SELECT FACTURA, FL.ID LINEA, PORCENTAJE, TIPOIMPUESTO, BASEIMPONIBLE, IMPORTE, BASEIMPONIBLE + IMPORTE,
SUM(NVL(BASEIMPONIBLE,0) + NVL(IMPORTE,0)) OVER (PARTITION BY FACTURA) TOTAL,
--ROUND(100 * (NVL(BASEIMPONIBLE,0) + NVL(IMPORTE,0)) / SUM(NVL(BASEIMPONIBLE,0) + NVL(IMPORTE,0)) OVER (PARTITION BY FACTURA),3) PORCENTAJE_SOBRE_TOTAL,
 TIPO, NUMFACTPROV, FECHAFACTURA, CONTRAALBARAN, ESTADO, IMPORTEBRUTO, IMPORTENETO
--* 
FROM REP_PRO_SIGLO.FAC_FACTURALINEA FL JOIN REP_PRO_SIGLO.FAC_FACTURA F
  ON (FL.FACTURA = F.ID)
WHERE FACTURA IN (
--SELECT COUNT(1) FROM (
SELECT FACTURA--, ORGANOGESTOR, COUNT(1) 
FROM (
SELECT FAL.ID, FAL.FACTURA, FA.ORGANOGESTOR
FROM REP_PRO_SIGLO.FAC_FACTURALINEA FAL
JOIN REP_PRO_SIGLO.FAC_FACTURA FA
  ON (FAL.FACTURA = FA.ID)
      WHERE TO_NUMBER(TO_CHAR(FA.FECHAFACTURA, 'YYYY')) = 2013
      AND FA.ESTADO IN ('CONCILIADA', 'PENDCONCILIAR', 'PENDREGISTRAR', 'REGISTRADA', 'TRAMITADA')
      AND FAL.TIPODESCUENTO IS NULL
      AND FA.TIPO NOT IN (6, 7, 8)
  )
  WHERE ORGANOGESTOR = 17550 
  GROUP BY FACTURA, ORGANOGESTOR
  HAVING COUNT(1) > 1
  --ORDER BY COUNT(1) DESC
  )
  AND GCDIRECTA IS NULL
  --AND IMPORTEBRUTO <> IMPORTENETO
  ORDER BY FACTURA