/* Formatted on 29/10/2013 14:34:06 (QP5 v5.163.1008.3004) */
DROP TABLE MSTR_MAE_ARTICULOS;
DROP TABLE MSTR_MAE_CATALOGO_NB;
DROP TABLE MSTR_MAE_CATALOGO_NA;
DROP TABLE MSTR_MAE_CATALOGO_N9;
DROP TABLE MSTR_MAE_CATALOGO_N8;
DROP TABLE MSTR_MAE_CATALOGO_N7;
DROP TABLE MSTR_MAE_CATALOGO_N6;
DROP TABLE MSTR_MAE_CATALOGO_N5;
DROP TABLE MSTR_MAE_CATALOGO_N4;
DROP TABLE MSTR_MAE_CATALOGO_N3;
DROP TABLE MSTR_MAE_CATALOGO_N2;
DROP TABLE MSTR_MAE_CATALOGO_N1;
DROP TABLE MSTR_MAE_CATALOGO_N0;

@MSTR_MAE_CATALOGO_N0.sql;
@MSTR_MAE_CATALOGO_N1.sql;
@MSTR_MAE_CATALOGO_N2.sql;
@MSTR_MAE_CATALOGO_N3.sql;
@MSTR_MAE_CATALOGO_N4.sql;
@MSTR_MAE_CATALOGO_N5.sql;
@MSTR_MAE_CATALOGO_N6.sql;
@MSTR_MAE_CATALOGO_N7.sql;
@MSTR_MAE_CATALOGO_N8.sql;
@MSTR_MAE_CATALOGO_N9.sql;
@MSTR_MAE_CATALOGO_NA.sql;
@MSTR_MAE_CATALOGO_NB.sql;
@MSTR_MAE_ARTICULOS.sql;

PURGE RECYCLEBIN;