/* Formatted on 20/01/2014 17:18:59 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
--SELECT DISTINCT NATID_CENTROCONSUMO FROM (
-- con servicios
--SELECT * FROM (
SELECT CC.ORGANICA NATID_ORGANOGESTOR
			,CC.ID NATID_CENTROCONSUMO
			--,CC.VERSION
			,CC.NOMBRE DESCR_CENTROCONSUMO
			,CC.CODIGO LDESC_CENTROCONSUMO
			--,CC.DESCRIPCION
			,CC.ESTADO ESTADO_CENTROCONSUMO
			--,SCC.ID
			--,SCC.VERSION
			--,SCC.SERVICIO
			--,SCC.CENTROCONSUMO
			--,SCC.RESPONSABLE
			,NVL (SCC.PORCENTAJE, 100) PORCENTAJE_SERVICIO
			,NVL(SCC.ESTADO,'N/A') ESTADO_PORCENTAJE_SERVICIO
			,NVL(SV.ID, -1) NATID_SERVICIO
			--,SV.VERSION
			,NVL(SV.CODIGO,'N/A') LDESC_SERVICIO
			,NVL(SV.DESCRIPCION,'Sin Servicio') DESCR_SERVICIO
			--,SV.ORGANOGESTOR
			--,SV.RESPONSABLE
			,NVL(SV.ESTADO,'N/A') ESTADO_SERVICIO
			--,UGCSV.ID
			--,UGCSV.VERSION
			,NVL(UGCSV.UNIDADGESTIONCLINICA, -1) NATID_UNIDAD_GESTION_CLINICA
			--,UGCSV.SERVICIO
			--,UGCSV.RESPONSABLE
			,(100) PORCENTAJE_UGC
			,NVL(UGCSV.ESTADO, 'N/A') ESTADO_PORCENTAJE_UGC
	FROM REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG CC
			 LEFT JOIN REP_PRO_SIGLO.ORG_SERVICIOCC@SYG SCC
				 ON (SCC.CENTROCONSUMO = CC.ID)
			 LEFT JOIN REP_PRO_SIGLO.ORG_SERVICIO@SYG SV
				 ON (SCC.SERVICIO = SV.ID)
			 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICASRV@SYG UGCSV
				 ON (UGCSV.SERVICIO = SV.ID)

--)
--) WHERE NATID_ORGANOGESTOR <> ORGANOGESTOR