/* Formatted on 11/12/2013 14:58:33 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_DET_CO01B;

CREATE TABLE MSTR_DET_CO01B
NOLOGGING
NOMONITORING
NOPARALLEL AS
		--SELECT SUM (CO01B), COUNT (CO01B)
		-- FROM (
		SELECT TRUNC (PED.FECHAPEDIDO) NATID_DIA
					/*,PED.EMPRESA NATID_PROVEEDOR*/
					,PED.ORGANOGESTOR NATID_ORGANOGESTOR
					,PRO.ECONOMICA NATID_ECONOMICA_N4
					,LIN.ARTICULO NATID_ARTICULO
					,COUNT (LIN.ID) CO01B
			FROM REP_PRO_SIGLO.PED_PEDIDOLINEA@SYG LIN
					 JOIN REP_PRO_SIGLO.PED_PEDIDO@SYG PED
						 ON (LIN.PEDIDO = PED.ID)
					 JOIN REP_PRO_SIGLO.PED_PROPUESTASL@SYG PRO
						 ON (LIN.PROPUESTALINEA = PRO.ID)
	GROUP BY TRUNC (PED.FECHAPEDIDO)
					/*,PED.EMPRESA*/
					,PED.ORGANOGESTOR
					,PRO.ECONOMICA
					,LIN.ARTICULO
--) WHERE NATID_PROVEEDOR IS NULL
/
ALTER TABLE MSTR_SIGLO.MSTR_DET_CO01B ADD
CONSTRAINT MSTR_DET_CO01B_PK
 PRIMARY KEY (NATID_DIA, /*NATID_PROVEEDOR, */NATID_ORGANOGESTOR, NATID_ECONOMICA_N4, NATID_ARTICULO)
 ENABLE
 VALIDATE
/
 ALTER TABLE MSTR_SIGLO.MSTR_DET_CO01B ADD
CONSTRAINT MSTR_DET_CO01B_R01
 FOREIGN KEY (NATID_ORGANOGESTOR)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ORGANOSGESTORES (NATID_ORGANOGESTOR)
 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_SIGLO.MSTR_DET_CO01B ADD
CONSTRAINT MSTR_DET_CO01B_R02
 FOREIGN KEY (NATID_ECONOMICA_N4)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ECONOMICA_N4 (NATID_ECONOMICA_N4)
 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_SIGLO.MSTR_DET_CO01B ADD
CONSTRAINT MSTR_DET_CO01B_R03
 FOREIGN KEY (NATID_ARTICULO)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ARTICULOS (NATID_ARTICULO)
 ENABLE
 VALIDATE
/
BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => 'MSTR_SIGLO'
																		,TabName => 'MSTR_DET_CO01B'
																		,Estimate_Percent => 0
																		,Method_Opt => 'FOR ALL COLUMNS SIZE 1'
																		,Degree => 4
																		,Cascade => FALSE
																		,No_Invalidate => FALSE);
END;
/