/* Formatted on 11/12/2013 14:29:00 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
	SELECT NVL (TRUNC (PED.FECHAPEDIDO), TO_DATE ('01/01/1900', 'DD/MM/YYYY')) NATID_DIA
				,PED.EMPRESA NATID_PROVEEDOR
				,NVL (DEC.DES, -1) NATID_ORGANOGESTOR
				, (CASE WHEN NIV.NIVEL <> 15 THEN -1 ELSE PRO.ECONOMICA END) NATID_ECONOMICA_N4
				,LIN.ARTICULO NATID_ARTICULO
				,COUNT (LIN.ID) CO01B
		FROM REP_PRO_SIGLO.PED_PEDIDO@SYG PED
				,REP_PRO_SIGLO.PED_PEDIDOLINEA@SYG LIN
				,REP_PRO_SIGLO.PED_PROPUESTASL@SYG PRO
				,REP_PRO_SIGLO.CTR_EXPEDIENTE@SYG EXP
				,(		SELECT CONNECT_BY_ROOT ID ORI, ID DES
								FROM REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG
							 WHERE PLATAFORMA IS NULL AND TIPO = 5012
					CONNECT BY PRIOR PLATAFORMA = ID) DEC
				,REP_PRO_SIGLO.CAT_NIVELVALOR@SYG NIV
	 WHERE PED.ID = LIN.PEDIDO AND LIN.PROPUESTALINEA = PRO.ID AND PED.EXPEDIENTE = EXP.ID(+) AND PED.ORGANOGESTOR = DEC.ORI(+) AND NIV.ID = PRO.ECONOMICA
GROUP BY NVL (TRUNC (PED.FECHAPEDIDO), TO_DATE ('01/01/1900', 'DD/MM/YYYY'))
				,PED.EMPRESA
				,DEC.DES
				,(CASE WHEN NIV.NIVEL <> 15 THEN -1 ELSE PRO.ECONOMICA END)
				,LIN.ARTICULO;