/* Formatted on 29/01/2014 14:37:40 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
SELECT
-- ID
--			,VERSION
--			,ARTICULO
--			,CENTROCONSUMO
			TO_CHAR(FECHA,'YYYY')
--			,UBICACIONVIRTUAL
--			,CANTIDADSALIDA
			,SUM(IMPORTESALIDA)
--			,FECHACADUCIDADEXISTENCIAS
--			,NHUSA
	FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN
    WHERE CENTROCONSUMO IS NOT NULL
    AND FECHA BETWEEN ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), -24) AND (ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), 1) - 1)
    GROUP BY TO_CHAR(FECHA,'YYYY')