/* Formatted on 13/01/2014 11:52:52 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
CREATE OR REPLACE VIEW EXCL_M_ARTICULOS
AS
SELECT NATID_ARTICULO
			,LDESC_ARTICULO
			,SUBSTR (DESCR_ARTICULO, 1, 100) DESCR_ARTICULO
			,DESCR_CATALOGO_NC
			,DESCR_CATALOGO_NB
			,DESCR_CATALOGO_NA
			,DESCR_CATALOGO_N9
			,DESCR_CATALOGO_N8
			,DESCR_CATALOGO_N7
			,DESCR_CATALOGO_N6
			,DESCR_CATALOGO_N5
			,DESCR_CATALOGO_N4
			,DESCR_CATALOGO_N3
			,DESCR_CATALOGO_N2
			,DESCR_CATALOGO_N1
			,DESCR_CATALOGO_N0
	FROM MSTR_MAE_ARTICULOS
			 JOIN MSTR_MAE_CATALOGO_NC
				 USING (NATID_CATALOGO_NC)
			 JOIN MSTR_MAE_CATALOGO_NB
				 USING (NATID_CATALOGO_NB)
			 JOIN MSTR_MAE_CATALOGO_NA
				 USING (NATID_CATALOGO_NA)
			 JOIN MSTR_MAE_CATALOGO_N9
				 USING (NATID_CATALOGO_N9)
			 JOIN MSTR_MAE_CATALOGO_N8
				 USING (NATID_CATALOGO_N8)
			 JOIN MSTR_MAE_CATALOGO_N7
				 USING (NATID_CATALOGO_N7)
			 JOIN MSTR_MAE_CATALOGO_N6
				 USING (NATID_CATALOGO_N6)
			 JOIN MSTR_MAE_CATALOGO_N5
				 USING (NATID_CATALOGO_N5)
			 JOIN MSTR_MAE_CATALOGO_N4
				 USING (NATID_CATALOGO_N4)
			 JOIN MSTR_MAE_CATALOGO_N3
				 USING (NATID_CATALOGO_N3)
			 JOIN MSTR_MAE_CATALOGO_N2
				 USING (NATID_CATALOGO_N2)
			 JOIN MSTR_MAE_CATALOGO_N1
				 USING (NATID_CATALOGO_N1)
			 JOIN MSTR_MAE_CATALOGO_N0
				 USING (NATID_CATALOGO_N0)