/* Formatted on 13/01/2014 11:58:04 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
CREATE OR REPLACE VIEW EXCL_MAE_CENTROSCONSUMO AS
	SELECT NATID_CENTROCONSUMO
				,LDESC_CENTROCUNSUMO
				,DESCR_CENTROCONSUMO
				,DESCR_ORGANOGESTOR
				,DESCR_PLATAFORMA_N1
				,DESCR_PLATAFORMA_N0
		FROM MSTR_MAE_CENTROSCONSUMO
				 JOIN MSTR_MAE_ORGANOSGESTORES
					 USING (NATID_ORGANOGESTOR)
				 JOIN MSTR_MAE_PLATAFORMA_N1
					 USING (NATID_PLATAFORMA_N1)
				 JOIN MSTR_MAE_PLATAFORMA_N0
					 USING (NATID_PLATAFORMA_N0)