DROP VIEW EXCL_H_INDICADORES_CONSUMO;

/* Formatted on 13/01/2014 16:13:02 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
CREATE OR REPLACE FORCE VIEW EXCL_H_INDICADORES_CONSUMO
(
	NATID_DIA
 ,NATID_ARTICULO
 ,NATID_CENTROCONSUMO
 ,NATID_ECONOMICA_N4
 ,CN03B_CANTIDAD
 ,CN03B_IMPORTE
) AS
	SELECT NATID_DIA
				,NATID_ARTICULO
				,NATID_CENTROCONSUMO
				,NATID_ECONOMICA_N4
				,CN03B_CANTIDAD
				,CN03B_IMPORTE
		FROM MSTR_DET_CN03B;
