SELECT 
count(*),  organogestor, descripcion
--ID, VERSION, EJERCICIO, 
--   ORGANOGESTOR, TIPO, FACTURAREINTEGRAR, 
--   PROVEEDOR, NUMFACTPROV, NUMFACTFOG, 
--   FECHAFACTURA, FECHAENTRADA, FECHAMECANIZACION, 
--   FECHAVENCIMIENTO, DENOMINACION, CONTRAALBARAN, 
--   ANTICIPOCAJAFIJA, FORMAPAGO, CUENTABANCARIA, 
--   ESTADO, FECHACAMBIOESTADO, USUARIOCAMBIOESTADO, 
--   MOTIVOCAMBIOESTADO, OBSCAMBIOESTADO, SITUACION, 
--   IDTRAMITACION, DEUDA, MANUAL, 
--   FIRMAFACTURAE, IMPORTEBRUTO, VERSIONTERCERO, 
--   TIPOPERCEPTOR, TIPOPERCEPTOREXENTO, NPROCEDIMIENTOJUDICIAL, 
--   NUMEROFOGREINT, NUMREGISTROFOG, SITUACIONPAGO, 
--   IMPORTENETO, TRACTOSUCESIVO, FECHAPAGO, 
--   NUMERODOCUMENTO, FECHACONTABILIZACION, USUARIOMECANIZACION, 
--   DIRECTA, PORCENTAJESDIRECTA, CONFORMADA, 
--   NUMEROEXPEDIENTE, NUMEROALTEXPEDIENTE, NUMEROCERTIFICACION, 
--   IMPORTEOBRAEJECUTADA, IMPORTEOBRAEJECUTADANOACRE, ABONOCUENTAACOPIOMATERIAL, 
--   ABONOCUENTAINSTALACIONEQUIPOS, IMPORTEANTICIPOCOMPENSAR, IMPORTEOBRAEJECUTADAANTERIOR, 
--   IMPORTEREVISIONPRECIOS, IMPORTEOTROSCONCEPTOS, IMPORTEACOPIOSCOMPENSAR, 
--   IMPORTEANTICIPOMAQUINARIAINSTA, IMPORTEEXCESOMEDICION, IMPORTEDESCUENTOIRPF
FROM REP_PRO_SIGLO.FAC_FACTURA JOIN REP_PRO_SIGLO.ORG_ORGANOGESTOR ON  (organogestor=ORG_ORGANOGESTOR.id)
group by  organogestor, descripcion