/* Formatted on 19/11/2013 12:42:47 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
--SELECT PL.*
--	FROM REP_PRO_SIGLO.PED_PEDIDOLINEA PL, REP_PRO_SIGLO.PED_PEDIDO PE
-- WHERE PL.ACTIVO = 'T' AND PE.ID = PL.PEDIDO;
--
--SELECT COUNT (*)
--	-- INTO V_N_CONT
--	FROM REP_PRO_SIGLO.PED_PROGRAMENTREGA ENT
-- WHERE ENT.ACTIVO = 'T' AND ENT.PEDIDOLINEA IN (491533) /*CAMPO.ID*/;

--SELECT COUNT (*), ENT.PEDIDOLINEA
--		-- INTO V_N_CONT
--		FROM REP_PRO_SIGLO.PED_PROGRAMENTREGA ENT
-- WHERE ENT.ACTIVO = 'T' /*AND ENT.PEDIDOLINEA IN (1346149) *//*CAMPO.ID*/
-- GROUP BY ENT.PEDIDOLINEA
-- HAVING COUNT (*)>1 ;

--SELECT SUM(GA02B)
--FROM (

DROP TABLE TEMP_DET_GA02B_01;
/

CREATE TABLE TEMP_DET_GA02B_01
NOLOGGING
NOMONITORING
PARALLEL AS
		SELECT TRUNC (MIN_FECHAENTREGA) NATID_DIA,
					 PED.ORGANOGESTOR NATID_ORGANOGESTOR,
					 ECONOMICA NATID_ECONOMICA_N4,
					 ARTICULO NATID_ARTICULO,
					 SUM (IMPORTELINEA) GA02B
			FROM ( -- Si la línea pedido tiene entrega coge la fecha minima de entrega
						SELECT	 MIN (PENT.FECHAENTREGA) MIN_FECHAENTREGA, PENT.PEDIDOLINEA
								FROM REP_PRO_SIGLO.PED_PROGRAMENTREGA@SYG PENT JOIN REP_PRO_SIGLO.PED_PEDIDOLINEA@SYG PL1 ON (PENT.PEDIDOLINEA = PL1.ID)
							 WHERE PENT.ACTIVO = 'T'
						GROUP BY PENT.PEDIDOLINEA) PLCE
					 JOIN REP_PRO_SIGLO.PED_PEDIDOLINEA@SYG PL2
						 ON (PLCE.PEDIDOLINEA = PL2.ID)
					 JOIN REP_PRO_SIGLO.PED_PEDIDO@SYG PED
						 ON (PED.ID = PL2.PEDIDO)
					 JOIN REP_PRO_SIGLO.PED_PROPUESTASL@SYG PRO
						 ON (PL2.PROPUESTALINEA = PRO.ID)
		 WHERE PL2.ACTIVO = 'T'
	GROUP BY TRUNC (MIN_FECHAENTREGA),
					 PED.ORGANOGESTOR,
					 ECONOMICA,
					 ARTICULO;
/

DROP TABLE TEMP_DET_GA02B_02;
/

CREATE TABLE TEMP_DET_GA02B_02
NOLOGGING
NOMONITORING
PARALLEL AS
		SELECT TRUNC (FECHAPEDIDO) NATID_DIA,
					 PED.ORGANOGESTOR NATID_ORGANOGESTOR,
					 ECONOMICA NATID_ECONOMICA_N4,
					 ARTICULO NATID_ARTICULO,
					 SUM (IMPORTELINEA) GA02B
			FROM REP_PRO_SIGLO.PED_PEDIDOLINEA@SYG PL2
					 JOIN REP_PRO_SIGLO.PED_PEDIDO@SYG PED
						 ON (PED.ID = PL2.PEDIDO)
					 JOIN REP_PRO_SIGLO.PED_PROPUESTASL@SYG PRO
						 ON (PL2.PROPUESTALINEA = PRO.ID)
		 WHERE PL2.ACTIVO = 'T'
					 -- Si la línea pedido no tiene entrega coge la fecha del pedido
					 AND PL2.ID NOT IN (SELECT DISTINCT ENT.PEDIDOLINEA
																FROM REP_PRO_SIGLO.PED_PROGRAMENTREGA@SYG ENT
															 WHERE ENT.ACTIVO = 'T')
	GROUP BY TRUNC (FECHAPEDIDO),
					 PED.ORGANOGESTOR,
					 ECONOMICA,
					 ARTICULO;
/

DROP TABLE MSTR_DET_GA02B;
/

CREATE TABLE MSTR_DET_GA02B
NOLOGGING
NOMONITORING
PARALLEL AS
		SELECT NATID_DIA,
					 NATID_ORGANOGESTOR,
					 NATID_ECONOMICA_N4,
					 NATID_ARTICULO,
					 SUM (GA02B) GA02B
			FROM (SELECT GA02B,
									 NATID_ARTICULO,
									 NATID_DIA,
									 NATID_ECONOMICA_N4,
									 NATID_ORGANOGESTOR
							FROM TEMP_DET_GA02B_01
						UNION ALL
						SELECT GA02B,
									 NATID_ARTICULO,
									 NATID_DIA,
									 NATID_ECONOMICA_N4,
									 NATID_ORGANOGESTOR
							FROM TEMP_DET_GA02B_02)
	GROUP BY NATID_DIA,
					 NATID_ORGANOGESTOR,
					 NATID_ECONOMICA_N4,
					 NATID_ARTICULO;
/

ALTER TABLE MSTR_SIGLO.MSTR_DET_GA02B ADD
CONSTRAINT MSTR_DET_GA02B_PK
 PRIMARY KEY (NATID_DIA, NATID_ORGANOGESTOR, NATID_ECONOMICA_N4, NATID_ARTICULO)
 ENABLE
 VALIDATE;
 ALTER TABLE MSTR_SIGLO.MSTR_DET_GA02B ADD
CONSTRAINT MSTR_DET_GA02B_C01
 CHECK (NATID_DIA IS NOT NULL)
 ENABLE
 VALIDATE;
 ALTER TABLE MSTR_SIGLO.MSTR_DET_GA02B ADD
CONSTRAINT MSTR_DET_GA02B_C02
 CHECK (NATID_ORGANOGESTOR IS NOT NULL)
 ENABLE
 VALIDATE;
ALTER TABLE MSTR_SIGLO.MSTR_DET_GA02B ADD
CONSTRAINT MSTR_DET_GA02B_C03
 CHECK (NATID_ECONOMICA_N4 IS NOT NULL)
 ENABLE
 VALIDATE;
 ALTER TABLE MSTR_SIGLO.MSTR_DET_GA02B ADD
CONSTRAINT MSTR_DET_GA02B_C04
 CHECK (NATID_ARTICULO IS NOT NULL)
 ENABLE
 VALIDATE;
 ALTER TABLE MSTR_SIGLO.MSTR_DET_GA02B ADD
CONSTRAINT MSTR_DET_GA02B_R01
 FOREIGN KEY (NATID_ARTICULO)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ARTICULOS (NATID_ARTICULO)
 ENABLE
 VALIDATE;
ALTER TABLE MSTR_SIGLO.MSTR_DET_GA02B ADD
CONSTRAINT MSTR_DET_GA02B_R02
 FOREIGN KEY (NATID_ECONOMICA_N4)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ECONOMICA_N4 (NATID_ECONOMICA_N4)
 ENABLE
 VALIDATE;
BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => 'MSTR_SIGLO',
																		 TabName => 'MSTR_DET_GA02B',
																		 Estimate_Percent => SYS.DBMS_STATS.AUTO_SAMPLE_SIZE,
																		 Method_Opt => 'FOR ALL INDEXED COLUMNS SIZE AUTO ',
																		 Degree => NULL,
																		 Cascade => TRUE,
																		 No_Invalidate => FALSE);
END;