/* Formatted on 29/10/2013 13:53:16 (QP5 v5.163.1008.3004) */
--DROP TABLE MSTR_MAE_CATALOGO_N1;

CREATE TABLE MSTR_MAE_CATALOGO_N1
NOLOGGING
NOMONITORING
NOPARALLEL
AS
   SELECT ID NATID_CATALOGO_N1,
          DESCRIPCION DESCR_CATALOGO_N1,
          CODIGOCONCATENADO LDESC_CATALOGO_N1,
          NIVEL NIVEL_SIGLO_N1,
          VALORPADRE NATID_CATALOGO_N0
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 5 AND ACTIVO = 'T' AND VALORPADRE IN (SELECT NATID_CATALOGO_N0 FROM MSTR_MAE_CATALOGO_N0)
   UNION ALL
   SELECT -1 NATID_CATALOGO_N1,
          'n/a' DESCR_CATALOGO_N1,
          'n/a' LDESC_CATALOGO_N1,
          18 NIVEL_SIGLO_N1,
          -1 NATID_CATALOGO_N0
     FROM DUAL;

/

ALTER TABLE MSTR_MAE_CATALOGO_N1 ADD (
  CONSTRAINT MSTR_MAE_CATALOGO_N1_PK
  PRIMARY KEY
  (NATID_CATALOGO_N1)
  USING INDEX
    TABLESPACE USERS
    NOLOGGING
);

/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_CATALOGO_N1 ADD
CONSTRAINT MSTR_MAE_CATALOGO_N1_R01
 FOREIGN KEY (NATID_CATALOGO_N0)
 REFERENCES MSTR_SIGLO.MSTR_MAE_CATALOGO_N0 (NATID_CATALOGO_N0)
 ENABLE
 VALIDATE
/

BEGIN
   SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName            => 'MSTR_SIGLO',
                                      TabName            => 'MSTR_MAE_CATALOGO_N1',
                                      Estimate_Percent   => 0,
                                      Method_Opt         => 'FOR ALL COLUMNS SIZE 1',
                                      Degree             => 4,
                                      Cascade            => FALSE,
                                      No_Invalidate      => FALSE);
END;