/* Formatted on 06/11/2013 16:28:37 (QP5 v5.163.1008.3004) */
--DROP TABLE MSTR_MAE_ECONOMICA_N1;

CREATE TABLE MSTR_MAE_ECONOMICA_N1
NOLOGGING
NOMONITORING
NOPARALLEL
AS
   SELECT ID NATID_ECONOMICA_N1,
          DESCRIPCION DESCR_ECONOMICA_N1,
          CODIGOCONCATENADO LDESC_ECONOMICA_N1,
          VALORPADRE NATID_ECONOMICA_N0
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 4 AND VALORPADRE IN (SELECT NATID_ECONOMICA_N0 FROM MSTR_MAE_ECONOMICA_N0)
   UNION ALL
   SELECT -1 NATID_ECONOMICA_N1,
          'n/a' DESCR_ECONOMICA_N1,
          'n/a' LDESC_ECONOMICA_N1,
          -1 NATID_ECONOMICA_N0
     FROM DUAL
   UNION ALL
   -- Replica N0
   SELECT ID NATID_ECONOMICA_N1,
          DESCRIPCION DESCR_ECONOMICA_N1,
          CODIGOCONCATENADO || '*' LDESC_ECONOMICA_N1,
          ID NATID_ECONOMICA_N0
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 4 AND VALORPADRE IS NULL;

/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_ECONOMICA_N1 ADD
CONSTRAINT MSTR_MAE_ECONOMICA_N1_PK
 PRIMARY KEY (NATID_ECONOMICA_N1)

 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_SIGLO.MSTR_MAE_ECONOMICA_N1 ADD
CONSTRAINT MSTR_MAE_ECONOMICA_N1_R01
 FOREIGN KEY (NATID_ECONOMICA_N0)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ECONOMICA_N0 (NATID_ECONOMICA_N0)
 ENABLE
 VALIDATE
/

CREATE INDEX MSTR_SIGLO.MSTR_MAE_ECONOMICA_N1_IX01
   ON MSTR_SIGLO.MSTR_MAE_ECONOMICA_N1 (NATID_ECONOMICA_N0)
   NOLOGGING
   NOPARALLEL;

/

BEGIN
   SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName            => 'MSTR_SIGLO',
                                      TabName            => 'MSTR_MAE_ECONOMICA_N1',
                                      Estimate_Percent   => 0,
                                      Method_Opt         => 'FOR ALL COLUMNS SIZE 1',
                                      Degree             => 4,
                                      Cascade            => FALSE,
                                      No_Invalidate      => FALSE);
END;
/