/* Formatted on 27/01/2014 14:38:22 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_DET_CN03B_REPARTIDO;
CREATE TABLE MSTR_DET_CN03B_REPARTIDO
NOLOGGING
NOMONITORING
PARALLEL AS
	--SELECT SUM(IMPORTE_REPARTIDO)
	--FROM (
	SELECT CN03B.NATID_DIA
				,CN03B.NATID_ARTICULO
				,NATID_CENTROCONSUMO
				,CN03B.NATID_ECONOMICA_N4
				,CN03B.CN03B_CANTIDAD * HLP.PORCENTAJE CN03B_CANTIDAD
				,CN03B.CN03B_IMPORTE * HLP.PORCENTAJE CN03B_IMPORTE
				,HLP.PORCENTAJE
				--,CN03B.CN03B_CANTIDAD * HLP.PORCENTAJE CANTIDAD_REPARTIDA
				--,CN03B.CN03B_IMPORTE * HLP.PORCENTAJE IMPORTE_REPARTIDO
				--,HLP.NATID_ORGANOGESTOR
				--,NATID_CENTROCONSUMO
				--,HLP.DESCR_CENTROCONSUMO
				--,HLP.LDESC_CENTROCONSUMO
				--,HLP.ESTADO_CENTROCONSUMO
				,HLP.TIPO TIPO_ER
				,HLP.NATID_SERVICIO
				--,HLP.DESCR_SERVICIO
				--,HLP.LDESC_SERVICIO
				--,HLP.ESTADO_SERVICIO
				--,HLP.PORCENTAJE
				,HLP.NATID_UNIDAD_GESTION_CLINICA
		--,HLP.DESCR_UNIDAD_GESTION_CLINICA
		--,HLP.LDESC_UNIDAD_GESTION_CLINICA
		--,HLP.ESTADO_UNIDAD_GESTION_CLINICA
		FROM MSTR_DET_CN03B CN03B LEFT JOIN MSTR_HLP_PORCENTAJES_CC_SV_UG HLP USING (NATID_CENTROCONSUMO)
	 WHERE HLP.ESTADO_SERVICIO NOT IN ('BORRADO', 'RECHAZADO') AND HLP.ESTADO_UNIDAD_GESTION_CLINICA NOT IN ('BORRADO', 'RECHAZADO')
--AND NATID_CENTROCONSUMO IN (63366) --14169--13153
--)
/
ALTER TABLE MSTR_SIGLO.MSTR_DET_CN03B_REPARTIDO ADD
CONSTRAINT MSTR_DET_CN03B_REPARTIDO_PK
 PRIMARY KEY (NATID_DIA, NATID_ARTICULO, NATID_CENTROCONSUMO, NATID_SERVICIO, NATID_UNIDAD_GESTION_CLINICA)
NOLOGGING
 NOMONITORING
 PARALLEL
/

BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => 'MSTR_SIGLO'
																		,TabName => 'MSTR_DET_CN03B_REPARTIDO'
																		,Estimate_Percent => SYS.DBMS_STATS.AUTO_SAMPLE_SIZE
																		,Method_Opt => 'FOR ALL INDEXED COLUMNS SIZE AUTO '
																		,Degree => NULL
																		,Cascade => TRUE
																		,No_Invalidate => FALSE);
END;
--MSTR_DET_CN03B_REPARTIDO_PK