/* Formatted on 29/10/2013 13:55:09 (QP5 v5.163.1008.3004) */
--DROP TABLE MSTR_MAE_CATALOGO_N2;

CREATE TABLE MSTR_MAE_CATALOGO_N2
NOLOGGING
NOMONITORING
NOPARALLEL
AS
   SELECT ID NATID_CATALOGO_N2,
          DESCRIPCION DESCR_CATALOGO_N2,
          CODIGOCONCATENADO LDESC_CATALOGO_N2,
          NIVEL NIVEL_SIGLO_N2,
          VALORPADRE NATID_CATALOGO_N1
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 5 AND ACTIVO = 'T' AND VALORPADRE IN (SELECT NATID_CATALOGO_N1 FROM MSTR_MAE_CATALOGO_N1)
   UNION ALL
   SELECT -1 NATID_CATALOGO_N2,
          'n/a' DESCR_CATALOGO_N2,
          'n/a' LDESC_CATALOGO_N2,
          19 NIVEL_SIGLO_N2,
          -1 NATID_CATALOGO_N1
     FROM DUAL
   UNION ALL
   -- Replica N1
   SELECT ID NATID_CATALOGO_N2,
          DESCRIPCION DESCR_CATALOGO_N2,
          CODIGOCONCATENADO || '*' LDESC_CATALOGO_N2,
          19 NIVEL_SIGLO_N2,
          ID NATID_CATALOGO_N1
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 5 AND ACTIVO = 'T' AND VALORPADRE IN (SELECT NATID_CATALOGO_N0 FROM MSTR_MAE_CATALOGO_N0);

/

ALTER TABLE MSTR_MAE_CATALOGO_N2 ADD (
  CONSTRAINT MSTR_MAE_CATALOGO_N2_PK
  PRIMARY KEY
  (NATID_CATALOGO_N2)
  USING INDEX
    TABLESPACE USERS
    NOLOGGING
);

/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_CATALOGO_N2 ADD
CONSTRAINT MSTR_MAE_CATALOGO_N2_R01
 FOREIGN KEY (NATID_CATALOGO_N1)
 REFERENCES MSTR_SIGLO.MSTR_MAE_CATALOGO_N1 (NATID_CATALOGO_N1)
 ENABLE
 VALIDATE
/

BEGIN
   SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName            => 'MSTR_SIGLO',
                                      TabName            => 'MSTR_MAE_CATALOGO_N2',
                                      Estimate_Percent   => 0,
                                      Method_Opt         => 'FOR ALL COLUMNS SIZE 1',
                                      Degree             => 4,
                                      Cascade            => FALSE,
                                      No_Invalidate      => FALSE);
END;