DROP TABLE MSTR_MAE_ORGANOSGESTORES
/
DROP TABLE MSTR_MAE_PLATAFORMA_N1
/
/* Formatted on 10/12/2013 12:16:15 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_MAE_PLATAFORMA_N0
/
CREATE TABLE MSTR_MAE_PLATAFORMA_N0
NOLOGGING
NOMONITORING
NOPARALLEL AS
	SELECT -1 NATID_PLATAFORMA_N0, 'n/a' DESCR_PLATAFORMA_N0 FROM DUAL
	UNION ALL
	SELECT ID NATID_PLATAFORMA_N0, DESCRIPCION DESCR_PLATAFORMA_N0
		FROM REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG
	 WHERE PLATAFORMA IS NULL
--WHERE ACTIVO = 'F';
/
ALTER TABLE MSTR_SIGLO.MSTR_MAE_PLATAFORMA_N0 ADD
CONSTRAINT MSTR_MAE_PLATAFORMA_N0_PK
 PRIMARY KEY (NATID_PLATAFORMA_N0)
 ENABLE
 VALIDATE
/
BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => 'MSTR_SIGLO'
																		,TabName => 'MSTR_MAE_PLATAFORMA_N0'
																		,Estimate_Percent => 0
																		,Method_Opt => 'FOR ALL COLUMNS SIZE 1'
																		,Degree => 4
																		,Cascade => FALSE
																		,No_Invalidate => FALSE);
END;
/
/*
   SELECT ID NATID_CATALOGO_N1,
          DESCRIPCION DESCR_CATALOGO_N1,
          CODIGOCONCATENADO LDESC_CATALOGO_N1,
          NIVEL NIVEL_SIGLO_N1,
          VALORPADRE NATID_CATALOGO_N0
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 5 AND ACTIVO = ''T'' AND VALORPADRE IN (SELECT NATID_CATALOGO_N0 FROM MSTR_MAE_CATALOGO_N0)
   UNION ALL
   SELECT -1 NATID_CATALOGO_N1,
          ''n/a'' DESCR_CATALOGO_N1,
          ''n/a'' LDESC_CATALOGO_N1,
          18 NIVEL_SIGLO_N1,
          -1 NATID_CATALOGO_N0
     FROM DUAL';
*/
CREATE TABLE MSTR_MAE_PLATAFORMA_N1
NOLOGGING
NOMONITORING
NOPARALLEL AS
	SELECT -1 NATID_PLATAFORMA_N1
				,'n/a' DESCR_PLATAFORMA_N1
				,'n/a' LDESC_PLATAFORMA_N1
				,-1 NATID_PLATAFORMA_N0
		FROM DUAL
	UNION ALL
	SELECT ID NATID_PLATAFORMA_N1
				,DESCRIPCION DESCR_PLATAFORMA_N1
				,CODIGO LDESC_PLATAFORMA_N1
				,PLATAFORMA NATID_PLATAFORMA_N0
		FROM REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG
	 WHERE PLATAFORMA IN (SELECT NATID_PLATAFORMA_N0 FROM MSTR_MAE_PLATAFORMA_N0)
	UNION ALL
	-- Replica N0
	SELECT ID NATID_PLATAFORMA_N1
				,DESCRIPCION DESCR_PLATAFORMA_N1
				,CODIGO || '*' LDESC_PLATAFORMA_N1
				,ID NATID_PLATAFORMA_N0
		FROM REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG
	 WHERE PLATAFORMA IS NULL
/
ALTER TABLE MSTR_SIGLO.MSTR_MAE_PLATAFORMA_N1 ADD
CONSTRAINT MSTR_MAE_PLATAFORMA_N1_PK
 PRIMARY KEY (NATID_PLATAFORMA_N1)
 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_SIGLO.MSTR_MAE_PLATAFORMA_N1 ADD
CONSTRAINT MSTR_MAE_PLATAFORMA_N1_R01
 FOREIGN KEY (NATID_PLATAFORMA_N0)
 REFERENCES MSTR_SIGLO.MSTR_MAE_PLATAFORMA_N0 (NATID_PLATAFORMA_N0)
 ENABLE
 VALIDATE
/
CREATE INDEX MSTR_SIGLO.MSTR_MAE_PLATAFORMA_N1_IX01
	ON MSTR_SIGLO.MSTR_MAE_PLATAFORMA_N1 (NATID_PLATAFORMA_N0)
	NOLOGGING
	NOPARALLEL
/
BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => 'MSTR_SIGLO'
																		,TabName => 'MSTR_MAE_PLATAFORMA_N1'
																		,Estimate_Percent => 0
																		,Method_Opt => 'FOR ALL COLUMNS SIZE 1'
																		,Degree => 4
																		,Cascade => FALSE
																		,No_Invalidate => FALSE);
END;
/
/*
   SELECT ID NATID_ECONOMICA_N2,
          DESCRIPCION DESCR_ECONOMICA_N2,
          CODIGOCONCATENADO LDESC_ECONOMICA_N2,
          VALORPADRE NATID_ECONOMICA_N1
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 4
          AND VALORPADRE IN (SELECT NATID_ECONOMICA_N1
                               FROM MSTR_MAE_ECONOMICA_N1
                              WHERE INSTR (LDESC_ECONOMICA_N1, ''*'') = 0)

*/
CREATE TABLE MSTR_MAE_ORGANOSGESTORES
NOLOGGING
NOMONITORING
NOPARALLEL AS
	SELECT -1 NATID_ORGANOGESTOR
				,'n/a' DESCR_ORGANOGESTOR
				,'n/a' LDESC_ORGANOGESTOR
				,-1 NATID_PLATAFORMA_N1
		FROM DUAL
	UNION ALL
	SELECT ID NATID_ORGANOGESTOR
				,DESCRIPCION DESCR_ORGANOGESTOR
				,CODIGO LDESC_ORGANOGESTOR
				,PLATAFORMA NATID_PLATAFORMA_N1
		FROM REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG
	 WHERE PLATAFORMA IN (SELECT NATID_PLATAFORMA_N1
													FROM MSTR_MAE_PLATAFORMA_N1
												 WHERE INSTR (LDESC_PLATAFORMA_N1, '*') = 0)
	UNION ALL
	-- Replica N0
	SELECT ID NATID_ORGANOGESTOR
				,DESCRIPCION DESCR_ORGANOGESTOR
				,CODIGO || '**' LDESC_ORGANOGESTOR
				,ID NATID_PLATAFORMA_N1
		FROM REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG
	 WHERE PLATAFORMA IS NULL
	UNION ALL
	-- Replica N1
	SELECT ID NATID_ORGANOGESTOR
				,DESCRIPCION DESCR_ORGANOGESTOR
				,CODIGO || '*' LDESC_ORGANOGESTOR
				,ID NATID_PLATAFORMA_N1
		FROM REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG
	 WHERE PLATAFORMA IN (SELECT NATID_PLATAFORMA_N1 FROM MSTR_MAE_PLATAFORMA_N1)
/
ALTER TABLE MSTR_SIGLO.MSTR_MAE_ORGANOSGESTORES ADD
CONSTRAINT MSTR_MAE_ORGANOSGESTORES_PK
 PRIMARY KEY (NATID_ORGANOGESTOR)
 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_SIGLO.MSTR_MAE_ORGANOSGESTORES ADD
CONSTRAINT MSTR_MAE_ORGANOSGESTORES_R01
 FOREIGN KEY (NATID_PLATAFORMA_N1)
 REFERENCES MSTR_SIGLO.MSTR_MAE_PLATAFORMA_N1 (NATID_PLATAFORMA_N1)
 ENABLE
 VALIDATE
/
CREATE INDEX MSTR_SIGLO.MSTR_MAE_ORGANOSGESTORES_IX01
	ON MSTR_SIGLO.MSTR_MAE_ORGANOSGESTORES (NATID_PLATAFORMA_N1)
	NOLOGGING
	NOPARALLEL
/
BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => 'MSTR_SIGLO'
																		,TabName => 'MSTR_MAE_ORGANOSGESTORES'
																		,Estimate_Percent => 0
																		,Method_Opt => 'FOR ALL COLUMNS SIZE 1'
																		,Degree => 4
																		,Cascade => FALSE
																		,No_Invalidate => FALSE);
END;
/


/*
  -- Replica N0
   SELECT ID NATID_ECONOMICA_N2,
          DESCRIPCION DESCR_ECONOMICA_N2,
          CODIGOCONCATENADO || ''**'' LDESC_ECONOMICA_N2,
          ID NATID_ECONOMICA_N1
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 4 AND VALORPADRE IS NULL
   UNION ALL
   -- Replica N1
   SELECT ID NATID_ECONOMICA_N2,
          DESCRIPCION DESCR_ECONOMICA_N2,
          CODIGOCONCATENADO || ''*'' LDESC_ECONOMICA_N2,
          ID NATID_ECONOMICA_N1
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 4 AND VALORPADRE IN (SELECT NATID_ECONOMICA_N0 FROM MSTR_MAE_ECONOMICA_N0)';


*/
-- No hay N3
--SELECT ID NATID_PLATAFORMA_N3
--						,DESCRIPCION DESCR_PLATAFORMA_N3
--						,CODIGO LDESC_PLATAFORMA_N3
--						,PLATAFORMA NATID_PLATAFORMA_N2
--		FROM REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG
-- WHERE PLATAFORMA IN (SELECT NATID_PLATAFORMA_N2
--																								FROM MSTR_MAE_PLATAFORMA_N2
--																						 WHERE INSTR (LDESC_PLATAFORMA_N2, '*') = 0)