/* Formatted on 14/10/2013 12:50:18 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE VIEW MSTR_MAE_CAPITULO_N1
AS
   SELECT ID NATID_CAPITULO_N1,
          DESCRIPCION DESCR_CAPITULO_N1,
          CODIGO LDESC_CAPITULO_N1,
          VALORPADRE NATID_CAPITULO_N0
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 4 AND VALORPADRE IN (SELECT NATID_CAPITULO_N0 FROM MSTR_MAE_CAPITULO_N0)