/* Formatted on 29/10/2013 14:07:20 (QP5 v5.163.1008.3004) */
--DROP TABLE MSTR_MAE_CATALOGO_N8;

CREATE TABLE MSTR_MAE_CATALOGO_N8
NOLOGGING
NOMONITORING
NOPARALLEL
AS
   SELECT ID NATID_CATALOGO_N8,
          DESCRIPCION DESCR_CATALOGO_N8,
          CODIGOCONCATENADO LDESC_CATALOGO_N8,
          NIVEL NIVEL_SIGLO_N8,
          VALORPADRE NATID_CATALOGO_N7
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N7
                               FROM MSTR_MAE_CATALOGO_N7
                              WHERE INSTR (LDESC_CATALOGO_N7, '*') = 0)
   UNION ALL
   SELECT -1 NATID_CATALOGO_N8,
          'n/a' DESCR_CATALOGO_N8,
          'n/a' LDESC_CATALOGO_N8,
          5058 NIVEL_SIGLO_N8,
          -1 NATID_CATALOGO_N7
     FROM DUAL
   UNION ALL
   -- Replica N1
   SELECT ID NATID_CATALOGO_N8,
          DESCRIPCION DESCR_CATALOGO_N8,
          CODIGOCONCATENADO || '*******' LDESC_CATALOGO_N8,
          5058 NIVEL_SIGLO_N8,
          ID NATID_CATALOGO_N7
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 5 AND ACTIVO = 'T' AND VALORPADRE IN (SELECT NATID_CATALOGO_N0 FROM MSTR_MAE_CATALOGO_N0)
   UNION ALL
   --Replica N2
   SELECT ID NATID_CATALOGO_N8,
          DESCRIPCION DESCR_CATALOGO_N8,
          CODIGOCONCATENADO || '******' LDESC_CATALOGO_N8,
          5058 NIVEL_SIGLO_N8,
          ID NATID_CATALOGO_N7
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N1
                               FROM MSTR_MAE_CATALOGO_N1
                              WHERE INSTR (LDESC_CATALOGO_N1, '*') = 0)
   UNION ALL
   -- Replica N3
   SELECT ID NATID_CATALOGO_N8,
          DESCRIPCION DESCR_CATALOGO_N8,
          CODIGOCONCATENADO || '*****' LDESC_CATALOGO_N8,
          5058 NIVEL_SIGLO_N8,
          ID NATID_CATALOGO_N7
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N2
                               FROM MSTR_MAE_CATALOGO_N2
                              WHERE INSTR (LDESC_CATALOGO_N2, '*') = 0)
   UNION ALL
   -- Replica N4
   SELECT ID NATID_CATALOGO_N8,
          DESCRIPCION DESCR_CATALOGO_N8,
          CODIGOCONCATENADO || '****' LDESC_CATALOGO_N8,
          5058 NIVEL_SIGLO_N8,
          ID NATID_CATALOGO_N7
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N3
                               FROM MSTR_MAE_CATALOGO_N3
                              WHERE INSTR (LDESC_CATALOGO_N3, '*') = 0)
   UNION ALL
   -- Replica N5
   SELECT ID NATID_CATALOGO_N8,
          DESCRIPCION DESCR_CATALOGO_N8,
          CODIGOCONCATENADO || '***' LDESC_CATALOGO_N8,
          5058 NIVEL_SIGLO_N8,
          ID NATID_CATALOGO_N7
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N4
                               FROM MSTR_MAE_CATALOGO_N4
                              WHERE INSTR (LDESC_CATALOGO_N4, '*') = 0)
   UNION ALL
   -- Replica N6
   SELECT ID NATID_CATALOGO_N8,
          DESCRIPCION DESCR_CATALOGO_N8,
          CODIGOCONCATENADO || '**' LDESC_CATALOGO_N8,
          5058 NIVEL_SIGLO_N8,
          ID NATID_CATALOGO_N7
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N5
                               FROM MSTR_MAE_CATALOGO_N5
                              WHERE INSTR (LDESC_CATALOGO_N5, '*') = 0)
   UNION ALL
   -- Replica N7
   SELECT ID NATID_CATALOGO_N8,
          DESCRIPCION DESCR_CATALOGO_N8,
          CODIGOCONCATENADO || '*' LDESC_CATALOGO_N8,
          5058 NIVEL_SIGLO_N8,
          ID NATID_CATALOGO_N7
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N6
                               FROM MSTR_MAE_CATALOGO_N6
                              WHERE INSTR (LDESC_CATALOGO_N6, '*') = 0);

/

ALTER TABLE MSTR_MAE_CATALOGO_N8 ADD (
  CONSTRAINT MSTR_MAE_CATALOGO_N8_PK
  PRIMARY KEY
  (NATID_CATALOGO_N8)
  USING INDEX
    TABLESPACE USERS
    NOLOGGING
);

/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_CATALOGO_N8 ADD
CONSTRAINT MSTR_MAE_CATALOGO_N8_R01
 FOREIGN KEY (NATID_CATALOGO_N7)
 REFERENCES MSTR_SIGLO.MSTR_MAE_CATALOGO_N7 (NATID_CATALOGO_N7)
 ENABLE
 VALIDATE
/

BEGIN
   SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName            => 'MSTR_SIGLO',
                                      TabName            => 'MSTR_MAE_CATALOGO_N8',
                                      Estimate_Percent   => 0,
                                      Method_Opt         => 'FOR ALL COLUMNS SIZE 1',
                                      Degree             => 4,
                                      Cascade            => FALSE,
                                      No_Invalidate      => FALSE);
END;