/* Formatted on 29/10/2013 13:59:52 (QP5 v5.163.1008.3004) */
--DROP TABLE MSTR_MAE_CATALOGO_N4;

CREATE TABLE MSTR_MAE_CATALOGO_N4
NOLOGGING
NOMONITORING
NOPARALLEL
AS
   SELECT ID NATID_CATALOGO_N4,
          DESCRIPCION DESCR_CATALOGO_N4,
          CODIGOCONCATENADO LDESC_CATALOGO_N4,
          NIVEL NIVEL_SIGLO_N4,
          VALORPADRE NATID_CATALOGO_N3
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N3
                               FROM MSTR_MAE_CATALOGO_N3
                              WHERE INSTR (LDESC_CATALOGO_N3, '*') = 0)
   UNION ALL
   SELECT -1 NATID_CATALOGO_N4,
          'n/a' DESCR_CATALOGO_N4,
          'n/a' LDESC_CATALOGO_N4,
          21 NIVEL_SIGLO_N4,
          -1 NATID_CATALOGO_N3
     FROM DUAL
   UNION ALL
   -- Replica N1
   SELECT ID NATID_CATALOGO_N4,
          DESCRIPCION DESCR_CATALOGO_N4,
          CODIGOCONCATENADO || '***' LDESC_CATALOGO_N4,
          21 NIVEL_SIGLO_N4,
          ID NATID_CATALOGO_N3
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 5 AND ACTIVO = 'T' AND VALORPADRE IN (SELECT NATID_CATALOGO_N0 FROM MSTR_MAE_CATALOGO_N0)
   UNION ALL
   --Replica N2
   SELECT ID NATID_CATALOGO_N4,
          DESCRIPCION DESCR_CATALOGO_N4,
          CODIGOCONCATENADO || '**' LDESC_CATALOGO_N4,
          21 NIVEL_SIGLO_N4,
          ID NATID_CATALOGO_N3
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N1
                               FROM MSTR_MAE_CATALOGO_N1
                              WHERE INSTR (LDESC_CATALOGO_N1, '*') = 0)
   UNION ALL
   -- Replica N3
   SELECT ID NATID_CATALOGO_N4,
          DESCRIPCION DESCR_CATALOGO_N4,
          CODIGOCONCATENADO || '*' LDESC_CATALOGO_N4,
          21 NIVEL_SIGLO_N4,
          ID NATID_CATALOGO_N3
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N2
                               FROM MSTR_MAE_CATALOGO_N2
                              WHERE INSTR (LDESC_CATALOGO_N2, '*') = 0);

/

ALTER TABLE MSTR_MAE_CATALOGO_N4 ADD (
  CONSTRAINT MSTR_MAE_CATALOGO_N4_PK
  PRIMARY KEY
  (NATID_CATALOGO_N4)
  USING INDEX
    TABLESPACE USERS
    NOLOGGING
);

/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_CATALOGO_N4 ADD
CONSTRAINT MSTR_MAE_CATALOGO_N4_R01
 FOREIGN KEY (NATID_CATALOGO_N3)
 REFERENCES MSTR_SIGLO.MSTR_MAE_CATALOGO_N3 (NATID_CATALOGO_N3)
 ENABLE
 VALIDATE
/

BEGIN
   SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName            => 'MSTR_SIGLO',
                                      TabName            => 'MSTR_MAE_CATALOGO_N4',
                                      Estimate_Percent   => 0,
                                      Method_Opt         => 'FOR ALL COLUMNS SIZE 1',
                                      Degree             => 4,
                                      Cascade            => FALSE,
                                      No_Invalidate      => FALSE);
END;