/* Formatted on 19/12/2013 17:45:36 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
CREATE TABLE MSTR_MAE_CENTROSCONSUMO
NOLOGGING
NOMONITORING
NOPARALLEL AS
	SELECT ID NATID_CENTROCONSUMO
				--	,VERSION
				,NOMBRE DESCR_CENTROCONSUMO
				,CODIGO LDESC_CENTROCUNSUMO
				--	,DESCRIPCION
				,ORGANICA NATID_ORGANOGESTOR
		--	,ESTADO
		FROM REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG;
/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_CENTROSCONSUMO ADD
CONSTRAINT MSTR_MAE_CENTROSCONSUMO_PK
 PRIMARY KEY (NATID_CENTROCONSUMO)
NOLOGGING
NOMONITORING
NOPARALLEL
/
ALTER TABLE MSTR_SIGLO.MSTR_MAE_CENTROSCONSUMO ADD
CONSTRAINT MSTR_MAE_CENTROSCONSUMO_R03
 FOREIGN KEY (NATID_ORGANOGESTOR)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ORGANOSGESTORES (NATID_ORGANOGESTOR)
 ENABLE
 VALIDATE
/
CREATE INDEX MSTR_SIGLO.MSTR_MAE_CENTROSCONSUMO_IX01 ON MSTR_SIGLO.MSTR_MAE_CENTROSCONSUMO
(NATID_ORGANOGESTOR)
NOLOGGING 
PARALLEL
/
BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => 'MSTR_SIGLO'
																		,TabName => 'MSTR_MAE_CENTROSCONSUMO'
																		,Estimate_Percent => 0
																		,Method_Opt => 'FOR ALL COLUMNS SIZE 1'
																		,Degree => 4
																		,Cascade => FALSE
																		,No_Invalidate => FALSE);
END;