/* Formatted on 29/10/2013 13:57:52 (QP5 v5.163.1008.3004) */
--DROP TABLE MSTR_MAE_CATALOGO_N3;

CREATE TABLE MSTR_MAE_CATALOGO_N3
NOLOGGING
NOMONITORING
NOPARALLEL
AS
   SELECT ID NATID_CATALOGO_N3,
          DESCRIPCION DESCR_CATALOGO_N3,
          CODIGOCONCATENADO LDESC_CATALOGO_N3,
          NIVEL NIVEL_SIGLO_N3,
          VALORPADRE NATID_CATALOGO_N2
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N2
                               FROM MSTR_MAE_CATALOGO_N2
                              WHERE INSTR (LDESC_CATALOGO_N2, '*') = 0)
   UNION ALL
   SELECT -1 NATID_CATALOGO_N3,
          'n/a' DESCR_CATALOGO_N3,
          'n/a' LDESC_CATALOGO_N3,
          20 NIVEL_SIGLO_N3,
          -1 NATID_CATALOGO_N2
     FROM DUAL
   UNION ALL
   --   SELECT NATID_CATALOGO_N2,
   --          DESCR_CATALOGO_N2,
   --          LDESC_CATALOGO_N2 || '*' LDESC_CATALOGO_N2,
   --          20 NIVEL_SIGLO_N2,
   --          NATID_CATALOGO_N2 NATID_CATALOGO_N2
   --     FROM MSTR_MAE_CATALOGO_N2
   --    WHERE NATID_CATALOGO_N2 > 0 AND
   --   UNION ALL
   -- Replica N1
   SELECT ID NATID_CATALOGO_N3,
          DESCRIPCION DESCR_CATALOGO_N3,
          CODIGOCONCATENADO || '**' LDESC_CATALOGO_N3,
          20 NIVEL_SIGLO_N3,
          ID NATID_CATALOGO_N2
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 5 AND ACTIVO = 'T' AND VALORPADRE IN (SELECT NATID_CATALOGO_N0 FROM MSTR_MAE_CATALOGO_N0)
   UNION ALL
   --Replica N2
   SELECT ID NATID_CATALOGO_N3,
          DESCRIPCION DESCR_CATALOGO_N3,
          CODIGOCONCATENADO || '*' LDESC_CATALOGO_N3,
          20 NIVEL_SIGLO_N3,
          ID NATID_CATALOGO_N2
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N1
                               FROM MSTR_MAE_CATALOGO_N1
                              WHERE INSTR (LDESC_CATALOGO_N1, '*') = 0);

/

ALTER TABLE MSTR_MAE_CATALOGO_N3 ADD (
  CONSTRAINT MSTR_MAE_CATALOGO_N3_PK
  PRIMARY KEY
  (NATID_CATALOGO_N3)
  USING INDEX
    TABLESPACE USERS
    NOLOGGING
);

/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_CATALOGO_N3 ADD
CONSTRAINT MSTR_MAE_CATALOGO_N3_R01
 FOREIGN KEY (NATID_CATALOGO_N2)
 REFERENCES MSTR_SIGLO.MSTR_MAE_CATALOGO_N2 (NATID_CATALOGO_N2)
 ENABLE
 VALIDATE
/

BEGIN
   SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName            => 'MSTR_SIGLO',
                                      TabName            => 'MSTR_MAE_CATALOGO_N3',
                                      Estimate_Percent   => 0,
                                      Method_Opt         => 'FOR ALL COLUMNS SIZE 1',
                                      Degree             => 4,
                                      Cascade            => FALSE,
                                      No_Invalidate      => FALSE);
END;