/* Formatted on 27/01/2014 14:09:11 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_DET_CN03B;
CREATE TABLE MSTR_DET_CN03B
NOLOGGING
NOMONITORING
PARALLEL AS
	--WITH LIMITS AS (SELECT TO_DATE ('01-JAN-2012') INICIO, TO_DATE ('31-DEC-2014') FIN FROM DUAL)
    WITH LIMITS AS (SELECT ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), -24) INICIO, ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), 1) - 1 FIN FROM DUAL)
		SELECT TRUNC (FECHA) NATID_DIA
					,ARTICULO NATID_ARTICULO
					,NVL (CENTROCONSUMO, -1) NATID_CENTROCONSUMO
					,NVL (NATID_ECONOMICA_N4, -1) NATID_ECONOMICA_N4
					,SUM (CANTIDADSALIDA) CN03B_CANTIDAD
					,SUM (IMPORTESALIDA) CN03B_IMPORTE
			FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG
					 LEFT JOIN (	SELECT ARTICULO, NIVELVALOR NATID_ECONOMICA_N4
													FROM (SELECT ID, ARTICULO, NIVELVALOR
																	FROM REP_PRO_SIGLO.CAT_ARTICULOCLASIF@SYG
																 WHERE		 FECHAFINVALIDEZ IS NULL
																			 AND DEFECTO = 'T'
																			 AND NIVELVALOR IN (SELECT ID
																														FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
																													 WHERE CLASIFICACION = 4))
											GROUP BY ARTICULO, NIVELVALOR)
						 USING (ARTICULO)
					 CROSS JOIN LIMITS
		 WHERE FECHA BETWEEN INICIO AND FIN AND CENTROCONSUMO IS NOT NULL
	GROUP BY TRUNC (FECHA)
					,ARTICULO
					,CENTROCONSUMO
					,NATID_ECONOMICA_N4
/

ALTER TABLE MSTR_SIGLO.MSTR_DET_CN03B ADD
CONSTRAINT MSTR_DET_CN03B_PK
 PRIMARY KEY (NATID_DIA, NATID_ARTICULO, NATID_CENTROCONSUMO)
 NOLOGGING
 NOMONITORING
 PARALLEL
/
ALTER TABLE MSTR_SIGLO.MSTR_DET_CN03B ADD
CONSTRAINT MSTR_DET_CN03B_R01
 FOREIGN KEY (NATID_ARTICULO)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ARTICULOS (NATID_ARTICULO)
/

ALTER TABLE MSTR_DET_CN03B ADD (
 CONSTRAINT MSTR_DET_CN03B_R04
 FOREIGN KEY (NATID_CENTROCONSUMO)
 REFERENCES MSTR_MAE_CENTROSCONSUMO (NATID_CENTROCONSUMO));
/

BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => 'MSTR_SIGLO'
																		,TabName => 'MSTR_DET_CN03B'
																		,Estimate_Percent => SYS.DBMS_STATS.AUTO_SAMPLE_SIZE
																		,Method_Opt => 'FOR ALL INDEXED COLUMNS SIZE AUTO '
																		,Degree => NULL
																		,Cascade => TRUE
																		,No_Invalidate => FALSE);
END;