/* Formatted on 29/10/2013 14:25:50 (QP5 v5.163.1008.3004) */
DROP TABLE MSTR_MAE_ARTICULOS;

--/

CREATE TABLE MSTR_MAE_ARTICULOS
NOLOGGING
NOMONITORING
NOPARALLEL
AS
   SELECT CAT_ARTICULO.ID NATID_ARTICULO,
          CAT_ARTICULO.DESCRIPCION DESCR_ARTICULO,
          CAT_ARTICULO.CODCLASIFIC LDESC_ARTICULO,
          --CODIGO CODIGO_ARTICULO,
          --NEMOTECNICO NEMOTECNICO_ARTICULO,
          CAT_ARTICULO.ORGANOGESTOR NATID_ORGANOGESTOR,
          CAT_ARTICULO.NIVELVALORUNIVERSAL NATID_CATALOGO_NB
     FROM    REP_PRO_SIGLO.CAT_ARTICULO@SYG
          JOIN
             REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
          ON (CAT_NIVELVALOR.ID = CAT_ARTICULO.NIVELVALORUNIVERSAL)
    WHERE /*ESTADO <> 'BORRADO' AND */ ACTIVO = 'T'
--WHERE ESTADO <> 'BORRADO'
/

ALTER TABLE MSTR_MAE_ARTICULOS ADD (
  CONSTRAINT MSTR_MAE_ARTICULOS_PK
  PRIMARY KEY
  (NATID_ARTICULO)
  USING INDEX
    TABLESPACE USERS
    NOLOGGING
);

/

CREATE INDEX MSTR_SIGLO.MSTR_MAE_ARTICULOS_IX01
   ON MSTR_SIGLO.MSTR_MAE_ARTICULOS (NATID_CATALOGO_NB)
   TABLESPACE USERS
   NOLOGGING
   NOPARALLEL;

/

CREATE INDEX MSTR_SIGLO.MSTR_MAE_ARTICULOS_IX02
   ON MSTR_SIGLO.MSTR_MAE_ARTICULOS (NATID_ORGANOGESTOR)
   TABLESPACE USERS
   NOLOGGING
   NOPARALLEL;

/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_ARTICULOS ADD
CONSTRAINT MSTR_MAE_ARTICULOS_R01
 FOREIGN KEY (NATID_CATALOGO_NB)
 REFERENCES MSTR_SIGLO.MSTR_MAE_CATALOGO_NB (NATID_CATALOGO_NB)
 ENABLE
 VALIDATE
/

BEGIN
   SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName            => 'MSTR_SIGLO',
                                      TabName            => 'MSTR_MAE_ARTICULOS',
                                      Estimate_Percent   => 0,
                                      Method_Opt         => 'FOR ALL COLUMNS SIZE 1',
                                      Degree             => 4,
                                      Cascade            => FALSE,
                                      No_Invalidate      => FALSE);
END;
/