/* Formatted on 29/10/2013 14:11:12 (QP5 v5.163.1008.3004) */
--DROP TABLE MSTR_MAE_CATALOGO_NA;

CREATE TABLE MSTR_MAE_CATALOGO_NA
NOLOGGING
NOMONITORING
NOPARALLEL
AS
   SELECT ID NATID_CATALOGO_NA,
          DESCRIPCION DESCR_CATALOGO_NA,
          CODIGOCONCATENADO LDESC_CATALOGO_NA,
          NIVEL NIVEL_SIGLO_NA,
          VALORPADRE NATID_CATALOGO_N9
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          --AND VALORPADRE IN (SELECT NATID_CATALOGO_N9 FROM MSTR_MAE_CATALOGO_N9)
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N9
                               FROM MSTR_MAE_CATALOGO_N9
                              WHERE INSTR (LDESC_CATALOGO_N9, '*') = 0)
   UNION ALL
   SELECT -1 NATID_CATALOGO_NA,
          'n/a' DESCR_CATALOGO_NA,
          'n/a' LDESC_CATALOGO_NA,
          5060 NIVEL_SIGLO_NA,
          -1 NATID_CATALOGO_NA
     FROM DUAL
   UNION ALL
   -- Replica N1
   SELECT ID NATID_CATALOGO_NA,
          DESCRIPCION DESCR_CATALOGO_NA,
          CODIGOCONCATENADO || '*********' LDESC_CATALOGO_NA,
          5060 NIVEL_SIGLO_NA,
          ID NATID_CATALOGO_N9
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 5 AND ACTIVO = 'T' AND VALORPADRE IN (SELECT NATID_CATALOGO_N0 FROM MSTR_MAE_CATALOGO_N0)
   UNION ALL
   --Replica N2
   SELECT ID NATID_CATALOGO_NA,
          DESCRIPCION DESCR_CATALOGO_NA,
          CODIGOCONCATENADO || '********' LDESC_CATALOGO_NA,
          5060 NIVEL_SIGLO_NA,
          ID NATID_CATALOGO_N9
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N1
                               FROM MSTR_MAE_CATALOGO_N1
                              WHERE INSTR (LDESC_CATALOGO_N1, '*') = 0)
   UNION ALL
   -- Replica N3
   SELECT ID NATID_CATALOGO_NA,
          DESCRIPCION DESCR_CATALOGO_NA,
          CODIGOCONCATENADO || '*******' LDESC_CATALOGO_NA,
          5060 NIVEL_SIGLO_NA,
          ID NATID_CATALOGO_N9
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N2
                               FROM MSTR_MAE_CATALOGO_N2
                              WHERE INSTR (LDESC_CATALOGO_N2, '*') = 0)
   UNION ALL
   -- Replica N4
   SELECT ID NATID_CATALOGO_NA,
          DESCRIPCION DESCR_CATALOGO_NA,
          CODIGOCONCATENADO || '******' LDESC_CATALOGO_NA,
          5060 NIVEL_SIGLO_NA,
          ID NATID_CATALOGO_N9
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N3
                               FROM MSTR_MAE_CATALOGO_N3
                              WHERE INSTR (LDESC_CATALOGO_N3, '*') = 0)
   UNION ALL
   -- Replica N5
   SELECT ID NATID_CATALOGO_NA,
          DESCRIPCION DESCR_CATALOGO_NA,
          CODIGOCONCATENADO || '*****' LDESC_CATALOGO_NA,
          5060 NIVEL_SIGLO_NA,
          ID NATID_CATALOGO_N9
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N4
                               FROM MSTR_MAE_CATALOGO_N4
                              WHERE INSTR (LDESC_CATALOGO_N4, '*') = 0)
   UNION ALL
   -- Replica N6
   SELECT ID NATID_CATALOGO_NA,
          DESCRIPCION DESCR_CATALOGO_NA,
          CODIGOCONCATENADO || '****' LDESC_CATALOGO_NA,
          5060 NIVEL_SIGLO_NA,
          ID NATID_CATALOGO_N9
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N5
                               FROM MSTR_MAE_CATALOGO_N5
                              WHERE INSTR (LDESC_CATALOGO_N5, '*') = 0)
   UNION ALL
   -- Replica N7
   SELECT ID NATID_CATALOGO_NA,
          DESCRIPCION DESCR_CATALOGO_NA,
          CODIGOCONCATENADO || '***' LDESC_CATALOGO_NA,
          5060 NIVEL_SIGLO_NA,
          ID NATID_CATALOGO_N9
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N6
                               FROM MSTR_MAE_CATALOGO_N6
                              WHERE INSTR (LDESC_CATALOGO_N6, '*') = 0)
   UNION ALL
   -- Replica N8
   SELECT ID NATID_CATALOGO_NA,
          DESCRIPCION DESCR_CATALOGO_NA,
          CODIGOCONCATENADO || '**' LDESC_CATALOGO_NA,
          5060 NIVEL_SIGLO_NA,
          ID NATID_CATALOGO_N9
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N7
                               FROM MSTR_MAE_CATALOGO_N7
                              WHERE INSTR (LDESC_CATALOGO_N7, '*') = 0)
   UNION ALL
   -- Replica N9
   SELECT ID NATID_CATALOGO_NA,
          DESCRIPCION DESCR_CATALOGO_NA,
          CODIGOCONCATENADO || '*' LDESC_CATALOGO_NA,
          5060 NIVEL_SIGLO_NA,
          ID NATID_CATALOGO_N9
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N8
                               FROM MSTR_MAE_CATALOGO_N8
                              WHERE INSTR (LDESC_CATALOGO_N8, '*') = 0);

/

ALTER TABLE MSTR_MAE_CATALOGO_NA ADD (
  CONSTRAINT MSTR_MAE_CATALOGO_NA_PK
  PRIMARY KEY
  (NATID_CATALOGO_NA)
  USING INDEX
    TABLESPACE USERS
    NOLOGGING
);

/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_CATALOGO_NA ADD
CONSTRAINT MSTR_MAE_CATALOGO_NA_R01
 FOREIGN KEY (NATID_CATALOGO_N9)
 REFERENCES MSTR_SIGLO.MSTR_MAE_CATALOGO_N9 (NATID_CATALOGO_N9)
 ENABLE
 VALIDATE
/

BEGIN
   SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName            => 'MSTR_SIGLO',
                                      TabName            => 'MSTR_MAE_CATALOGO_NA',
                                      Estimate_Percent   => 0,
                                      Method_Opt         => 'FOR ALL COLUMNS SIZE 1',
                                      Degree             => 4,
                                      Cascade            => FALSE,
                                      No_Invalidate      => FALSE);
END;