/* Formatted on 29/10/2013 14:01:47 (QP5 v5.163.1008.3004) */
--DROP TABLE MSTR_MAE_CATALOGO_N5;

CREATE TABLE MSTR_MAE_CATALOGO_N5
NOLOGGING
NOMONITORING
NOPARALLEL
AS
   SELECT ID NATID_CATALOGO_N5,
          DESCRIPCION DESCR_CATALOGO_N5,
          CODIGOCONCATENADO LDESC_CATALOGO_N5,
          NIVEL NIVEL_SIGLO_N5,
          VALORPADRE NATID_CATALOGO_N4
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N4
                               FROM MSTR_MAE_CATALOGO_N4
                              WHERE INSTR (LDESC_CATALOGO_N4, '*') = 0)
   UNION ALL
   SELECT -1 NATID_CATALOGO_N5,
          'n/a' DESCR_CATALOGO_N5,
          'n/a' LDESC_CATALOGO_N5,
          31 NIVEL_SIGLO_N5,
          -1 NATID_CATALOGO_N4
     FROM DUAL
   UNION ALL
   -- Replica N1
   SELECT ID NATID_CATALOGO_N5,
          DESCRIPCION DESCR_CATALOGO_N5,
          CODIGOCONCATENADO || '****' LDESC_CATALOGO_N5,
          31 NIVEL_SIGLO_N5,
          ID NATID_CATALOGO_N4
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 5 AND ACTIVO = 'T' AND VALORPADRE IN (SELECT NATID_CATALOGO_N0 FROM MSTR_MAE_CATALOGO_N0)
   UNION ALL
   --Replica N2
   SELECT ID NATID_CATALOGO_N5,
          DESCRIPCION DESCR_CATALOGO_N5,
          CODIGOCONCATENADO || '***' LDESC_CATALOGO_N5,
          31 NIVEL_SIGLO_N5,
          ID NATID_CATALOGO_N4
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N1
                               FROM MSTR_MAE_CATALOGO_N1
                              WHERE INSTR (LDESC_CATALOGO_N1, '*') = 0)
   UNION ALL
   -- Replica N3
   SELECT ID NATID_CATALOGO_N5,
          DESCRIPCION DESCR_CATALOGO_N5,
          CODIGOCONCATENADO || '**' LDESC_CATALOGO_N5,
          31 NIVEL_SIGLO_N5,
          ID NATID_CATALOGO_N4
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N2
                               FROM MSTR_MAE_CATALOGO_N2
                              WHERE INSTR (LDESC_CATALOGO_N2, '*') = 0)
   UNION ALL
   -- Replica N4
   SELECT ID NATID_CATALOGO_N5,
          DESCRIPCION DESCR_CATALOGO_N5,
          CODIGOCONCATENADO || '*' LDESC_CATALOGO_N5,
          31 NIVEL_SIGLO_N5,
          ID NATID_CATALOGO_N4
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE     CLASIFICACION = 5
          AND ACTIVO = 'T'
          AND VALORPADRE IN (SELECT NATID_CATALOGO_N3
                               FROM MSTR_MAE_CATALOGO_N3
                              WHERE INSTR (LDESC_CATALOGO_N3, '*') = 0);

/

ALTER TABLE MSTR_MAE_CATALOGO_N5 ADD (
  CONSTRAINT MSTR_MAE_CATALOGO_N5_PK
  PRIMARY KEY
  (NATID_CATALOGO_N5)
  USING INDEX
    TABLESPACE USERS
    NOLOGGING
);

/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_CATALOGO_N5 ADD
CONSTRAINT MSTR_MAE_CATALOGO_N5_R01
 FOREIGN KEY (NATID_CATALOGO_N4)
 REFERENCES MSTR_SIGLO.MSTR_MAE_CATALOGO_N4 (NATID_CATALOGO_N4)
 ENABLE
 VALIDATE
/

BEGIN
   SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName            => 'MSTR_SIGLO',
                                      TabName            => 'MSTR_MAE_CATALOGO_N5',
                                      Estimate_Percent   => 0,
                                      Method_Opt         => 'FOR ALL COLUMNS SIZE 1',
                                      Degree             => 4,
                                      Cascade            => FALSE,
                                      No_Invalidate      => FALSE);
END;