DROP TABLE MSTR_HLP_PORCENTAJES_CC_SV_UG;

CREATE TABLE MSTR_HLP_PORCENTAJES_CC_SV_UG
NOLOGGING
NOMONITORING
NOPARALLEL AS

--SELECT COUNT(DISTINCT NATID_CENTROCONSUMO), SUM(PORCENTAJE) FROM (
SELECT CC.ORGANICA NATID_ORGANOGESTOR
			,CC.ID NATID_CENTROCONSUMO
			,CC.NOMBRE DESCR_CENTROCONSUMO
			,CC.CODIGO LDESC_CENTROCONSUMO
			,CC.ESTADO ESTADO_CENTROCONSUMO
			,NVL (TIPO, 'NA') TIPO
			,DECODE (TIPO,	'SV', ER.ID,  'UG', ER.ID * -1,  NULL, -1) NATID_SERVICIO
			,DECODE (TIPO,	'SV', SV.DESCRIPCION,  'UG', 'Sin Servicio - ' || UG.DESCRIPCION,  NULL, 'Sin Servicio') DESCR_SERVICIO
			,DECODE (TIPO,	'SV', SV.CODIGO, 'UG', 'N/A', NULL, 'N/A') LDESC_SERVICIO
			,DECODE (TIPO,	'SV', SV.ESTADO, 'UG', 'N/A',  NULL, 'N/A') ESTADO_SERVICIO
			,DECODE (TIPO,	'UG', ER.ID,  'SV', NVL(UGCSV.UNIDADGESTIONCLINICA, -1),  NULL, -1) NATID_UNIDAD_GESTION_CLINICA
			,DECODE (TIPO,	'UG', UG.DESCRIPCION,  'SV', NVL(UG2.DESCRIPCION, 'N/A'),  NULL, 'Sin UGC') DESCR_UNIDAD_GESTION_CLINICA
			,DECODE (TIPO,	'UG', UG.CODIGO,  'SV', NVL(UG2.CODIGO,'N/A'),  NULL, 'N/A') LDESC_UNIDAD_GESTION_CLINICA
			,DECODE (TIPO,	'UG', UG.ESTADO, 'SV', NVL(UG2.ESTADO,'N/A'),  NULL, 'N/A') ESTADO_UNIDAD_GESTION_CLINICA
			,NVL ( (PORCENTAJE / 100), 1) PORCENTAJE
	FROM REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG CC
			 LEFT JOIN (SELECT SERVICIO ID
												,PORCENTAJE
												,CENTROCONSUMO
												,'SV' TIPO
										FROM REP_PRO_SIGLO.ORG_SERVICIOCC@SYG SCC
									 WHERE ESTADO = 'CONFIRMADO'
									UNION ALL
									SELECT UNIDADGESTIONCLINICA ID
												,PORCENTAJE
												,CENTROCONSUMO
												,'UG' TIPO
										FROM REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICACC@SYG UCC
									 WHERE ESTADO = 'CONFIRMADO') ER
				 ON (ER.CENTROCONSUMO = CC.ID)
			 LEFT JOIN REP_PRO_SIGLO.ORG_SERVICIO@SYG SV
				 ON (ER.ID = SV.ID)
			 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICA@SYG UG
				 ON (ER.ID = UG.ID)
			 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICASRV@SYG UGCSV
				 ON (UGCSV.SERVICIO = SV.ID AND UGCSV.ESTADO = 'CONFIRMADO')
			 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICA@SYG UG2
				 ON (UGCSV.UNIDADGESTIONCLINICA = UG2.ID)
 WHERE CC.ESTADO <> 'PROPINICIAL'
			 --AND CC.ID = 13153
             /*IN
             (
SELECT ID
    FROM REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG CC
 WHERE id IN (SELECT centroconsumo FROM REP_PRO_SIGLO.ORG_SERVICIOCC@SYG WHERE ESTADO = 'CONFIRMADO') AND id IN (SELECT centroconsumo FROM REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICACC@SYG WHERE ESTADO = 'CONFIRMADO')
 AND CC.ESTADO = 'CONFIRMADO'
  )*/
              -- Caso especial 14513
             
             /*IN
             (
SELECT ID
    FROM REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG CC
 WHERE id  IN (SELECT centroconsumo FROM REP_PRO_SIGLO.ORG_SERVICIOCC@SYG WHERE ESTADO = 'CONFIRMADO') AND id NOT IN (SELECT centroconsumo FROM REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICACC@SYG WHERE ESTADO = 'CONFIRMADO')
 AND CC.ESTADO = 'CONFIRMADO'
  )*/

        /*     (
SELECT ID
    FROM REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG CC
 WHERE id NOT IN (SELECT centroconsumo FROM REP_PRO_SIGLO.ORG_SERVICIOCC@SYG WHERE ESTADO = 'CONFIRMADO') AND id IN (SELECT centroconsumo FROM REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICACC@SYG WHERE ESTADO = 'CONFIRMADO')
 AND CC.ESTADO = 'CONFIRMADO'
 )*/
             /* (SELECT ID
											 FROM REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG CC
											WHERE 		id NOT IN (SELECT centroconsumo
																						 FROM REP_PRO_SIGLO.ORG_SERVICIOCC@SYG
																						WHERE ESTADO = 'CONFIRMADO')
														AND id NOT IN (SELECT centroconsumo
																						 FROM REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICACC@SYG
																						WHERE ESTADO = 'CONFIRMADO')
														AND CC.ESTADO = 'CONFIRMADO')*/

-- = 15621
-- 11713 multiple UG
-- 13141 multiple SV + multiple UG
-- 15621 multiple SV + 1 UG
-- 14740 SV
--15673 UG
--13153 SV + UG
--)
--WHERE ESTADO_SERVICIO <> 'BORRADO' --AND ESTADO_UNIDAD_GESTION_CLINICA <> 'BORRADO'
/
--ALTER TABLE MSTR_SIGLO.MSTR_DET_REPARTO_CC_SV_UGC ADD
--CONSTRAINT MSTR_DET_REPARTO_CC_SV_UGC_PK
-- PRIMARY KEY (NATID_CENTROCONSUMO, NATID_SERVICIO, NATID_UNIDAD_GESTION_CLINICA)
-- ENABLE
-- VALIDATE
--/
ALTER TABLE MSTR_SIGLO.MSTR_HLP_PORCENTAJES_CC_SV_UG ADD
CONSTRAINT MSTR_DET_REPARTO_CC_SV_UGC_R03
 FOREIGN KEY (NATID_ORGANOGESTOR)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ORGANOSGESTORES (NATID_ORGANOGESTOR)
 ENABLE
 VALIDATE
/
SELECT COUNT (DISTINCT NATID_CENTROCONSUMO) FROM MSTR_HLP_PORCENTAJES_CC_SV_UG;

BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => 'MSTR_SIGLO'
																		,TabName => 'MSTR_HLP_PORCENTAJES_CC_SV_UG'
																		,Estimate_Percent => 0
																		,Method_Opt => 'FOR ALL COLUMNS SIZE 1'
																		,Degree => 4
																		,Cascade => FALSE
																		,No_Invalidate => FALSE);
END;