/* Formatted on 22/01/2014 13:25:42 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_DET_REPARTO_CC_SV_UGC;
CREATE TABLE MSTR_DET_REPARTO_CC_SV_UGC
NOLOGGING
NOMONITORING
NOPARALLEL AS
	--SELECT COUNT(DISTINCT NATID_CENTROCONSUMO) FROM (
	SELECT CC.ORGANICA NATID_ORGANOGESTOR
				,CC.ID NATID_CENTROCONSUMO
				,CC.NOMBRE DESCR_CENTROCONSUMO
				,CC.CODIGO LDESC_CENTROCONSUMO
				,CC.ESTADO ESTADO_CENTROCONSUMO
				--,NVL (SV.ID, NVL (UGC2.ID * -1, -1)) NATID_SERVICIO --,NVL (SV.ID, -1) NATID_SERVICIO
				--,NVL (SV.DESCRIPCION, 'Sin Servicio - ' || UGC2.DESCRIPCION) DESCR_SERVICIO --,NVL (SV.DESCRIPCION, 'Sin Servicio') DESCR_SERVICIO
				,CASE
					 WHEN SV.DESCRIPCION IS NOT NULL THEN SV.DESCRIPCION
					 --WHEN UGC2.DESCRIPCION IS NOT NULL THEN 'Sin Servicio - ' || UGC2.DESCRIPCION
					 --WHEN SV.DESCRIPCION IS NULL AND UGC2.DESCRIPCION IS NULL THEN 'Sin Servicio'
				 END
					 DESCR_SERVICIO
				--,SV.CODIGO LDESC_SERVICIO --,NVL (SV.CODIGO, 'N/A') LDESC_SERVICIO
				,CASE WHEN SV.ID IS NOT NULL THEN SV.CODIGO WHEN SV.ID IS NULL THEN 'N/A' END LDESC_SERVICIO
				--,SV.ESTADO ESTADO_SERVICIO --,NVL (SV.ESTADO, 'N/A') ESTADO_SERVICIO
				,CASE WHEN SV.ID IS NOT NULL THEN SV.ESTADO WHEN SV.ID IS NULL THEN 'N/A' END ESTADO_SERVICIO
				--,SCC.PORCENTAJE PORCENTAJE_SERVICIO --,NVL (SCC.PORCENTAJE, 0) PORCENTAJE_SERVICIO
				,CASE WHEN SV.ID IS NOT NULL THEN (SCC.PORCENTAJE / 100) WHEN SV.ID IS NULL THEN 1 END PORCENTAJE_SERVICIO
				--,SCC.ESTADO ESTADO_PORCENTAJE_SERVICIO --,NVL (SCC.ESTADO, 'N/A') ESTADO_PORCENTAJE_SERVICIO
				,CASE WHEN SV.ID IS NOT NULL THEN SCC.ESTADO WHEN SV.ID IS NULL THEN 'N/A' END ESTADO_PORCENTAJE_SERVICIO
				,NVL (UGCSV.UNIDADGESTIONCLINICA, NVL (UCC.ID, -1)) NATID_UNIDAD_GESTION_CLINICA --,NVL (UGCSV.UNIDADGESTIONCLINICA, -1) NATID_UNIDAD_GESTION_CLINICA
				--,NVL (UGC1.DESCRIPCION, NVL (UGC2.DESCRIPCION, 'Sin UGC')) DESCR_UNIDAD_GESTION_CLINICA --,NVL (UGC.DESCRIPCION, 'Sin UGC') DESCR_UNIDAD_GESTION_CLINICA
				--,NVL (UGC1.ESTADO, NVL (UGC2.ESTADO, 'N/A')) ESTADO_UNIDAD_GESTION_CLINICA --,NVL (UGC.ESTADO, 'N/A') ESTADO_UNIDAD_GESTION_CLINICA
				--,UCC.PORCENTAJE PORCENTAJE_UGC --,NVL (SCC.PORCENTAJE, 0) PORCENTAJE_UGC
				,CASE
					 WHEN UCC.PORCENTAJE IS NOT NULL THEN (UCC.PORCENTAJE / 100)
					 WHEN UCC.PORCENTAJE IS NULL AND UGCSV.UNIDADGESTIONCLINICA IS NOT NULL THEN (SCC.PORCENTAJE / 100)
					 WHEN UCC.PORCENTAJE IS NULL AND UGCSV.UNIDADGESTIONCLINICA IS NULL THEN 1
				 END
					 PORCENTAJE_UGC
				,NVL (UCC.ESTADO, 'N/A') ESTADO_PORCENTAJE_UGC
		FROM REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG CC
				 LEFT JOIN REP_PRO_SIGLO.ORG_SERVICIOCC@SYG SCC
					 ON (SCC.CENTROCONSUMO = CC.ID AND SCC.ESTADO = 'CONFIRMADO')
				 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICACC@SYG UCC
					 ON (UCC.CENTROCONSUMO = CC.ID AND UCC.ESTADO = 'CONFIRMADO')
				 LEFT JOIN REP_PRO_SIGLO.ORG_SERVICIO@SYG SV
					 ON (SCC.SERVICIO = SV.ID)
				 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICASRV@SYG UGCSV
					 ON (UGCSV.SERVICIO = SV.ID AND UGCSV.ESTADO = 'CONFIRMADO')
--				 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICA@SYG UGC1
--					 ON (UGCSV.UNIDADGESTIONCLINICA = UGC1.ID AND UCC.UNIDADGESTIONCLINICA IS NULL)
--				 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICA@SYG UGC2
--					 ON (UCC.UNIDADGESTIONCLINICA = UGC2.ID)
LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICA@SYG UGC1
ON (NVL(UCC.UNIDADGESTIONCLINICA, UGCSV.UNIDADGESTIONCLINICA) = UGC1.ID)
	 WHERE CC.ESTADO <> 'PROPINICIAL'
--)