/* Formatted on 23/01/2014 18:43:07 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_HLP_PORCENTAJES_CC_SV_UG;

CREATE TABLE MSTR_HLP_PORCENTAJES_CC_SV_UG
NOLOGGING
NOMONITORING
NOPARALLEL AS
	SELECT NATID_ORGANOGESTOR
				,NATID_CENTROCONSUMO
				,DESCR_CENTROCONSUMO
				,LDESC_CENTROCONSUMO
				,ESTADO_CENTROCONSUMO
				,TIPO
				,NATID_SERVICIO
				,DESCR_SERVICIO
				,LDESC_SERVICIO
				,ESTADO_SERVICIO
				,PORCENTAJE
				,DECODE (TIPO,	'UG', ER_ID,  'SV', NVL (UGCSV.UNIDADGESTIONCLINICA, -1),  'NA', -1) NATID_UNIDAD_GESTION_CLINICA
				,DECODE (TIPO,	'UG', UG_DESCRIPCION,  'SV', NVL (UG2.DESCRIPCION, 'N/A'),  'NA', 'Sin UGC') DESCR_UNIDAD_GESTION_CLINICA
				,DECODE (TIPO,	'UG', UG_CODIGO,  'SV', NVL (UG2.CODIGO, 'N/A'),  'NA', 'N/A') LDESC_UNIDAD_GESTION_CLINICA
				,DECODE (TIPO,	'UG', UG_ESTADO,  'SV', NVL (UG2.ESTADO, 'N/A'),  'NA', 'N/A') ESTADO_UNIDAD_GESTION_CLINICA
		FROM (SELECT CC.ORGANICA NATID_ORGANOGESTOR
								,CC.ID NATID_CENTROCONSUMO
								,CC.NOMBRE DESCR_CENTROCONSUMO
								,CC.CODIGO LDESC_CENTROCONSUMO
								,CC.ESTADO ESTADO_CENTROCONSUMO
								,NVL (TIPO, 'NA') TIPO
								,DECODE (TIPO,	'SV', ER.ID,  'UG', ER.ID * -1,  NULL, -1) NATID_SERVICIO
								,DECODE (TIPO,	'SV', SV.DESCRIPCION,  'UG', 'Sin Servicio - ' || UG.DESCRIPCION,  NULL, 'Sin Servicio') DESCR_SERVICIO
								,DECODE (TIPO,	'SV', SV.CODIGO,  'UG', 'N/A',  NULL, 'N/A') LDESC_SERVICIO
								,DECODE (TIPO,	'SV', SV.ESTADO,  'UG', 'N/A',  NULL, 'N/A') ESTADO_SERVICIO
								-- ,DECODE (TIPO, 'UG', ER.ID,  'SV', NVL(UGCSV.UNIDADGESTIONCLINICA, -1),  NULL, -1) NATID_UNIDAD_GESTION_CLINICA
								-- ,DECODE (TIPO, 'UG', UG.DESCRIPCION,  'SV', NVL(UG2.DESCRIPCION, 'N/A'),  NULL, 'Sin UGC') DESCR_UNIDAD_GESTION_CLINICA
								-- ,DECODE (TIPO, 'UG', UG.CODIGO,  'SV', NVL(UG2.CODIGO,'N/A'),  NULL, 'N/A') LDESC_UNIDAD_GESTION_CLINICA
								-- ,DECODE (TIPO, 'UG', UG.ESTADO, 'SV', NVL(UG2.ESTADO,'N/A'),  NULL, 'N/A') ESTADO_UNIDAD_GESTION_CLINICA
								,NVL ( (PORCENTAJE / 100), 1) PORCENTAJE
								,ER.ID ER_ID
								,UG.CODIGO UG_CODIGO
								,UG.DESCRIPCION UG_DESCRIPCION
								,UG.ESTADO UG_ESTADO
						FROM REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG CC
								 LEFT JOIN (SELECT SERVICIO ID
																	,PORCENTAJE
																	,CENTROCONSUMO
																	,'SV' TIPO
															FROM REP_PRO_SIGLO.ORG_SERVICIOCC@SYG SCC
														 WHERE ESTADO = 'CONFIRMADO'
														UNION ALL
														SELECT UNIDADGESTIONCLINICA ID
																	,PORCENTAJE
																	,CENTROCONSUMO
																	,'UG' TIPO
															FROM REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICACC@SYG UCC
														 WHERE ESTADO = 'CONFIRMADO') ER
									 ON (ER.CENTROCONSUMO = CC.ID)
								 LEFT JOIN REP_PRO_SIGLO.ORG_SERVICIO@SYG SV
									 ON (ER.ID = SV.ID)
								 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICA@SYG UG
									 ON (ER.ID = UG.ID)
					 --  LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICASRV@SYG UGCSV
					 --  ON (UGCSV.SERVICIO = SV.ID AND UGCSV.ESTADO = 'CONFIRMADO')
					 --  LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICA@SYG UG2
					 --  ON (UGCSV.UNIDADGESTIONCLINICA = UG2.ID)
					 WHERE CC.ESTADO <> 'PROPINICIAL' /*AND CC.ID IN (15311, 15312)*/
																					 ) T1
				 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICASRV@SYG UGCSV
					 ON (UGCSV.SERVICIO = NATID_SERVICIO AND UGCSV.ESTADO = 'CONFIRMADO')
				 LEFT JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICA@SYG UG2
					 ON (UGCSV.UNIDADGESTIONCLINICA = UG2.ID);
/

ALTER TABLE MSTR_SIGLO.MSTR_HLP_PORCENTAJES_CC_SV_UG ADD
CONSTRAINT MSTR_HLP_PORCENT_CC_SV_UG_PK
 PRIMARY KEY (NATID_CENTROCONSUMO, NATID_SERVICIO, NATID_UNIDAD_GESTION_CLINICA)
 NOLOGGING 
 NOMONITORING
/
SELECT COUNT (DISTINCT NATID_CENTROCONSUMO) FROM MSTR_HLP_PORCENTAJES_CC_SV_UG;
/
ALTER TABLE MSTR_SIGLO.MSTR_HLP_PORCENTAJES_CC_SV_UG ADD
CONSTRAINT MSTR_HLP_PORCENT_CC_SV_UG_R03
 FOREIGN KEY (NATID_ORGANOGESTOR)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ORGANOSGESTORES (NATID_ORGANOGESTOR)
 ENABLE
 VALIDATE
/
CREATE INDEX MSTR_SIGLO.MSTR_HLP_PORCENT_CC_SV_UG_IX01
	ON MSTR_SIGLO.MSTR_HLP_PORCENTAJES_CC_SV_UG (NATID_ORGANOGESTOR)
	NOLOGGING
	NOPARALLEL;
/

--SELECT COUNT (DISTINCT NATID_CENTROCONSUMO) FROM MSTR_HLP_PORCENTAJES_CC_SV_UG;

BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => 'MSTR_SIGLO'
																		,TabName => 'MSTR_HLP_PORCENTAJES_CC_SV_UG'
																		,Estimate_Percent => 0
																		,Method_Opt => 'FOR ALL COLUMNS SIZE 1'
																		,Degree => 4
																		,Cascade => FALSE
																		,No_Invalidate => FALSE);
END;