/* Formatted on 14/10/2013 13:00:42 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE VIEW MSTR_MAE_ECONOMICA_N5
AS
   SELECT ID NATID_ECONOMICA_N5,
          DESCRIPCION DESCR_ECONOMICA_N5,
          CODIGOCONCATENADO LDESC_ECONOMICA_N5,
          VALORPADRE NATID_ECONOMICA_N4
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 4 AND VALORPADRE IN (SELECT NATID_ECONOMICA_N4 FROM MSTR_MAE_ECONOMICA_N4)