/* Formatted on 19/12/2013 11:25:35 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
SELECT -1 NATID_ARTICULO
			,'n/a' DESCR_ARTICULO
			,'n/a' LDESC_ARTICULO
			,-1 NATID_ORGANOGESTOR
			,-1 NATID_CATALOGO_NC
            ,-1 NATID_DEFAULT_ECONOMICA_N4
	FROM DUAL
UNION ALL
SELECT CAT_ARTICULO.ID NATID_ARTICULO
			,CAT_ARTICULO.DESCRIPCION DESCR_ARTICULO
			,CAT_ARTICULO.CODCLASIFIC LDESC_ARTICULO
			, --CODIGO CODIGO_ARTICULO,
				--NEMOTECNICO NEMOTECNICO_ARTICULO,
			 CAT_ARTICULO.ORGANOGESTOR NATID_ORGANOGESTOR
			,CAT_ARTICULO.NIVELVALORUNIVERSAL NATID_CATALOGO_NC
			,NVL(EN4.NATID_ECONOMICA_N4, -1) NATID_DEFAULT_ECONOMICA_N4
	FROM REP_PRO_SIGLO.CAT_ARTICULO
			 JOIN REP_PRO_SIGLO.CAT_NIVELVALOR
				 ON (CAT_NIVELVALOR.ID = CAT_ARTICULO.NIVELVALORUNIVERSAL)
			 LEFT JOIN (	SELECT ARTICULO, NIVELVALOR NATID_ECONOMICA_N4
											FROM (SELECT ID, ARTICULO, NIVELVALOR
															FROM REP_PRO_SIGLO.CAT_ARTICULOCLASIF
														 WHERE		 FECHAFINVALIDEZ IS NULL
																	 AND DEFECTO = 'T'
																	 AND NIVELVALOR IN (SELECT ID
																												FROM REP_PRO_SIGLO.CAT_NIVELVALOR
																											 WHERE CLASIFICACION = 4))
									GROUP BY ARTICULO, NIVELVALOR) EN4
				 ON (EN4.ARTICULO = CAT_ARTICULO.ID)
 WHERE ACTIVO = 'T'