/* Formatted on 20/03/2014 10:50:10 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_UNIDADES_FUNCIONALES2
(
	NATID_AREA_HOSPITALARIA
 ,NATID_UNIDAD_FUNCIONAL2
 ,DESCR_UNIDAD_FUNCIONAL2
 ,NATID_UNIDAD_FUNCIONAL1
) AS
	SELECT '-1' NATID_AREA_HOSPITALARIA
				,'-1' NATID_UNIDAD_FUNCIONAL2
				,'n/a' DESCR_UNIDAD_FUNCIONAL2
				,'-1' NATID_UNIDAD_FUNCIONAL1
		FROM DUAL
	UNION ALL
	SELECT UF_AH_CODIGO NATID_AREA_HOSPITALARIA
				,UF_CODIGO NATID_UNIDAD_FUNCIONAL2
				,UF_NOMBRE DESCR_UNIDAD_FUNCIONAL2
				,UF_UF_CODIGO NATID_UNIDAD_FUNCIONAL1
		FROM REP_PRO_EST.UNIDADES_FUNCIONALES@SEE41DAE
	 WHERE UF_UF_CODIGO IN (SELECT UF_CODIGO
														FROM REP_PRO_EST.UNIDADES_FUNCIONALES@SEE41DAE
													 WHERE UF_UF_CODIGO IS NULL AND UF_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_LOCAL_CODIGOS))
	UNION ALL
	-- Replica Nivel 1 sin hijos
	SELECT UF_AH_CODIGO NATID_AREA_HOSPITALARIA
				,UF_CODIGO NATID_UNIDAD_FUNCIONAL2
				,UF_NOMBRE || '*' DESCR_UNIDAD_FUNCIONAL2
				,UF_CODIGO NATID_UNIDAD_FUNCIONAL1
		FROM REP_PRO_EST.UNIDADES_FUNCIONALES@SEE41DAE
	 WHERE UF_UF_CODIGO IS NULL AND UF_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_LOCAL_CODIGOS) AND UF_FINAL = 'S';