/* Formatted on 06/11/2013 16:28:41 (QP5 v5.163.1008.3004) */
--DROP TABLE MSTR_MAE_ECONOMICA_N2;

CREATE TABLE MSTR_MAE_ECONOMICA_N2
NOLOGGING
NOMONITORING
NOPARALLEL
AS
   SELECT ID NATID_ECONOMICA_N2,
          DESCRIPCION DESCR_ECONOMICA_N2,
          CODIGOCONCATENADO LDESC_ECONOMICA_N2,
          VALORPADRE NATID_ECONOMICA_N1
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 4
          AND VALORPADRE IN (SELECT NATID_ECONOMICA_N1
                               FROM MSTR_MAE_ECONOMICA_N1
                              WHERE INSTR (LDESC_ECONOMICA_N1, '*') = 0)
   UNION ALL
   SELECT -1 NATID_ECONOMICA_N2,
          'n/a' DESCR_ECONOMICA_N2,
          'n/a' LDESC_ECONOMICA_N2,
          -1 NATID_ECONOMICA_N1
     FROM DUAL
   UNION ALL
   -- Replica N0
   SELECT ID NATID_ECONOMICA_N2,
          DESCRIPCION DESCR_ECONOMICA_N2,
          CODIGOCONCATENADO || '**' LDESC_ECONOMICA_N2,
          ID NATID_ECONOMICA_N1
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 4 AND VALORPADRE IS NULL
   UNION ALL
   -- Replica N1
   SELECT ID NATID_ECONOMICA_N2,
          DESCRIPCION DESCR_ECONOMICA_N2,
          CODIGOCONCATENADO || '*' LDESC_ECONOMICA_N2,
          ID NATID_ECONOMICA_N1
     FROM REP_PRO_SIGLO.CAT_NIVELVALOR@SYG
    WHERE CLASIFICACION = 4 AND VALORPADRE IN (SELECT NATID_ECONOMICA_N0 FROM MSTR_MAE_ECONOMICA_N0);

/

ALTER TABLE MSTR_SIGLO.MSTR_MAE_ECONOMICA_N2 ADD
CONSTRAINT MSTR_MAE_ECONOMICA_N2_PK
 PRIMARY KEY (NATID_ECONOMICA_N2)

 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_SIGLO.MSTR_MAE_ECONOMICA_N2 ADD
CONSTRAINT MSTR_MAE_ECONOMICA_N2_R01
 FOREIGN KEY (NATID_ECONOMICA_N1)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ECONOMICA_N1 (NATID_ECONOMICA_N1)
 ENABLE
 VALIDATE
/

CREATE INDEX MSTR_SIGLO.MSTR_MAE_ECONOMICA_N2_IX01
   ON MSTR_SIGLO.MSTR_MAE_ECONOMICA_N2 (NATID_ECONOMICA_N1)
   NOLOGGING
   NOPARALLEL;

/

BEGIN
   SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName            => 'MSTR_SIGLO',
                                      TabName            => 'MSTR_MAE_ECONOMICA_N2',
                                      Estimate_Percent   => 0,
                                      Method_Opt         => 'FOR ALL COLUMNS SIZE 1',
                                      Degree             => 4,
                                      Cascade            => FALSE,
                                      No_Invalidate      => FALSE);
END;
/