/* Formatted on 04/11/2013 19:01:00 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_ORGANOSGESTORES
(
   NATID_ORGANOGESTOR,
   DESCR_ORGANOGESTOR
)
AS
   SELECT ID NATID_ORGANOGESTOR, DESCRIPCION DESCR_ORGANOGESTOR FROM REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG;
