/* Formatted on 10/12/2013 10:49:19 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP VIEW MSTR_MAE_ORGANOSGESTORES;

CREATE OR REPLACE FORCE VIEW MSTR_MAE_ORGANOSGESTORES
(
	NATID_ORGANOGESTOR
 ,DESCR_ORGANOGESTOR
) AS
	SELECT -1 NATID_ORGANOGESTOR, 'n/a' DESCR_ORGANOGESTOR FROM DUAL
	UNION ALL
	SELECT ID NATID_ORGANOGESTOR, DESCRIPCION DESCR_ORGANOGESTOR FROM REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG;