SELECT SUM(GA03B), SUM(IMPORTELINEA), COUNT(1) FROM (

SELECT A.ID, CONTRAALBARAN, GA03B, IMPORTELINEA FROM (

SELECT SUM(NVL(FAL.BASEIMPONIBLE, 0) + NVL(FAL.IMPORTE, 0) ) GA03B,
    FA.ID, FA.CONTRAALBARAN
     FROM REP_PRO_SIGLO.FAC_FACTURA FA
     JOIN REP_PRO_SIGLO.FAC_FACTURALINEA FAL ON (FAL.FACTURA = FA.ID)
    WHERE TO_NUMBER(TO_CHAR(FA.FECHAFACTURA, 'YYYY')) = 2013
      AND FA.ESTADO IN ('CONCILIADA', 'PENDCONCILIAR', 'PENDREGISTRAR', 'REGISTRADA', 'TRAMITADA')
      AND FAL.TIPODESCUENTO IS NULL
      AND FAL.GCDIRECTA IS NULL
      AND FA.TIPO NOT IN (6, 7, 8)
      GROUP BY FA.ID, FA.CONTRAALBARAN
      ) A
JOIN REP_PRO_SIGLO.PED_ENTRALMACLINEA EAL USING (CONTRAALBARAN)
)
;
