/* Formatted on 13/01/2014 13:41:27 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
SELECT 'MSTR_DET_CN03B', TO_CHAR(NATID_DIA,'YYYY') AÑO, SUM (CN03B_CANTIDAD), SUM (CN03B_IMPORTE) FROM MSTR_DET_CN03B
GROUP BY TO_CHAR(NATID_DIA, 'YYYY')
UNION ALL
SELECT 'EXCL_H_INDICADORES_CONSUMO', TO_CHAR(NATID_DIA, 'YYYY') AÑO, SUM (CN03B_CANTIDAD), SUM (CN03B_IMPORTE) FROM EXCL_H_INDICADORES_CONSUMO
GROUP BY TO_CHAR(NATID_DIA, 'YYYY') 
UNION ALL
SELECT 'REP_PRO_SIGLO', TO_CHAR(FECHA, 'YYYY') AÑO,SUM (CANTIDADSALIDA) CN03B_CANTIDAD, SUM (IMPORTESALIDA) CN03B_IMPORTE FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG
WHERE FECHA BETWEEN ('01-JAN-2012') AND ('31-DEC-2014') AND CENTROCONSUMO IS NOT NULL
GROUP BY TO_CHAR(FECHA, 'YYYY') ;
/
SELECT 'MSTR_DET_CN03B', /*TO_CHAR(NATID_DIA,'YYYY') AÑO*/ SUM (CN03B_CANTIDAD), ROUND(SUM (CN03B_IMPORTE),2) FROM MSTR_DET_CN03B
--GROUP BY TO_CHAR(NATID_DIA, 'YYYY')
UNION ALL
SELECT 'EXCL_H_INDICADORES_CONSUMO', /*TO_CHAR(NATID_DIA, 'YYYY') AÑO*/ SUM (CN03B_CANTIDAD), ROUND(SUM (CN03B_IMPORTE),2) FROM EXCL_H_INDICADORES_CONSUMO
--GROUP BY TO_CHAR(NATID_DIA, 'YYYY') 
UNION ALL
SELECT 'REP_PRO_SIGLO', /*TO_CHAR(FECHA, 'YYYY') AÑO*/ SUM (CANTIDADSALIDA) CN03B_CANTIDAD, ROUND(SUM (IMPORTESALIDA),2) CN03B_IMPORTE FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG
WHERE FECHA BETWEEN ('01-JAN-2012') AND ('31-DEC-2014') AND CENTROCONSUMO IS NOT NULL
--GROUP BY TO_CHAR(FECHA, 'YYYY') ;