/* Formatted on 20/01/2014 14:33:38 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */

SELECT * FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN
WHERE CENTROCONSUMO IN
(
SELECT ORG_CENTROCONSUMO.ID
--			--,VERSION
--			,NOMBRE
--			,ORG_CENTROCONSUMO.CODIGO
--			,ORG_CENTROCONSUMO.DESCRIPCION CENTRO_CONSUMO
--			,ORGANICA
--			,ORG_CENTROCONSUMO.ESTADO
	FROM REP_PRO_SIGLO.ORG_CENTROCONSUMO
			 JOIN REP_PRO_SIGLO.ORG_SERVICIOCC
				 ON (ORG_SERVICIOCC.CENTROCONSUMO = ORG_CENTROCONSUMO.ID)
			 JOIN REP_PRO_SIGLO.ORG_SERVICIO
				 ON (ORG_SERVICIOCC.SERVICIO = ORG_SERVICIO.ID)
 WHERE ORG_CENTROCONSUMO.ESTADO <> 'CONFIRMADO' AND ORG_SERVICIOCC.ESTADO = 'CONFIRMADO' AND ORG_SERVICIO.ESTADO = 'CONFIRMADO'
 )
AND FECHA >= '01-ENE-2013'