/* Formatted on 20/01/2014 16:45:54 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
SELECT ID
			,VERSION
			,UNIDADGESTIONCLINICA
			,SERVICIO
			,RESPONSABLE
			,ESTADO
	FROM REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICASRV
 WHERE ESTADO = 'CONFIRMADO';

--select servicio, count(servicio) from (
	SELECT *
		FROM REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICASRV
        JOIN REP_PRO_SIGLO.ORG_SERVICIO ON (ORG_UNIDADGESTIONCLINICASRV.SERVICIO = ORG_SERVICIO.ID)
        JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICA ON (ORG_UNIDADGESTIONCLINICASRV.UNIDADGESTIONCLINICA = ORG_UNIDADGESTIONCLINICA.ID)
	 WHERE SERVICIO IN (	SELECT /*COUNT(ID),*/
															SERVICIO
													FROM REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICASRV
												 WHERE ESTADO = 'CONFIRMADO'
											GROUP BY SERVICIO
												HAVING COUNT (ID) > 1)
				 AND ORG_UNIDADGESTIONCLINICASRV.ESTADO = 'CONFIRMADO'
                 AND ORG_UNIDADGESTIONCLINICA.ESTADO = 'CONFIRMADO'
ORDER BY SERVICIO
--) group by servicio having count(servicio)>1