/* Formatted on 18/12/2013 12:12:41 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
SELECT COUNT (1)
	FROM (	SELECT TRUNC (FECHA), SUM (IMPORTESALIDA)
						FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG
				GROUP BY TRUNC (FECHA));
/

SELECT COUNT (id) FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG;
/

SELECT COUNT (1) FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG;
/

SELECT COUNT (*) FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG;
/

SELECT COUNT (ARTICULO) FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG;
/

--WITH FECHAS AS (SELECT ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), -12) INICIO, ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), 12) - 1 FIN FROM DUAL@SYG)
--SELECT COUNT(N) FROM
--(
	SELECT /*TRUNC(FECHA,'YEAR'),*/
				TO_NUMBER (TO_CHAR (FECHA, 'YYYY')) Y, COUNT (ID) N
		FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG --, FECHAS
	 --WHERE FECHA BETWEEN (ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), -12)) AND (ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), 12) - 1)
	 WHERE FECHA BETWEEN ('01-JAN-2012') AND ('31-DEC-2013')
--WHERE FECHA BETWEEN INICIO AND FIN
GROUP BY TO_NUMBER (TO_CHAR (FECHA, 'YYYY'))
--ORDER BY 1
--)
;SELECT ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), -12) begin_of_last_year, ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), 12) - 1 end_of_this_year FROM DUAL;

WITH FECHAS AS (SELECT ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), -12) INICIO, ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), 12) - 1 FIN FROM DUAL)
SELECT INICIO, FIN
	FROM FECHAS;
/

DROP TABLE TEMP_DET_CONSUMOS;

CREATE TABLE TEMP_DET_CONSUMOS
NOLOGGING
NOMONITORING
PARALLEL AS
		SELECT TRUNC (FECHA) NATID_DIA
					,ARTICULO NATID_ARTICULO
					,SUM (CANTIDADSALIDA) C
					,SUM (IMPORTESALIDA) I
			FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG
		 WHERE FECHA BETWEEN ('01-JAN-2012') AND ('31-DEC-2013')
	GROUP BY TRUNC (FECHA), ARTICULO
/
ALTER TABLE MSTR_SIGLO.TEMP_DET_CONSUMOS ADD
CONSTRAINT TEMP_DET_CONSUMOS_PK
 PRIMARY KEY (NATID_DIA, NATID_ARTICULO)
 ENABLE
 VALIDATE
/

SELECT --COUNT(DISTINCT ARTICULO) -- 56748
			COUNT (DISTINCT CENTROCONSUMO) --9350
																		FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG
/

	SELECT ARTICULO
				,COUNT (ID) FILAS
				,SUM (CANTIDADSALIDA) CANTIDAD
				,SUM (IMPORTESALIDA) IMPORTE
		FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN@SYG
	 WHERE FECHA BETWEEN TO_DATE ('01-JAN-2013') AND TO_DATE ('31-DEC-2013') AND CENTROCONSUMO IS NULL
GROUP BY ARTICULO;