   SELECT COUNT(*),SUM(NVL(FAL.BASEIMPONIBLE, 0) + NVL(FAL.IMPORTE, 0) ) GA03B
     --INTO V_I_FACTURA
     FROM REP_PRO_SIGLO.FAC_FACTURA FA,
          REP_PRO_SIGLO.FAC_FACTURALINEA FAL
    WHERE FAL.FACTURA = FA.ID
      --AND TO_NUMBER(TO_CHAR(FA.FECHAFACTURA, 'YYYY')) = 2013
      AND FA.ESTADO IN ('CONCILIADA', 'PENDCONCILIAR', 'PENDREGISTRAR', 'REGISTRADA', 'TRAMITADA')
      AND FAL.TIPODESCUENTO IS NULL
      AND FA.TIPO NOT IN (6, 7, 8);
      /
--SELECT COUNT(*), SUM(GA03B) FROM
--(
SELECT TRUNC(FA.FECHAFACTURA) NATID_DIA,-- FA.ESTADO,FA.TIPO,
FA.ORGANOGESTOR NATID_ORGANOGESTOR, 
FAL.CLASIFECONOMICADIRECTA NATID_ECONOMICA_N4, 
FAL.GCDIRECTA NATID_ARTICULO,
NVL(BASEIMPONIBLE, 0) + NVL(IMPORTE, 0) GA03B
FROM REP_PRO_SIGLO.FAC_FACTURALINEA FAL
JOIN REP_PRO_SIGLO.FAC_FACTURA FA ON (FAL.FACTURA = FA.ID)
WHERE FA.ESTADO IN ('CONCILIADA', 'PENDCONCILIAR', 'PENDREGISTRAR', 'REGISTRADA', 'TRAMITADA')
AND FAL.TIPODESCUENTO IS NULL
AND FA.TIPO NOT IN (6, 7, 8)
--)
;
