/* Formatted on 10/12/2013 12:59:14 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
--SELECT SUM(GA03B) FROM (
SELECT NATID_DIA, NVL (VALOR_FACTURAS, 0) - NVL (VALOR_FACTURAS_ABONO, 0) GA03B
	FROM	 (	SELECT TRUNC (FA.FECHAFACTURA) NATID_DIA, SUM (NVL (FAL.BASEIMPONIBLE, 0) + NVL (FAL.IMPORTE, 0)) VALOR_FACTURAS
							FROM REP_PRO_SIGLO.FAC_FACTURA@SYG FA JOIN REP_PRO_SIGLO.FAC_FACTURALINEA@SYG FAL ON (FAL.FACTURA = FA.ID)
						 WHERE		 FA.ESTADO IN ('CONCILIADA', 'PENDCONCILIAR', 'PENDREGISTRAR', 'REGISTRADA', 'TRAMITADA')
									 AND FAL.TIPODESCUENTO IS NULL
									 AND FA.TIPO NOT IN (6, 7, 8)
					GROUP BY TRUNC (FA.FECHAFACTURA))
			 FULL OUTER JOIN
				 (	SELECT TRUNC (FA.FECHAFACTURA) NATID_DIA, SUM (NVL (FAL.BASEIMPONIBLE, 0) + NVL (FAL.IMPORTE, 0)) VALOR_FACTURAS_ABONO
							FROM REP_PRO_SIGLO.FAC_FACTURA@SYG FA JOIN REP_PRO_SIGLO.FAC_FACTURALINEA@SYG FAL ON (FAL.FACTURA = FA.ID)
						 WHERE		 FA.ESTADO IN ('CONCILIADA', 'PENDCONCILIAR', 'PENDREGISTRAR', 'REGISTRADA', 'TRAMITADA')
									 AND FAL.TIPODESCUENTO IS NULL
									 AND FA.TIPO IN (6, 7, 8)
					GROUP BY TRUNC (FA.FECHAFACTURA))
			 USING (NATID_DIA)
-- )WHERE NATID_DIA between '01-JAN-2013' AND '31-DEC-2013'
/

CREATE TABLE MSTR_DET_GA03B
NOLOGGING
NOMONITORING
PARALLEL AS
	SELECT NATID_DIA
				,NATID_ORGANOGESTOR
				,NATID_ECONOMICA_N4
				,NATID_ARTICULO
				,NVL (VALOR_FACTURAS, 0) - NVL (VALOR_FACTURAS_ABONO, 0) GA03B
		FROM	 (	SELECT TRUNC (FA.FECHAFACTURA) NATID_DIA
										,NVL (FA.ORGANOGESTOR, -1) NATID_ORGANOGESTOR
										,NVL (FAL.CLASIFECONOMICADIRECTA, -1) NATID_ECONOMICA_N4
										,NVL (FAL.GCDIRECTA, -1) NATID_ARTICULO
										,SUM (NVL (FAL.BASEIMPONIBLE, 0) + NVL (FAL.IMPORTE, 0)) VALOR_FACTURAS
								FROM REP_PRO_SIGLO.FAC_FACTURA@SYG FA JOIN REP_PRO_SIGLO.FAC_FACTURALINEA@SYG FAL ON (FAL.FACTURA = FA.ID)
							 WHERE		 FA.ESTADO IN ('CONCILIADA', 'PENDCONCILIAR', 'PENDREGISTRAR', 'REGISTRADA', 'TRAMITADA')
										 AND FAL.TIPODESCUENTO IS NULL
										 AND FA.TIPO NOT IN (6, 7, 8)
						GROUP BY TRUNC (FA.FECHAFACTURA)
										,FA.ORGANOGESTOR
										,FAL.CLASIFECONOMICADIRECTA
										,FAL.GCDIRECTA)
				 FULL OUTER JOIN
					 (	SELECT TRUNC (FA.FECHAFACTURA) NATID_DIA
										,NVL (FA.ORGANOGESTOR, -1) NATID_ORGANOGESTOR
										,NVL (FAL.CLASIFECONOMICADIRECTA, -1) NATID_ECONOMICA_N4
										,NVL (FAL.GCDIRECTA, -1) NATID_ARTICULO
										,SUM (NVL (FAL.BASEIMPONIBLE, 0) + NVL (FAL.IMPORTE, 0)) VALOR_FACTURAS_ABONO
								FROM REP_PRO_SIGLO.FAC_FACTURA@SYG FA JOIN REP_PRO_SIGLO.FAC_FACTURALINEA@SYG FAL ON (FAL.FACTURA = FA.ID)
							 WHERE		 FA.ESTADO IN ('CONCILIADA', 'PENDCONCILIAR', 'PENDREGISTRAR', 'REGISTRADA', 'TRAMITADA')
										 AND FAL.TIPODESCUENTO IS NULL
										 AND FA.TIPO IN (6, 7, 8)
						GROUP BY TRUNC (FA.FECHAFACTURA)
										,FA.ORGANOGESTOR
										,FAL.CLASIFECONOMICADIRECTA
										,FAL.GCDIRECTA)
				 USING (NATID_DIA, NATID_ORGANOGESTOR, NATID_ECONOMICA_N4, NATID_ARTICULO)
/
ALTER TABLE MSTR_SIGLO.MSTR_DET_GA03B ADD
CONSTRAINT MSTR_DET_GA03B_PK
 PRIMARY KEY (NATID_DIA, NATID_ORGANOGESTOR, NATID_ECONOMICA_N4, NATID_ARTICULO)
 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_SIGLO.MSTR_DET_GA03B ADD
CONSTRAINT MSTR_DET_GA03B_R02
 FOREIGN KEY (NATID_ECONOMICA_N4)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ECONOMICA_N4 (NATID_ECONOMICA_N4)
 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_SIGLO.MSTR_DET_GA03B ADD
CONSTRAINT MSTR_DET_GA03B_R01
 FOREIGN KEY (NATID_ARTICULO)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ARTICULOS (NATID_ARTICULO)
 ENABLE
 VALIDATE
 /
 ALTER TABLE MSTR_SIGLO.MSTR_DET_GA03B ADD 
CONSTRAINT MSTR_DET_GA03B_R03
 FOREIGN KEY (NATID_ORGANOGESTOR)
 REFERENCES MSTR_SIGLO.MSTR_MAE_ORGANOSGESTORES (NATID_ORGANOGESTOR)
 ENABLE
 VALIDATE
