SELECT  CENTROCONSUMO,
--ID, VERSION, ARTICULO, 
--   CENTROCONSUMO, FECHA, UBICACIONVIRTUAL, 
--   CANTIDADSALIDA, IMPORTESALIDA, FECHACADUCIDADEXISTENCIAS, 
--   NHUSA
SUM(IMPORTESALIDA)
FROM REP_PRO_SIGLO.ALM_SALIDAALMACEN
WHERE FECHA BETWEEN ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), -24) AND ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), 1) - 1
 AND CENTROCONSUMO IN (63366,14169,13153)
 GROUP BY CENTROCONSUMO