--ALTER TABLE MSTR_SIGLO.MSTR_DET_GA01B ADD
--CONSTRAINT MSTR_DET_GA01B_PK
-- PRIMARY KEY (NATID_DIA, NATID_ORGANOGESTOR, NATID_ECONOMICA_N4, NATID_ARTICULO)
--   USING INDEX
--    TABLESPACE USERS
--    NOLOGGING
----    NOMONITORING
----    PARALLEL
--/
ALTER TABLE MSTR_SIGLO.MSTR_DET_GA01B DROP
CONSTRAINT MSTR_DET_GA01B_PK
/
DROP INDEX MSTR_DET_GA01B_PK
/
ALTER TABLE MSTR_SIGLO.MSTR_DET_GA01B ADD
CONSTRAINT MSTR_DET_GA01B_PK
 PRIMARY KEY (NATID_DIA, NATID_ORGANOGESTOR, NATID_ECONOMICA_N4, NATID_ARTICULO) DISABLE
 /
 CREATE UNIQUE INDEX MSTR_DET_GA01B_PK ON MSTR_SIGLO.MSTR_DET_GA01B 
  (NATID_DIA, NATID_ORGANOGESTOR, NATID_ECONOMICA_N4, NATID_ARTICULO)
  NOLOGGING  PARALLEL
  STORAGE ( BUFFER_POOL KEEP )
  /
  ALTER TABLE MSTR_SIGLO.MSTR_DET_GA01B ENABLE PRIMARY KEY
  /
  