--SELECT COUNT(*)
--FROM (
SELECT 
DESCR_CATALOGO_N8, LDESC_CATALOGO_N8, NATID_CATALOGO_N7, 
   NATID_CATALOGO_N8, NIVEL_SIGLO_N8
FROM MSTR_MAE_CATALOGO_N8
LEFT JOIN REP_PRO_SIGLO.CAT_ARTICULO@SYG
ON (NATID_CATALOGO_N8 = NIVELVALORUNIVERSAL)
WHERE NIVELVALORUNIVERSAL IS NULL
--)