/* Formatted on 16/06/2014 13:35:03 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
--CREATE TABLE MSTR_DET_ESTANCIAS_HISTORICO
--NOLOGGING PARALLEL NOMONITORING
--AS


WITH CALENDARIO AS
			 (		SELECT (DATE_GENERA_FECHAS_V2.INICIO_DEL_MES_HACE_TRES_MESES + LEVEL - 1) NATID_FECHA
							FROM DUAL
				CONNECT BY ROWNUM <= (DATE_GENERA_FECHAS_V2.FIN_DE_ESTE_MES - DATE_GENERA_FECHAS_V2.INICIO_DEL_MES_HACE_TRES_MESES + 1))
	SELECT NATID_AREA_HOSPITALARIA
				,DIA_DE_ESTANCIA NATID_FECHA
                ,NATID_FECHA_ULTIMO_REFRESCO
				,NATID_CENTRO_CAMA
				,NATID_UNIDAD_FUNCIONAL3_CAMA
				,NATID_UNIDAD_FUNCIONAL3_RESP
				,COUNT (DIA_DE_ESTANCIA) ESTANCIAS
		FROM (SELECT NATID_AREA_HOSPITALARIA
								,NATID_TRASLADO
								,CALENDARIO.NATID_FECHA DIA_DE_ESTANCIA
								--,NATID_CENTRO_INGRESO
								,NATID_CENTRO_CAMA
								,NATID_UNIDAD_FUNCIONAL3_CAMA
								,NATID_UNIDAD_FUNCIONAL3_RESP
								,NATID_FECHA_ULTIMO_REFRESCO
						FROM CALENDARIO, TEMP_TRASLADOS_A102039
					 WHERE FIN_TRASLADO >= CALENDARIO.NATID_FECHA AND INICIO_TRASLADO < CALENDARIO.NATID_FECHA --ORDER BY 1, 2
																																																		)
GROUP BY NATID_AREA_HOSPITALARIA
				,DIA_DE_ESTANCIA
                ,NATID_FECHA_ULTIMO_REFRESCO
				,NATID_CENTRO_CAMA
				,NATID_UNIDAD_FUNCIONAL3_CAMA
				,NATID_UNIDAD_FUNCIONAL3_RESP
ORDER BY DIA_DE_ESTANCIA;
/
ALTER TABLE MSTR_HOSPITALIZACION.MSTR_DET_ESTANCIAS_HISTORICO ADD 
CONSTRAINT MSTR_DET_ESTANCIAS_HISTORICOPK
 PRIMARY KEY (NATID_AREA_HOSPITALARIA, NATID_FECHA, NATID_CENTRO_CAMA, NATID_UNIDAD_FUNCIONAL3_CAMA, NATID_UNIDAD_FUNCIONAL3_RESP)
 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_HOSPITALIZACION.MSTR_DET_ESTANCIAS_HISTORICO ADD 
CONSTRAINT MSTR_DET_ESTANCIAS_HISTORI_R02
 FOREIGN KEY (NATID_CENTRO_CAMA)
 REFERENCES MSTR_HOSPITALIZACION.MSTR_MAE_CENTROS (NATID_CENTRO)
 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_HOSPITALIZACION.MSTR_DET_ESTANCIAS_HISTORICO ADD 
CONSTRAINT MSTR_DET_ESTANCIAS_HISTORI_R03
 FOREIGN KEY (NATID_UNIDAD_FUNCIONAL3_CAMA)
 REFERENCES MSTR_HOSPITALIZACION.MSTR_MAE_UNIDADES_FUNCIONALES3 (NATID_UNIDAD_FUNCIONAL3)
 ENABLE
 VALIDATE
/
ALTER TABLE MSTR_HOSPITALIZACION.MSTR_DET_ESTANCIAS_HISTORICO ADD 
CONSTRAINT MSTR_DET_ESTANCIAS_HISTORI_R04
 FOREIGN KEY (NATID_UNIDAD_FUNCIONAL3_RESP)
 REFERENCES MSTR_HOSPITALIZACION.MSTR_MAE_UNIDADES_FUNCIONALES3 (NATID_UNIDAD_FUNCIONAL3)
 ENABLE
 VALIDATE
/
