--SELECT * FROM REP_HIS_OWN.COM_UBICACION_GESTION_LOCAL@HUE40DAE
--WHERE CODIGO_ESTRUCTURA
SELECT * FROM REP_PRO_EST.UBICACIONES@HUE40DAE
WHERE UBI_CODIGO
IN (SELECT 
DISTINCT NATID_CAMA
FROM MSTR_HOSPITALIZACION.TEMP_TRASLADOS_A102037
WHERE NATID_CONTROL_ENFERMERIA IS NULL)