/* Formatted on 9/9/2014 12:18:22 PM (QP5 v5.163.1008.3004) */
  SELECT COUNT (LOG_ID) FAILED_STEPS
    FROM DBA_SCHEDULER_JOB_LOG
   WHERE     JOB_NAME = 'ETL_LOAD_ESTANCIAS_P001_MT'
         AND OPERATION = 'RUN'
         AND STATUS NOT IN ('SUCCEEDED')
         AND LOG_ID BETWEEN (SELECT MAX (L1.LOG_ID) LAST_RUN_START
                               FROM DBA_SCHEDULER_JOB_LOG L1
                              WHERE OWNER = 'MSTR_HOSPITALIZACION' AND JOB_NAME = 'ETL_LOAD_ESTANCIAS_P001_MT' AND OPERATION = 'CHAIN_START')
                        AND (SELECT MAX (L1.LOG_ID) LAST_RUN_STOP
                               FROM DBA_SCHEDULER_JOB_LOG L1
                              WHERE OWNER = 'MSTR_HOSPITALIZACION' AND JOB_NAME = 'ETL_LOAD_ESTANCIAS_P001_MT' AND OPERATION = 'CHAIN_RUN')
/

SELECT *
  FROM    (SELECT MAX (L1.LOG_ID) LAST_RUN_START
             FROM DBA_SCHEDULER_JOB_LOG L1
            WHERE OWNER = 'MSTR_HOSPITALIZACION' AND JOB_NAME = 'ETL_LOAD_ESTANCIAS_P001_MT' AND OPERATION = 'CHAIN_START')
       CROSS JOIN
          (SELECT MAX (L1.LOG_ID) LAST_RUN_STOP
             FROM DBA_SCHEDULER_JOB_LOG L1
            WHERE OWNER = 'MSTR_HOSPITALIZACION' AND JOB_NAME = 'ETL_LOAD_ESTANCIAS_P001_MT' AND OPERATION = 'CHAIN_RUN')
--ORDER BY 1 DESC