/* Formatted on 11/6/2014 1:41:33 PM (QP5 v5.163.1008.3004) */
  SELECT COUNT (*), TRUNC (NATID_FECHA_INICIO_PARTE, 'MM') F
    FROM TEMP_INTERVENCIONES_A102004 T
   WHERE T.IND_MODALIDAD_ASISTENCIAL = 1 AND (T.NATID_FECHA_FIN_EPISODIO IS NULL OR TRUNC (T.NATID_FECHA_INICIO_EPISODIO) <> TRUNC (T.NATID_FECHA_FIN_EPISODIO))
GROUP BY TRUNC (NATID_FECHA_INICIO_PARTE, 'MM')
ORDER BY 2 DESC;
/
  SELECT COUNT (*), TRUNC (NATID_FECHA_INICIO_PARTE, 'MM') F
    FROM MSTR_DET_INTERVEN_HISTORICO T
   WHERE T.IND_MODALIDAD_ASISTENCIAL = 1 AND (T.NATID_FECHA_FIN_EPISODIO IS NULL OR TRUNC (T.NATID_FECHA_INICIO_EPISODIO) <> TRUNC (T.NATID_FECHA_FIN_EPISODIO))
   AND NATID_AREA_HOSPITALARIA = '02003'
GROUP BY TRUNC (NATID_FECHA_INICIO_PARTE, 'MM')
ORDER BY 2 DESC