/* Formatted on 9/29/2014 2:36:25 PM (QP5 v5.163.1008.3004) */
UPDATE TEMP_TRASLADOS_A102024 T
   SET ETL_ERROR_DESCR = 'Recupera el C.E: de estructura si lo encuentra',
       NATID_CONTROL_ENFERMERIA =
          NVL ( (SELECT NATID_CONTROL_ENFERMERIA
                   FROM MSTR_DET_CAMAS_DEL_DIA C
                  WHERE C.NATID_CAMA = T.NATID_CAMA AND C.NATID_AREA_HOSPITALARIA = T.NATID_AREA_HOSPITALARIA),
               -4)
/* WHERE NATID_CONTROL_ENFERMERIA IN (-2, -3)*/;

/

SELECT * FROM TEMP_TRASLADOS_A102024
--WHERE NATID_CONTROL_ENFERMERIA IN (-1);
/

UPDATE TEMP_TRASLADOS_A102024 T
   SET ETL_ERROR_DESCR = 'Uff', NATID_CONTROL_ENFERMERIA = NVL (FUNC_RECUPERA_CONTR_ENFERM_V3 (T.NATID_CAMA, 'COE41DAE'), -4)
 WHERE NATID_CONTROL_ENFERMERIA IN (-4);

/

DROP TABLE TEMP_TRASLADOS_A302024;

/

CREATE TABLE TEMP_TRASLADOS_A302024
NOLOGGING
NOMONITORING
PARALLEL
AS
   SELECT                                                                                                                                                                                                         /*+DRIVING_SITE(UBICACIONES)*/
         UBI_CODIGO NATID_CAMA, UBI_CAH_CODIGO NATID_CENTRO, CAH_AH_CODIGO NATID_AREA_HOSPITALARIA                                                                                                                                           --,
     --'zzzzzz' /*FUNC_RECUPERA_CONTR_ENFERM_V3 (UBI_CODIGO, 'COE41DAE')*/ NATID_CONTROL_ENFERMERIA
     FROM REP_PRO_EST.UBICACIONES@COE41DAE JOIN REP_PRO_EST.CENTROS_AH@COE41DAE ON (CAH_CODIGO = UBI_CAH_CODIGO)
    WHERE CAH_AH_CODIGO = '02024';

/

ALTER TABLE TEMP_TRASLADOS_A302024 ADD (NATID_CONTROL_ENFERMERIA VARCHAR2(6));

/

ALTER TABLE TEMP_TRASLADOS_A302024
ADD CONSTRAINT TEMP_TRASLADOS_A302024_PK PRIMARY KEY
(NATID_CAMA)
/

  SELECT *
    FROM TEMP_TRASLADOS_A302024
ORDER BY NATID_CONTROL_ENFERMERIA ASC;

/

UPDATE TEMP_TRASLADOS_A302024
   SET NATID_CONTROL_ENFERMERIA = FUNC_RECUPERA_CONTR_ENFERM_V3 (NATID_CAMA, 'COE41DAE');

/

UPDATE TEMP_TRASLADOS_A102024 T
   SET ETL_ERROR_DESCR = 'Uff',
       NATID_CONTROL_ENFERMERIA =
          (SELECT NATID_CONTROL_ENFERMERIA
             FROM TEMP_TRASLADOS_A302024 A
            WHERE T.NATID_CAMA = A.NATID_CAMA AND T.NATID_AREA_HOSPITALARIA = A.NATID_AREA_HOSPITALARIA)
 WHERE NATID_CONTROL_ENFERMERIA IS NULL;

;