/* Formatted on 8/21/2014 2:29:15 PM (QP5 v5.163.1008.3004) */
  SELECT NATID_FECHA,
         NATID_AREA_HOSPITALARIA,
         E_CE,
         E_UF,
         (E_CE - E_UF) DIFF
    FROM    (  SELECT NATID_FECHA, NATID_AREA_HOSPITALARIA, SUM (ESTANCIAS) E_CE
                 FROM MSTR_HOSPITALIZACION.MSTR_DET_ESTANCIAS_HISTORICO_2
             GROUP BY NATID_FECHA, NATID_AREA_HOSPITALARIA
             ORDER BY NATID_FECHA)
         JOIN
            (  SELECT NATID_FECHA, NATID_AREA_HOSPITALARIA, SUM (ESTANCIAS) E_UF
                 FROM MSTR_HOSPITALIZACION.MSTR_DET_ESTANCIAS_HISTORICO
             GROUP BY NATID_FECHA, NATID_AREA_HOSPITALARIA
             ORDER BY NATID_FECHA)
         USING (NATID_FECHA, NATID_AREA_HOSPITALARIA)
   WHERE NATID_FECHA >= ADD_MONTHS (SYSDATE, -1) AND NATID_AREA_HOSPITALARIA = '02037'
ORDER BY 5