/* Formatted on 8/19/2014 1:20:49 PM (QP5 v5.163.1008.3004) */
SELECT T.NATID_CAMA,
       TRUNC (INICIO_TRASLADO) INICIO_TRASLADO,
       TRUNC (FIN_TRASLADO) FIN_TRASLADO,
       NVL (NATID_CONTROL_ENFERMERIA, -1) NATID_CONTROL_ENFERMERIA
  /*
  -- Esto es muy elegante pero inutil, tomo el control enf. de la fecha de fin traslado

         (SELECT MAX (NATID_CONTROL_ENFERMERIA) KEEP (DENSE_RANK LAST ORDER BY NATID_FECHA)
            FROM MSTR_DET_CAMAS_HISTORICO
           WHERE NATID_CAMA = T.NATID_CAMA AND NATID_FECHA BETWEEN T.INICIO_TRASLADO AND T.FIN_TRASLADO)
            NATID_CONTROL_ENFERMERIA
  */
  FROM MSTR_HOSPITALIZACION.TEMP_TRASLADOS_A102003 T LEFT JOIN MSTR_DET_CAMAS_HISTORICO H ON (T.NATID_CAMA = H.NATID_CAMA AND H.NATID_FECHA = TRUNC (FIN_TRASLADO))
--ORDER BY TRUNC (FIN_TRASLADO)
/

SELECT NATID_ADMISION, NUHSA
  FROM MSTR_HOSPITALIZACION.TEMP_TRASLADOS_A102005
       JOIN ADM_ADMISION
          ON (ADMISION_ID = NATID_ADMISION)
       JOIN COM_USUARIO
          ON (USUARIO = ID_USUARIO);

ALTER TABLE MSTR_HOSPITALIZACION.TEMP_TRASLADOS_A102005
READ WRITE;
--SELECT * FROM  ADM_ADMISION;

UPDATE TEMP_TRASLADOS_A102005 T
   SET NATID_NUHSA =
          (SELECT NVL (NUHSA, -1)
             FROM COM_USUARIO U JOIN ADM_ADMISION A ON (A.USUARIO = U.ID_USUARIO)
            WHERE T.NATID_ADMISION = A.ADMISION_ID);

ALTER TABLE MSTR_HOSPITALIZACION.TEMP_TRASLADOS_A102005
READ ONLY;

DECLARE
   v_USUARIO   ADM_ADMISION.USUARIO%TYPE;
   v_NUHSA     COM_USUARIO.NUHSA%TYPE;
BEGIN
   FOR C1 IN (SELECT NATID_ADMISION, NATID_TRASLADO
                FROM MSTR_HOSPITALIZACION.TEMP_TRASLADOS_A102005
               WHERE ROWNUM < 10000)
   LOOP
      SELECT USUARIO
        INTO v_USUARIO
        FROM ADM_ADMISION
       WHERE ADMISION_ID = C1.NATID_ADMISION;

      SELECT NUHSA
        INTO v_NUHSA
        FROM COM_USUARIO
       WHERE ID_USUARIO = v_USUARIO;

      --DBMS_OUTPUT.PUT_LINE (v_NUHSA);
      UPDATE TEMP_TRASLADOS_A102005
         SET NATID_NUHSA = v_NUHSA
       WHERE NATID_TRASLADO = C1.NATID_TRASLADO;
   END LOOP;
END;

CREATE TABLE TEMP_TRASLADOS_A202005
(
   NATID_NUHSA,
   NATID_ADMISION,
   CONSTRAINT TEMP_TRASLADOS_A202005_PK PRIMARY KEY (NATID_ADMISION)
)
NOLOGGING
NOMONITORING
PARALLEL
STORAGE (BUFFER_POOL KEEP)
AS
   SELECT NUHSA NATID_NUHSA, ADMISION_ID NATID_ADMISION
     FROM    COM_USUARIO
          JOIN
             (SELECT ADMISION_ID, USUARIO
                FROM ADM_ADMISION
               WHERE ADMISION_ID IN (SELECT DISTINCT NATID_ADMISION FROM MSTR_HOSPITALIZACION.TEMP_TRASLADOS_A102005))
          ON (USUARIO = ID_USUARIO);


UPDATE TEMP_TRASLADOS_A102005 A1
   SET NATID_NUHSA =
          (SELECT NATID_NUHSA
             FROM TEMP_TRASLADOS_A202005 A2
            WHERE A2.NATID_ADMISION = A1.NATID_ADMISION);