/* Formatted on 09/05/2014 9:56:03 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP SYNONYM ADM_TRASLADO;
CREATE SYNONYM ADM_TRASLADO FOR REP_HIS_OWN.ADM_TRASLADO@SEE41DAE;

	SELECT *
		FROM REP_HIS_OWN.ADM_TRASLADO@SEE41DAE
	 WHERE ADMISION = 2069942
ORDER BY TRASLADO_ID;

SELECT NATID_ADMISION, UBIC_TERMINAL
	FROM (SELECT NATID_ADMISION, UBIC_TERMINAL, RANK () OVER (PARTITION BY ADMISION ORDER BY TRASLADO_ID) R
					FROM TEMP_INGRESOS_A102003 JOIN ADM_TRASLADO ON (NATID_ADMISION = ADMISION)
				 WHERE TRASLADO_PADRE IS NULL
			 )
 WHERE R = 1;