/* Formatted on 26/03/2014 11:41:39 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE TEMP_CAMAS_A1;

CREATE TABLE TEMP_CAMAS_A1
NOLOGGING
NOPARALLEL
NOMONITORING AS
	SELECT CAH_AH_CODIGO NATID_AREA_HOSPITALARIA
				,TRUNC (SYSDATE) NATID_FECHA
				,LAST_REFRESH_DATE NATID_FECHA_ULTIMO_REFRESCO
				,NVL (UBI_CAH_CODIGO, -1) NATID_CENTRO
				,NVL (UNIDAD_FUNCIONAL, -1) NATID_UNIDAD_FUNCIONAL3
				,UBI_CODIGO NATID_CAMA
				,UBI_NOMBRE DESCR_CAMA
				,UBI_DESCRIPCION LDESC_CAMA
				,UBI_TIP_UBICACION NATID_TIPO_CAMA
				,TUBI_DESCRIPCION DESCR_TIPO_CAMA
				,NVL (TIPO_AISLAMIENTO, NULL) NATID_TIPO_AISLAMIENTO
				,NVL (DECODE (NUM_CAMA, NULL, '--', COM_M_TIPO_AISLAMIENTO.NOMBRE), 'N/A') DESCR_TIPO_AISLAMIENTO
				,NVL (EPISODIO_ID, -1) NATID_EPISODIO
		--,NUM_CAMA CAMA_AISLADA
		FROM REP_HIS_OWN.COM_UBICACION_GESTION_LOCAL@SEE41DAE
				 JOIN REP_PRO_EST.UBICACIONES@SEE41DAE
					 ON (CODIGO_ESTRUCTURA = UBI_CODIGO)
				 JOIN REP_PRO_EST.TIPOS_UBICACION@SEE41DAE
					 ON (UBI_TIP_UBICACION = TUBI_CODIGO)
				 JOIN REP_PRO_EST.CENTROS_AH@SEE41DAE
					 ON (UBI_CAH_CODIGO = CAH_CODIGO)
				 JOIN SYS.ALL_MVIEWS@SEE41DAE
					 ON (MVIEW_NAME = 'COM_UBICACION_GESTION_LOCAL')
				 LEFT JOIN REP_HIS_OWN.COM_M_TIPO_AISLAMIENTO@SEE41DAE
					 ON (TIPO_AISLAMIENTO = CODIGO)
				 LEFT JOIN (SELECT UBICACION_ORIGEN NUM_CAMA FROM REP_HIS_OWN.COM_UBICACION_AISLADA@SEE41DAE
										UNION
										SELECT UBICACION_AFECTADA NUM_CAMA FROM REP_HIS_OWN.COM_UBICACION_AISLADA@SEE41DAE)
					 ON (ID = NUM_CAMA)
	 WHERE ACTIVA = 1 AND UBI_ACTIVO = 0
/
ALTER TABLE MSTR_HOSPITALIZACION.TEMP_CAMAS_A1 ADD
CONSTRAINT TEMP_CAMAS_A1_PK
 PRIMARY KEY (NATID_CAMA)
 ENABLE
 VALIDATE
/
CREATE INDEX TEMP_CAMAS_A1_IDX01
	ON TEMP_CAMAS_A1 (NATID_EPISODIO)
	NOLOGGING
	NOPARALLEL;
/

ALTER TABLE TEMP_CAMAS_A1
 ADD (NATID_CONTROL_ENFERMERIA VARCHAR2(5), NATID_NUHSA  VARCHAR2(12), ETL_ERROR_DESCR VARCHAR2(250));
/

UPDATE TEMP_CAMAS_A1
	 SET NATID_TIPO_AISLAMIENTO = -1, ETL_ERROR_DESCR = 'cama aislada en COM_UBICACION_AISLADA sin tipo aislamiento en COM_UBICACION_GESTION_LOCAL'
 WHERE DESCR_TIPO_AISLAMIENTO = 'N/A';
/

UPDATE TEMP_CAMAS_A1
	 SET NATID_CONTROL_ENFERMERIA = NVL (func_recupera_contr_enfermeria (NATID_CAMA), '-1')
/
DECLARE
	v_EPISODIO_ID TEMP_CAMAS_A1.NATID_EPISODIO%TYPE;
	v_REFERENCIA_ID NUMBER;
	v_USUARIO NUMBER;
	v_NATID_NUHSA TEMP_CAMAS_A1.NATID_NUHSA%TYPE;
	v_COUNT PLS_INTEGER;
	CURSOR C1 IS
				SELECT NATID_EPISODIO, NATID_NUHSA
					FROM TEMP_CAMAS_A1
		FOR UPDATE OF NATID_NUHSA;
BEGIN
	FOR R1 IN C1 LOOP
		IF R1.NATID_EPISODIO > 0 THEN
			BEGIN
				SELECT (REFERENCIA_ID)
					INTO v_REFERENCIA_ID
					FROM REP_HIS_OWN.ADM_EPIS_DETALLE@SEE41DAE
				 WHERE EPISODIO_ID = R1.NATID_EPISODIO;
			EXCEPTION
				WHEN NO_DATA_FOUND THEN
					DBMS_OUTPUT.PUT_LINE ('episodio not found: ' || R1.NATID_EPISODIO);
					UPDATE TEMP_CAMAS_A1
						 SET NATID_NUHSA = '-2', ETL_ERROR_DESCR = 'episodio ' || R1.NATID_EPISODIO || ' no encontrado en ADM_EPIS_DETALLE'
					 WHERE NATID_EPISODIO = R1.NATID_EPISODIO;
					v_REFERENCIA_ID := -1;
			END;
			IF v_REFERENCIA_ID > 0 THEN
				BEGIN
					SELECT (USUARIO)
						INTO v_USUARIO
						FROM REP_HIS_OWN.ADM_ADMISION@SEE41DAE
					 WHERE ADMISION_ID = v_REFERENCIA_ID;
				EXCEPTION
					WHEN NO_DATA_FOUND THEN
						DBMS_OUTPUT.PUT_LINE ('referencia not found: ' || v_REFERENCIA_ID);
						UPDATE TEMP_CAMAS_A1
							 SET ETL_ERROR_DESCR = 'referencia ' || v_REFERENCIA_ID || ' no encontrada en ADM_ADMISION'
						 WHERE NATID_EPISODIO = R1.NATID_EPISODIO;
						v_USUARIO := -1;
				END;
				IF v_USUARIO > 0 THEN
					SELECT (NUHSA)
						INTO v_NATID_NUHSA
						FROM REP_HIS_OWN.COM_USUARIO@SEE41DAE
					 WHERE ID_USUARIO = v_USUARIO;
					UPDATE TEMP_CAMAS_A1
						 SET NATID_NUHSA = v_NATID_NUHSA
					 WHERE NATID_EPISODIO = R1.NATID_EPISODIO;
				END IF;
			END IF;
		END IF;
	END LOOP;
	UPDATE TEMP_CAMAS_A1
		 SET NATID_NUHSA = '-1'
	 WHERE NATID_NUHSA IS NULL;
	COMMIT;
END;

BEGIN
	SYS.DBMS_STATS.GATHER_TABLE_STATS (OwnName => USER
																		,TabName => 'TEMP_CAMAS_A1'
																		,Estimate_Percent => NULL --SYS.DBMS_STATS.AUTO_SAMPLE_SIZE
																		,Method_Opt => 'FOR ALL COLUMNS SIZE SKEWONLY '
																		,Degree => DBMS_STATS.DEFAULT_DEGREE
																		,Cascade => DBMS_STATS.AUTO_CASCADE
																		,No_Invalidate => DBMS_STATS.AUTO_INVALIDATE);
END;