/* Formatted on 8/27/2014 12:56:08 PM (QP5 v5.163.1008.3004) */
BEGIN
   DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE (DBMS_RULE_ADM.CREATE_RULE_OBJ, 'MSTR_HOSPITALIZACION');
   DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE (DBMS_RULE_ADM.CREATE_RULE_SET_OBJ, 'MSTR_HOSPITALIZACION');
   DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE (DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ, 'MSTR_HOSPITALIZACION');
END;
/
