/* Formatted on 4/23/2014 13:54:06 (QP5 v5.163.1008.3004) */
  SELECT TRUNC (FCH_INGRESO, 'MONTH') AS FECHA, COUNT (1) AS CONTADOR
    FROM REP_HIS_OWN.ADM_ADMISION@SEE41DAE adm
   WHERE     MODALIDAD_ASIST = 1
         AND EPIS_CONTAB = 1
         AND TRUNC (FCH_INGRESO) >= TRUNC (ADD_MONTHS (SYSDATE, -12), 'MM')
GROUP BY TRUNC (FCH_INGRESO, 'MONTH');