SELECT 
NATID_AREA_HOSPITALARIA, NATID_FECHA, NATID_FECHA_ULTIMO_REFRESCO, 
   NATID_CENTRO, NATID_UNIDAD_FUNCIONAL3, NATID_UNIDAD_FUNCIONAL3_RESP, 
   NATID_ADMISION, NATID_EPISODIO, NATID_NUHSA, 
   IND_MODALIDAD_ASISTENCIAL, IND_MEDICO_QUIRURGICO, IND_PROCEDENTE_DE, 
   IND_URGENTE_PROGRAMADO, NATID_CAMA, NATID_CONTROL_ENFERMERIA, 
   ETL_ERROR_DESCR, CIE9_DIAGNOSTICO_INGRESO, NATID_CENTRO_PRIMER_TRASLADO, 
   NATID_CAMA_PRIMER_TRASLADO
FROM MSTR_HOSPITALIZACION.MSTR_DET_INGRESOS_HISTORICO
WHERE NATID_CENTRO_PRIMER_TRASLADO = -1 AND NATID_CAMA_PRIMER_TRASLADO = -1
AND IND_MODALIDAD_ASISTENCIAL = 'Hospitalización'
AND IND_PROCEDENTE_DE <> 'Nacidos en el Hospital'