/* Formatted on 4/26/2014 14:58:46 (QP5 v5.163.1008.3004) */
SELECT CUBEACTIONID,
       CUBEINSTANCEID,
       CUBEKBSIZE,
       CUBEREPORTGUID,
       CUBEROWSIZE,
       DAY_ID,
       FINISHTIME,
       HOUR_ID,
       JOBID,
       MINUTE_ID,
       PROJECTID,
       RECORDTIME,
       REPORTGUID,
       REPOSITORYID,
       SERVERMACHINE,
       SESSIONID,
       STARTTIME
  FROM IS_CUBE_REP_STATS
/

  SELECT OBJECT_NAME,
         MAX (FINISHTIME) ULTIMO_REFRESH,
         CUBEREPORTGUID || TO_CHAR (MAX (FINISHTIME), 'YYYYMMDDHH24MISS') TAG
    FROM IS_CUBE_REP_STATS JOIN DSSMDOBJINFO ON (CUBEREPORTGUID = OBJECT_ID)
GROUP BY OBJECT_NAME, CUBEREPORTGUID