/* Formatted on 9/26/2014 1:29:31 PM (QP5 v5.163.1008.3004) */
SELECT CODIGO,
       NOMBRE,
       --TIPO_UNIDAD,
       DECODE (TIPO_UNIDAD,  'UF', AH1.AH_CODIGO,  'AH', AH2.AH_CODIGO,  'SAS', 'SAS',  'SC', 'SC',  'UFS', 'UFS') AH_CODIGO,
       DECODE (TIPO_UNIDAD,  'UF', AH1.AH_DESCRIPCION,  'AH', AH2.AH_DESCRIPCION,  'SAS', 'Todas',  'SC', 'Servicios Centrales',  'UFS', '¿UFS?') AH_DESCRIPCION,
       DECODE (TIPO_UNIDAD,  'UF', UF.UF_CODIGO,  'AH', NULL) UF_CODIGO,
       UF_NOMBRE
  FROM REP_PRO_MAC.OPERADORUNIDADFUNCIONAL@MAE41DAE
       JOIN REP_PRO_MAC.MODULO@MAE44DAE
          ON (MODULO = CODIGO)
       LEFT JOIN REP_PRO_EST.UNIDADES_FUNCIONALES@MAE44DAE UF
          ON (UNIDAD = UF_CODIGO)
       LEFT JOIN REP_PRO_EST.AREAS_HOSPITALARIAS@MAE44DAE AH1
          ON (UF_AH_CODIGO = AH1.AH_CODIGO)
       LEFT JOIN REP_PRO_EST.AREAS_HOSPITALARIAS@MAE44DAE AH2
          ON (UNIDAD = AH2.AH_CODIGO)
 WHERE OPERADOR = '7125512'