BEGIN
   FOR C1 IN (SELECT OWNER, TABLE_NAME
                FROM ALL_TABLES
               WHERE OWNER = 'MSTR_QUIROFANO' AND TABLE_NAME LIKE 'TEMP_INTERVENCIONES_A1%')
   LOOP
      EXECUTE IMMEDIATE 'GRANT ALTER ON ' || C1.OWNER || '.' || C1.TABLE_NAME || ' TO MSTR_HOSPITALIZACION';
   END LOOP;
END;