/* Formatted on 8/20/2014 12:24:31 PM (QP5 v5.163.1008.3004) */
SELECT * FROM MSTR_DET_ESTANCIAS_HISTORICO_2;

/
TRUNCATE TABLE MSTR_DET_ESTANCIAS_HISTORICO_2;
/
INSERT INTO MSTR_DET_ESTANCIAS_HISTORICO_2
   WITH CALENDARIO
        AS (    SELECT (DATE_GENERA_FECHAS_V2.INICIO_DEL_MES_HACE_TRES_MESES + LEVEL - 1) NATID_FECHA
                  FROM DUAL
            CONNECT BY ROWNUM <= (DATE_GENERA_FECHAS_V2.FIN_DE_ESTE_MES - DATE_GENERA_FECHAS_V2.INICIO_DEL_MES_HACE_TRES_MESES + 1))
     SELECT NATID_AREA_HOSPITALARIA,
            DIA_DE_ESTANCIA NATID_FECHA,
            NATID_FECHA_ULTIMO_REFRESCO,
            NATID_CENTRO_CAMA,
            NATID_UNIDAD_FUNCIONAL3_CAMA,
            NATID_UNIDAD_FUNCIONAL3_RESP,
            COUNT (DIA_DE_ESTANCIA) ESTANCIAS,
            NATID_CONTROL_ENFERMERIA,
            NULL ETL_ERROR_DESCR
       FROM (SELECT NATID_AREA_HOSPITALARIA,
                    --                    NATID_TRASLADO,
                    CALENDARIO.NATID_FECHA DIA_DE_ESTANCIA,
                    NATID_FECHA_ULTIMO_REFRESCO,
                    NATID_CENTRO_CAMA,
                    NATID_UNIDAD_FUNCIONAL3_CAMA,
                    NATID_UNIDAD_FUNCIONAL3_RESP,
                    NATID_CONTROL_ENFERMERIA
               FROM CALENDARIO, TEMP_TRASLADOS_A102004
              WHERE FIN_TRASLADO >= CALENDARIO.NATID_FECHA AND INICIO_TRASLADO < CALENDARIO.NATID_FECHA)
   GROUP BY NATID_AREA_HOSPITALARIA,
            DIA_DE_ESTANCIA,
            NATID_FECHA_ULTIMO_REFRESCO,
            NATID_CENTRO_CAMA,
            NATID_UNIDAD_FUNCIONAL3_CAMA,
            NATID_UNIDAD_FUNCIONAL3_RESP,
            NATID_CONTROL_ENFERMERIA