/* Formatted on 28/03/2014 10:10:23 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_DET_CAMAS_DEL_DIA;
/

CREATE TABLE MSTR_DET_CAMAS_DEL_DIA
(
	NATID_AREA_HOSPITALARIA
 ,NATID_FECHA
 ,NATID_FECHA_ULTIMO_REFRESCO
 ,NATID_CENTRO
 ,NATID_UNIDAD_FUNCIONAL3
 ,NATID_CAMA
 ,DESCR_CAMA
 ,LDESC_CAMA
 ,NATID_TIPO_CAMA
 ,DESCR_TIPO_CAMA
 ,NATID_TIPO_AISLAMIENTO
 ,DESCR_TIPO_AISLAMIENTO
 ,NATID_EPISODIO
 ,NATID_CONTROL_ENFERMERIA
 ,NATID_NUHSA
 ,ETL_ERROR_DESCR
 ,CONSTRAINT MSTR_DET_CAMAS_DEL_DIA_PK PRIMARY KEY (NATID_CAMA)
)
ORGANIZATION INDEX
NOLOGGING
NOMONITORING
NOPARALLEL
STORAGE (BUFFER_POOL KEEP) AS
	SELECT NATID_AREA_HOSPITALARIA
				,NATID_FECHA
				,NATID_FECHA_ULTIMO_REFRESCO
				,NATID_CENTRO
				,NATID_UNIDAD_FUNCIONAL3
				,NATID_CAMA
				,DESCR_CAMA
				,LDESC_CAMA
				,NATID_TIPO_CAMA
				,DESCR_TIPO_CAMA
				,NATID_TIPO_AISLAMIENTO
				,DESCR_TIPO_AISLAMIENTO
				,NATID_EPISODIO
				,NATID_CONTROL_ENFERMERIA
				,NATID_NUHSA
				,ETL_ERROR_DESCR
		FROM TEMP_CAMAS_A102004
	 WHERE 1 = 0
/
BEGIN
	FOR C1 IN (  SELECT TABLE_NAME
								 FROM USER_TABLES
								WHERE TABLE_NAME LIKE 'TEMP_CAMAS_A1%'
						 ORDER BY 1) LOOP
		EXECUTE IMMEDIATE 'INSERT INTO MSTR_DET_CAMAS_DEL_DIA SELECT * FROM ' || C1.TABLE_NAME;
		EXECUTE IMMEDIATE 'INSERT INTO MSTR_DET_CAMAS_HISTORICO SELECT * FROM ' || C1.TABLE_NAME;
	END LOOP;
END;