/* Formatted on 27/03/2014 10:43:09 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_MAE_ESTADOS_CAMA;
CREATE TABLE MSTR_MAE_ESTADOS_CAMA
(
	NATID_ESTADO
 ,DESCR_ESTADO
 ,CONSTRAINT MSTR_MAE_ESTADOS_CAMA_PK PRIMARY KEY (NATID_ESTADO)
)
ORGANIZATION INDEX
NOLOGGING
NOMONITORING
NOPARALLEL
STORAGE (BUFFER_POOL KEEP) AS
	SELECT CODIGO NATID_ESTADO, NOMBRE DESCR_ESTADO FROM REP_HIS_OWN.COM_M_ESTADO_UBICACION@SEE41DAE;