SELECT 
NATID_AREA_HOSPITALARIA, DESCR_AREA_HOSPITALARIA, DESCR_INSTANCIA, 
   DESCR_REPLICA, ULTIMO_DATO_DISPONIBLE_MIN, ULTIMO_DATO_DISPONIBLE_MAX, 
   LAPSO, ESTADISTICA_MAS_ANTIGUA, ESTADISTICA_MAS_RECIENTE
FROM MSTR_HOSPITALIZACION.MSTR_DET_TIEMPOS_REPLICAS
WHERE DESCR_REPLICA='REP_SIDCA_OWN'