/* Formatted on 5/23/2014 9:59:32 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE VIEW MSTR_BAD_PACIENTES_DUPLICADOS
AS
     SELECT NATID_AREA_HOSPITALARIA,
            NATID_EPISODIO,
            NATID_FECHA,
            NATID_UNIDAD_FUNCIONAL3_RESP,
            COUNT (1) N
       FROM MSTR_DET_CAMAS_HISTORICO
      WHERE NATID_EPISODIO > 0
   GROUP BY NATID_AREA_HOSPITALARIA,
            NATID_EPISODIO,
            NATID_FECHA,
            NATID_UNIDAD_FUNCIONAL3_RESP
     HAVING COUNT (1) > 1
   ORDER BY NATID_FECHA DESC, NATID_AREA_HOSPITALARIA