/* Formatted on 5/21/2014 13:44:48 (QP5 v5.163.1008.3004) */
SELECT NATID_AREA_HOSPITALARIA,
       NATID_FECHA,
       NATID_FECHA_ULTIMO_REFRESCO,
       NATID_CENTRO,
       NATID_UNIDAD_FUNCIONAL3,
       NATID_CAMA,
       DESCR_CAMA,
       LDESC_CAMA,
       NATID_TIPO_CAMA,
       DESCR_TIPO_CAMA,
       NATID_TIPO_AISLAMIENTO,
       DESCR_TIPO_AISLAMIENTO,
       NATID_EPISODIO,
       NATID_UNIDAD_FUNCIONAL3_RESP,
       NATID_CONTROL_ENFERMERIA,
       NATID_NUHSA,
       ETL_ERROR_DESCR
  FROM MSTR_DET_CAMAS_HISTORICO;

-- Estancias por Unidad Funcional3

  SELECT NATID_AREA_HOSPITALARIA,
         NATID_FECHA,
         NATID_UNIDAD_FUNCIONAL3_RESP,
         COUNT (1) ESTANCIAS
    FROM MSTR_DET_CAMAS_HISTORICO
   WHERE NATID_TIPO_CAMA IN (14, 24) AND NATID_EPISODIO > 0
GROUP BY NATID_AREA_HOSPITALARIA, NATID_FECHA, NATID_UNIDAD_FUNCIONAL3_RESP;

-- Camas disponibles por Unidad Funcional3

  SELECT NATID_AREA_HOSPITALARIA,
         NATID_FECHA,
         NATID_UNIDAD_FUNCIONAL3,
         COUNT (1) CAMAS_DISPONIBLES
    FROM MSTR_DET_CAMAS_HISTORICO
   WHERE NATID_TIPO_CAMA IN (14, 24)
GROUP BY NATID_AREA_HOSPITALARIA, NATID_FECHA, NATID_UNIDAD_FUNCIONAL3;

-- FUll outer join de las 2, porcentaje de ocupación

CREATE OR REPLACE VIEW MSTR_AGR_INDICE_DE_OCUPACION
AS
   SELECT NATID_AREA_HOSPITALARIA,
          NATID_FECHA,
          NATID_UNIDAD_FUNCIONAL3,
          NVL (ESTANCIAS, 0) ESTANCIAS,
          NVL (CAMAS_DISPONIBLES, 0) CAMAS_DISPONIBLES,
         DECODE (
             CAMAS_DISPONIBLES,
             NULL, NULL,
             ROUND ( (NVL (ESTANCIAS, 0)) / (NVL (CAMAS_DISPONIBLES, 0)), 2))
             INDICE_OCUPACION
     FROM    (  SELECT NATID_AREA_HOSPITALARIA,
                       NATID_FECHA,
                       NATID_UNIDAD_FUNCIONAL3_RESP NATID_UNIDAD_FUNCIONAL3,
                       COUNT (1) ESTANCIAS
                  FROM MSTR_DET_CAMAS_HISTORICO
                 WHERE NATID_TIPO_CAMA IN (14, 24) AND NATID_EPISODIO > 0
              GROUP BY NATID_AREA_HOSPITALARIA,
                       NATID_FECHA,
                       NATID_UNIDAD_FUNCIONAL3_RESP) ESTANCIAS
          FULL OUTER JOIN
             (  SELECT NATID_AREA_HOSPITALARIA,
                       NATID_FECHA,
                       NATID_UNIDAD_FUNCIONAL3,
                       COUNT (1) CAMAS_DISPONIBLES
                  FROM MSTR_DET_CAMAS_HISTORICO
                 WHERE NATID_TIPO_CAMA IN (14, 24)
              GROUP BY NATID_AREA_HOSPITALARIA,
                       NATID_FECHA,
                       NATID_UNIDAD_FUNCIONAL3) CAMAS
          USING (NATID_AREA_HOSPITALARIA,
                 NATID_FECHA,
                 NATID_UNIDAD_FUNCIONAL3)
/

CREATE TABLE TEMP_AGR_INDICE_DE_OCUPACION
NOLOGGING
NOPARALLEL
NOMONITORING
AS
   SELECT NATID_AREA_HOSPITALARIA,
          NATID_FECHA,
          NATID_UNIDAD_FUNCIONAL3,
          NVL (ESTANCIAS, 0) ESTANCIAS,
          NVL (CAMAS_DISPONIBLES, 0) CAMAS_DISPONIBLES,
          DECODE (
             CAMAS_DISPONIBLES,
             NULL, NULL,
             ROUND ( (NVL (ESTANCIAS, 0)) / (NVL (CAMAS_DISPONIBLES, 0)), 2))
             INDICE_OCUPACION
     FROM    (  SELECT NATID_AREA_HOSPITALARIA,
                       NATID_FECHA,
                       NATID_UNIDAD_FUNCIONAL3_RESP NATID_UNIDAD_FUNCIONAL3,
                       COUNT (1) ESTANCIAS
                  FROM MSTR_DET_CAMAS_HISTORICO
                 WHERE NATID_TIPO_CAMA IN (14, 24) AND NATID_EPISODIO > 0
              GROUP BY NATID_AREA_HOSPITALARIA,
                       NATID_FECHA,
                       NATID_UNIDAD_FUNCIONAL3_RESP) ESTANCIAS
          FULL OUTER JOIN
             (  SELECT NATID_AREA_HOSPITALARIA,
                       NATID_FECHA,
                       NATID_UNIDAD_FUNCIONAL3,
                       COUNT (1) CAMAS_DISPONIBLES
                  FROM MSTR_DET_CAMAS_HISTORICO
                 WHERE NATID_TIPO_CAMA IN (14, 24)
              GROUP BY NATID_AREA_HOSPITALARIA,
                       NATID_FECHA,
                       NATID_UNIDAD_FUNCIONAL3) CAMAS
          USING (NATID_AREA_HOSPITALARIA,
                 NATID_FECHA,
                 NATID_UNIDAD_FUNCIONAL3)