SELECT *
---DISTINCT  NATID_FECHA
--NATID_AREA_HOSPITALARIA, NATID_FECHA, NATID_FECHA_ULTIMO_REFRESCO, 
--   NATID_CENTRO_CAMA, NATID_UNIDAD_FUNCIONAL3_CAMA, NATID_UNIDAD_FUNCIONAL3_RESP, 
--   ESTANCIAS, NATID_CONTROL_ENFERMERIA, ETL_ERROR_DESCR
FROM MSTR_HOSPITALIZACION.MSTR_DET_ESTANCIAS_HISTORICO_2
WHERE NATID_CONTROL_ENFERMERIA = -2;
/
ALTER TABLE TEMP_TRASLADOS_A102004 READ WRITE;
UPDATE TEMP_TRASLADOS_A102004 T
SET ETL_ERROR_DESCR = 'No se encuentra la cama en el histórico por esta fecha, se pone el último C.E.',
NATID_CONTROL_ENFERMERIA = (SELECT NATID_CONTROL_ENFERMERIA FROM MSTR_DET_CAMAS_DEL_DIA D WHERE D.NATID_CAMA = T.NATID_CAMA)
WHERE NATID_CONTROL_ENFERMERIA = -2;
ALTER TABLE TEMP_TRASLADOS_A102004 READ ONLY;

--SELECT TRUNC(FIN_TASLADO), NATID_CAMA--, NATID_CONTROL_ENFERMERIA
--FROM (
SELECT DISTINCT T.NATID_CAMA, TRUNC (T.FIN_TRASLADO) FECHA --*
FROM TEMP_TRASLADOS_A102004 T
LEFT JOIN MSTR_DET_CAMAS_HISTORICO H
ON (T.NATID_CAMA = H.NATID_CAMA AND H.NATID_FECHA = TRUNC (T.FIN_TRASLADO))
--)
WHERE H.NATID_CAMA IS NULL
ORDER BY  TRUNC (T.FIN_TRASLADO) DESC
/
SELECT * FROM TEMP_TRASLADOS_A102004
WHERE NATID_CAMA = 46032
ORDER BY FIN_TRASLADO DESC;
/

SELECT * FROM REP_HIS_OWN.ADM_TRASLADO@SEE43DAE
WHERE TRASLADO_ID = 1172726
--UBIC_TERMINAL = 46032
ORDER BY FCH_APERTURA DESC;
/
SELECT CAH_AH_CODIGO NATID_AREA_HOSPITALARIA
                                ,TRUNC (SYSDATE) NATID_FECHA
                                --,LAST_REFRESH_DATE NATID_FECHA_ULTIMO_REFRESCO
                                ,NVL (UBI_CAH_CODIGO, -1) NATID_CENTRO
                                ,NVL (UNIDAD_FUNCIONAL, -1) NATID_UNIDAD_FUNCIONAL3
                                ,UBI_CODIGO NATID_CAMA
                                ,UBI_NOMBRE DESCR_CAMA
                                ,UBI_DESCRIPCION LDESC_CAMA
                                ,UBI_TIP_UBICACION NATID_TIPO_CAMA
                                ,TUBI_DESCRIPCION DESCR_TIPO_CAMA
                                ,DECODE (NUM_CAMA, NULL, -1, TIPO_AISLAMIENTO) NATID_TIPO_AISLAMIENTO --NVL (TIPO_AISLAMIENTO, NULL) NATID_TIPO_AISLAMIENTO
                                ,NVL (DECODE (NUM_CAMA, NULL, '--', COM_M_TIPO_AISLAMIENTO.NOMBRE), 'N/A') DESCR_TIPO_AISLAMIENTO
                                ,NVL (EPISODIO_ID, -1) NATID_EPISODIO
                        FROM COM_UBICACION_GESTION_LOCAL
                                 JOIN UBICACIONES
                                     ON (CODIGO_ESTRUCTURA = UBI_CODIGO)
                                 JOIN TIPOS_UBICACION
                                     ON (UBI_TIP_UBICACION = TUBI_CODIGO)
                                 JOIN CENTROS_AH
                                     ON (UBI_CAH_CODIGO = CAH_CODIGO)
--                                 JOIN ALL_DAE_MVIEWS
--                                     ON (MVIEW_NAME = 'COM_UBICACION_GESTION_LOCAL' AND OWNER = 'REP_HIS_OWN')
                                 LEFT JOIN COM_M_TIPO_AISLAMIENTO
                                     ON (TIPO_AISLAMIENTO = CODIGO)
                                 LEFT JOIN (SELECT UBICACION_ORIGEN NUM_CAMA FROM COM_UBICACION_AISLADA
                                                        UNION
                                                        SELECT UBICACION_AFECTADA NUM_CAMA FROM COM_UBICACION_AISLADA)
                                     ON (ID = NUM_CAMA)
                     WHERE ACTIVA = 1 AND UBI_ACTIVO = 0;
                     /
                     SELECT * FROM COM_UBICACION_GESTION_LOCAL WHERE CODIGO_ESTRUCTURA = 35682;
                     /
SELECT DISTINCT NATID_CAMA FROM TEMP_TRASLADOS_A102004
WHERE NATID_CONTROL_ENFERMERIA = -1;                     
/
SELECT * FROM UBICACIONES WHERE UBI_CODIGO IN (SELECT DISTINCT NATID_CAMA FROM TEMP_TRASLADOS_A102004
WHERE NATID_CONTROL_ENFERMERIA = -1);