/* Formatted on 27/03/2014 10:59:40 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_MAE_UNIDADES_FUNCIONALES3;
CREATE TABLE MSTR_MAE_UNIDADES_FUNCIONALES3
(
    NATID_AREA_HOSPITALARIA
 ,NATID_UNIDAD_FUNCIONAL3
 ,DESCR_UNIDAD_FUNCIONAL3
 ,NATID_UNIDAD_FUNCIONAL2
 ,CONSTRAINT MAE_UNIDADES_FUNCIONALES3_PK PRIMARY KEY (NATID_UNIDAD_FUNCIONAL3)
)
ORGANIZATION INDEX
NOLOGGING
NOMONITORING
NOPARALLEL
STORAGE (BUFFER_POOL KEEP) AS
	SELECT '-1' NATID_AREA_HOSPITALARIA
				,'-1' NATID_UNIDAD_FUNCIONAL3
				,'n/a' DESCR_UNIDAD_FUNCIONAL3
				,'-1' NATID_UNIDAD_FUNCIONAL2
		FROM DUAL
	UNION ALL
	SELECT UF_AH_CODIGO NATID_AREA_HOSPITALARIA
				,UF_CODIGO NATID_UNIDAD_FUNCIONAL3
				,UF_NOMBRE DESCR_UNIDAD_FUNCIONAL3
				,UF_UF_CODIGO NATID_UNIDAD_FUNCIONAL2
		FROM REP_PRO_EST.UNIDADES_FUNCIONALES@SEE41DAE
	 WHERE UF_UF_CODIGO IN (SELECT UF_CODIGO
														FROM REP_PRO_EST.UNIDADES_FUNCIONALES@SEE41DAE
													 WHERE UF_UF_CODIGO IN (SELECT UF_CODIGO
																										FROM REP_PRO_EST.UNIDADES_FUNCIONALES@SEE41DAE
																									 WHERE UF_UF_CODIGO IS NULL AND UF_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_LOCAL_CODIGOS)))
	UNION ALL
	-- Replica Nivel 1 sin hijos
	SELECT UF_AH_CODIGO NATID_AREA_HOSPITALARIA
				,UF_CODIGO NATID_UNIDAD_FUNCIONAL3
				,UF_NOMBRE || '**' DESCR_UNIDAD_FUNCIONAL3
				,UF_CODIGO NATID_UNIDAD_FUNCIONAL2
		FROM REP_PRO_EST.UNIDADES_FUNCIONALES@SEE41DAE
	 WHERE UF_UF_CODIGO IS NULL AND UF_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_LOCAL_CODIGOS) AND UF_FINAL = 'S'
	UNION ALL
	-- Replica Nivel 2 sin hijos
	SELECT UF_AH_CODIGO NATID_AREA_HOSPITALARIA
				,UF_CODIGO NATID_UNIDAD_FUNCIONAL3
				,UF_NOMBRE || '*' DESCR_UNIDAD_FUNCIONAL3
				,UF_CODIGO NATID_UNIDAD_FUNCIONAL2
		FROM REP_PRO_EST.UNIDADES_FUNCIONALES@SEE41DAE
	 WHERE UF_UF_CODIGO IN (SELECT UF_CODIGO
														FROM REP_PRO_EST.UNIDADES_FUNCIONALES@SEE41DAE
													 WHERE UF_UF_CODIGO IS NULL AND UF_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_LOCAL_CODIGOS))
				 AND UF_FINAL = 'S';
