CREATE USER MSTR_QUIROFANO IDENTIFIED BY "spanish-woman-90000-in-stomach";
GRANT RESOURCE, CONNECT TO MSTR_QUIROFANO;

GRANT "TC_ADMIN_ROLE" TO MSTR_QUIROFANO;
GRANT "TC_LDR_ROLE" TO MSTR_QUIROFANO;
GRANT "TC_MGR_ROLE" TO MSTR_QUIROFANO;
ALTER USER MSTR_QUIROFANO DEFAULT ROLE "CONNECT", "RESOURCE", "TC_ADMIN_ROLE", "TC_LDR_ROLE", "TC_MGR_ROLE";

GRANT SELECT ON MSTR_HOSPITALIZACION.MSTR_TIME_N1_AÑOS TO MSTR_QUIROFANO;
GRANT SELECT ON MSTR_HOSPITALIZACION.MSTR_TIME_N2_MESES TO MSTR_QUIROFANO;
GRANT SELECT ON MSTR_HOSPITALIZACION.MSTR_TIME_N3_DIAS TO MSTR_QUIROFANO;

GRANT SELECT ON MSTR_HOSPITALIZACION.MSTR_MAE_AREAS_HOSPITALARIAS TO MSTR_QUIROFANO;
GRANT SELECT ON MSTR_HOSPITALIZACION.MSTR_MAE_CENTROS TO MSTR_QUIROFANO;
GRANT SELECT ON MSTR_HOSPITALIZACION.MSTR_MAE_CONTROLES_ENFERMERIA TO MSTR_QUIROFANO;
GRANT SELECT ON MSTR_HOSPITALIZACION.MSTR_MAE_UNIDADES_FUNCIONALES1 TO MSTR_QUIROFANO;
GRANT SELECT ON MSTR_HOSPITALIZACION.MSTR_MAE_UNIDADES_FUNCIONALES2 TO MSTR_QUIROFANO;
GRANT SELECT ON MSTR_HOSPITALIZACION.MSTR_MAE_UNIDADES_FUNCIONALES3 TO MSTR_QUIROFANO;

GRANT CREATE SYNONYM TO MSTR_QUIROFANO;
GRANT CREATE VIEW TO MSTR_QUIROFANO;

GRANT CREATE TABLE TO MSTR_QUIROFANO;
GRANT CREATE JOB TO MSTR_QUIROFANO;

  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'MSTR_QUIROFANO',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'MSTR_QUIROFANO',
  GRANT_OPTION => FALSE);
END;
/
 BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'MSTR_QUIROFANO',
  GRANT_OPTION => FALSE);
END;
/