/* Formatted on 20/03/2014 10:20:12 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_CENTROS
(
	NATID_AREA_HOSPITALARIA
 ,NATID_CENTRO
 ,DESCR_CENTRO
) AS
	SELECT '-1' NATID_AREA_HOSPITALARIA, -1 NATID_CENTRO, 'n/a' DESCR_CENTRO FROM DUAL
	UNION ALL
	SELECT CAH_AH_CODIGO NATID_AREA_HOSPITALARIA, CAH_CODIGO NATID_CENTRO, CAH_NOMBRE DESCR_CENTRO
		FROM REP_PRO_EST.CENTROS_AH@SEE41DAE
	 WHERE CAH_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_LOCAL_CODIGOS);