CREATE TABLE MSTR_DET_ESTANCIAS_HISTORICO_2
NOLOGGING NOMONITORING PARALLEL
AS
SELECT * FROM
MSTR_DET_ESTANCIAS_HISTORICO
WHERE 1=0;
/

ALTER TABLE MSTR_DET_ESTANCIAS_HISTORICO_2 ADD (NATID_CONTROL_ENFERMERIA VARCHAR2(8), ETL_ERROR_DESCR VARCHAR2(250));
/