/* Formatted on 10/14/2014 1:27:00 PM (QP5 v5.163.1008.3004) */
--EXEC ETL_LOAD_ALTAS_DEL_DIA_V3.P_001_MULTI_AREA('02024');
DROP TABLE MSTR_DET_ALTAS_HISTORICO;

CREATE TABLE MSTR_DET_ALTAS_HISTORICO
NOLOGGING
NOCOMPRESS
NOCACHE
PARALLEL
NOMONITORING
AS
   SELECT *
     FROM TEMP_ALTAS_A102024
    WHERE 1 = 2;

CREATE INDEX MSTR_DET_ALTAS_HISTORICO_PK
   ON MSTR_DET_ALTAS_HISTORICO (NATID_AREA_HOSPITALARIA, NATID_ADMISION)
   NOLOGGING
   PARALLEL;

CREATE INDEX MSTR_DET_INGRESOS_HISTORICO_PK
   ON MSTR_DET_INGRESOS_HISTORICO (NATID_AREA_HOSPITALARIA, NATID_ADMISION)
   NOLOGGING
   PARALLEL;

CREATE INDEX MSTR_DET_ESTANCIAS_HISTORIC_PK
   ON MSTR_DET_ESTANCIAS_HISTORICO (NATID_AREA_HOSPITALARIA,
                                    NATID_FECHA,
                                    NATID_CENTRO_CAMA,
                                    NATID_UNIDAD_FUNCIONAL3_CAMA,
                                    NATID_UNIDAD_FUNCIONAL3_RESP,
                                    NATID_CONTROL_ENFERMERIA)
   NOLOGGING
   PARALLEL;

    ALTER TABLE MSTR_DET_ALTAS_HISTORICO ADD
CONSTRAINT MSTR_DET_ALTAS_HISTORICO_PK
 PRIMARY KEY (NATID_AREA_HOSPITALARIA, NATID_ADMISION);


    ALTER TABLE MSTR_DET_INGRESOS_HISTORICO ADD
CONSTRAINT MSTR_DET_INGRESOS_HISTORICO_PK
 PRIMARY KEY (NATID_AREA_HOSPITALARIA, NATID_ADMISION);

    ALTER TABLE MSTR_DET_ESTANCIAS_HISTORICO ADD
CONSTRAINT MSTR_DET_ESTANCIAS_HISTORIC_PK
 PRIMARY KEY (NATID_AREA_HOSPITALARIA, NATID_FECHA, NATID_CENTRO_CAMA, NATID_UNIDAD_FUNCIONAL3_CAMA, NATID_UNIDAD_FUNCIONAL3_RESP,
NATID_CONTROL_ENFERMERIA);