/* Formatted on 27/03/2014 10:52:50 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_MAE_UNIDADES_FUNCIONALES1;
CREATE TABLE MSTR_MAE_UNIDADES_FUNCIONALES1
(
	NATID_AREA_HOSPITALARIA
 ,NATID_UNIDAD_FUNCIONAL1
 ,DESCR_UNIDAD_FUNCIONAL1
 ,CONSTRAINT MAE_UNIDADES_FUNCIONALES1_PK PRIMARY KEY (NATID_UNIDAD_FUNCIONAL1)
)
ORGANIZATION INDEX
NOLOGGING
NOMONITORING
NOPARALLEL
STORAGE (BUFFER_POOL KEEP) AS
	SELECT '-1' NATID_AREA_HOSPITALARIA, '-1' NATID_UNIDAD_FUNCIONAL1, 'n/a' DESCR_UNIDAD_FUNCIONAL1 FROM DUAL
	UNION ALL
	SELECT UF_AH_CODIGO NATID_AREA_HOSPITALARIA, UF_CODIGO NATID_UNIDAD_FUNCIONAL1, UF_NOMBRE DESCR_UNIDAD_FUNCIONAL1
		FROM REP_PRO_EST.UNIDADES_FUNCIONALES@SEE41DAE
	 WHERE UF_UF_CODIGO IS NULL AND UF_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_LOCAL_CODIGOS);