/* Formatted on 27/03/2014 10:38:44 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DROP TABLE MSTR_MAE_CENTROS;
CREATE TABLE MSTR_MAE_CENTROS
(
	NATID_AREA_HOSPITALARIA
 ,NATID_CENTRO
 ,DESCR_CENTRO
 ,CONSTRAINT MSTR_MAE_CENTROS_PK PRIMARY KEY (NATID_CENTRO)
)
ORGANIZATION INDEX
NOLOGGING
NOMONITORING
NOPARALLEL
STORAGE (BUFFER_POOL KEEP) AS
	SELECT '-1' NATID_AREA_HOSPITALARIA, -1 NATID_CENTRO, 'n/a' DESCR_CENTRO FROM DUAL
	UNION ALL
	SELECT CAH_AH_CODIGO NATID_AREA_HOSPITALARIA, CAH_CODIGO NATID_CENTRO, CAH_NOMBRE DESCR_CENTRO
		FROM REP_PRO_EST.CENTROS_AH@SEE41DAE
	 WHERE CAH_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_LOCAL_CODIGOS);