/* Formatted on 4/26/2014 19:16:32 (QP5 v5.163.1008.3004) */
  SELECT                          /*+ parallel(MSTR_DET_INGRESOS_HISTORICO) */
        COUNT (NATID_ADMISION), NATID_FECHA, NATID_UNIDAD_FUNCIONAL3
    FROM MSTR_HOSPITALIZACION.MSTR_DET_INGRESOS_HISTORICO
   WHERE NATID_FECHA = '6-FEB-2014'
GROUP BY NATID_FECHA, NATID_UNIDAD_FUNCIONAL3
/
SELECT  /*+ parallel(MSTR_DET_INGRESOS_HISTORICO) */ * FROM MSTR_HOSPITALIZACION.MSTR_DET_INGRESOS_HISTORICO
/