/* Formatted on 5/14/2014 11:31:50 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_UTL_ULTIMOS_DATOS_DISPON
AS
     SELECT NATID_AREA_HOSPITALARIA,
            DESCR_AREA_HOSPITALARIA,
            DESCR_INSTANCIA,
            DESCR_REPLICA,
            ULTIMO_DATO_DISPONIBLE_MIN,
            ULTIMO_DATO_DISPONIBLE_MAX,
            NUMTODSINTERVAL (
               (ULTIMO_DATO_DISPONIBLE_MAX - ULTIMO_DATO_DISPONIBLE_MIN),
               'day')
               LAPSO
       FROM TABLE (func_get_tab_tf_replicas)
   ORDER BY LAPSO DESC