/* Formatted on 5/8/2014 14:08:13 (QP5 v5.163.1008.3004) */

  SELECT ADMISION, COUNT (ADMISION) TRASLADOS_SIN_PADRE
    FROM (SELECT ADMISION
            FROM REP_HIS_OWN.ADM_TRASLADO@HUE40DAE
           WHERE TRASLADO_PADRE IS NULL)
GROUP BY ADMISION
  HAVING COUNT (ADMISION) > 1
ORDER BY ADMISION DESC
/
SELECT * FROM REP_HIS_OWN.ADM_TRASLADO@HUE40DAE
WHERE ADMISION IN (1148798) AND TRASLADO_PADRE IS NULL
ORDER BY ADMISION
/
SELECT * FROM REP_HIS_OWN.ADM_ADMISION@HUE40DAE
WHERE ADMISION_ID = 1148798
/