/* Formatted on 4/24/2014 13:29:50 (QP5 v5.163.1008.3004) */
SELECT                                                                     --*
      COUNT (ADMISION_ID)
  FROM REP_HIS_OWN.ADM_ADMISION@SEE41DAE
 WHERE FCH_INGRESO >= '01-JAN-2013' AND EPIS_CONTAB = 1;

SELECT COUNT (NATID_ADMISION)
  FROM (
--CREATE TABLE TEMP_INGRESOS_B10 NOLOGGING
--AS
SELECT CAH_AH_CODIGO NATID_AREA_HOSPITALARIA,
       TRUNC (FCH_INGRESO) NATID_FECHA,
       LAST_REFRESH_DATE NATID_FECHA_ULTIMO_REFRESCO,
       NVL (CENTRO_INGRESO, -1) NATID_CENTRO,
       NVL (UNID_FUNC_INGRESO, -1) NATID_UNIDAD_FUNCIONAL3,
       NVL (UNID_FUNC_RESP, -1) NATID_UNIDAD_FUNCIONAL3_RESP,
       ADMISION_ID NATID_ADMISION,
       NVL (EPISODIO_ID, -1) NATID_EPISODIO,
       NUHSA NATID_NUHSA,
       DES_MODAL_ASIST IND_MODALIDAD_ASISTENCIAL,
       DECODE (HD_QUIR_SN,  0, 'Médico',  1, 'Quirúrgico')
          IND_MEDICO_QUIRURGICO,
       DES_PROCEDENCIA IND_PROCEDENTE_DE,
       DES_MOTIVO_ING IND_URGENTE_PROGRAMADO,
       NVL (UBICACION_TERMINAL, -1) NATID_CAMA,
       NVL (UNIDAD_CUIDADO, -1) NATID_CONTROL_ENFERMERIA
  FROM REP_HIS_OWN.ADM_ADMISION@SEE41DAE
       JOIN REP_PRO_EST.CENTROS_AH@SEE41DAE
          ON (CENTRO_INGRESO = CAH_CODIGO)
       JOIN SYS.ALL_MVIEWS@SEE41DAE
          ON (MVIEW_NAME = 'ADM_ADMISION' AND OWNER = 'REP_HIS_OWN')
       JOIN REP_HIS_OWN.ADM_EPIS_DETALLE@SEE41DAE
          ON (ADMISION_ID = REFERENCIA_ID)
       JOIN REP_HIS_OWN.COM_USUARIO@SEE41DAE
          ON (USUARIO = ID_USUARIO)
       JOIN REP_HIS_OWN.ADM_M_MODAL_ASIST@SEE41DAE
          ON (ADM_ADMISION.MODALIDAD_ASIST = ADM_M_MODAL_ASIST.MODAL_ASIST_ID)
       JOIN REP_HIS_OWN.ADM_M_PROCEDENCIA@SEE41DAE
          ON (ORIGEN_INGRESO = PROCEDENCIA_ID)
       JOIN REP_HIS_OWN.ADM_M_MOTIVO_INGRESO@SEE41DAE
          ON (MOTIVO_INGRESO = MOTIVO_ING_ID)
 WHERE FCH_INGRESO >= '01-JAN-2013' AND EPIS_CONTAB = 1
 --AND 1 = 0
);
/