/* Formatted on 5/22/2014 9:09:56 (QP5 v5.163.1008.3004) */
DECLARE
   v_NATID_EPISODIO   MSTR_DET_CAMAS_HISTORICO.NATID_EPISODIO%TYPE;
BEGIN
   FOR C1 IN (SELECT LC.NATID_AREA_HOSPITALARIA, LC.DB_LINK_REPLICA
                FROM MSTR_UTL_LOCAL_CODIGOS LC
               WHERE ENABLED = 1 AND LC.NATID_AREA_HOSPITALARIA = '02003')
   LOOP
      FOR C2
         IN (SELECT CH.NATID_EPISODIO, CH.NATID_FECHA
               FROM MSTR_DET_CAMAS_HISTORICO CH
              WHERE CH.NATID_AREA_HOSPITALARIA = C1.NATID_AREA_HOSPITALARIA
                    AND CH.NATID_UNIDAD_FUNCIONAL3_RESP IS NULL
                    AND CH.NATID_EPISODIO > 0
                    ORDER BY CH.NATID_EPISODIO, CH.NATID_FECHA)
      LOOP
         DBMS_OUTPUT.put_line (C2.NATID_EPISODIO||' '||C2.NATID_FECHA);
      END LOOP;
   END LOOP;
END;