/* Formatted on 09/07/2014 14:07:21 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
	SELECT MVIEW_NAME, LAST_REFRESH_DATE
		FROM SYS.ALL_MVIEWS@SEE40DAE
	 WHERE OWNER = 'REP_HIS_OWN'
ORDER BY 2
/
select count(1) from rep_his_own.ADM_MOVIMIENTO_HC@hue40dae;
/
    SELECT MVIEW_NAME, LAST_REFRESH_DATE
        FROM SYS.ALL_MVIEWS@HUE40DAE
     WHERE OWNER = 'REP_HIS_OWN'
ORDER BY 2
/
DESC REP_HIS_OWN.ADM_MOVIMIENTO_HC@HUE40DAE
/
    SELECT MVIEW_NAME, LAST_REFRESH_DATE
        FROM SYS.ALL_MVIEWS@GRE41DAE
     WHERE OWNER = 'REP_HIS_OWN'
ORDER BY 2
/

SELECT * FROM REP_HIS_OWN.COM_M_MENU@HUE40DAE;