SELECT DISTINCT OBJECT_NAME REPORT_NAME, FACT_OBJECT_NAME TABLE_NAME
FROM
(
	SELECT 
				METADATA_REPORTS.OBJECT_ID
				,METADATA_REPORTS.OBJECT_TYPE
				,METADATA_REPORTS.OBJECT_NAME
				,METADATA_ATTRIBUTES.OBJECT_ID COMPONENT_OBJECT_ID
                ,METADATA_ATTRIBUTES.OBJECT_TYPE COMPONENT_OBJECT_TYPE                
                ,METADATA_ATTRIBUTES.OBJECT_NAME COMPONENT_OBJECT_NAME
                ,METADATA_FACTS.OBJECT_ID FACT_OBJECT_ID
                ,METADATA_FACTS.OBJECT_TYPE FACT_OBJECT_TYPE                
                ,METADATA_FACTS.OBJECT_NAME FACT_OBJECT_NAME
		FROM DSSMDOBJINFO METADATA_REPORTS 
        JOIN DSSMDOBJDEPN METADATA_REPORT_COMPONENTS ON (METADATA_REPORTS.OBJECT_ID= METADATA_REPORT_COMPONENTS.OBJECT_ID)
        JOIN DSSMDOBJINFO METADATA_ATTRIBUTES ON (METADATA_REPORT_COMPONENTS.DEPN_OBJID= METADATA_ATTRIBUTES.OBJECT_ID)
        JOIN DSSMDOBJDEPN METADATA_OBJECT_COMPONENTS ON (METADATA_ATTRIBUTES.OBJECT_ID= METADATA_OBJECT_COMPONENTS.OBJECT_ID)
        JOIN DSSMDOBJINFO METADATA_FACTS ON (METADATA_OBJECT_COMPONENTS.DEPN_OBJID= METADATA_FACTS.OBJECT_ID)
	 WHERE METADATA_REPORTS.PROJECT_ID IN ('EA835B9E11E31A1109D30080EFD500F9') AND METADATA_REPORTS.OBJECT_TYPE = 3 /*REPORTS*/
     AND METADATA_ATTRIBUTES.OBJECT_TYPE IN (4, 12) /*METRICS, ATTRIBUTES*/
     AND METADATA_FACTS.OBJECT_TYPE IN (13, 15) /*FACTS, TABLES*/
)
WHERE FACT_OBJECT_TYPE = 15
UNION ALL
SELECT DISTINCT OBJECT_NAME REPORT_NAME, FACT_OBJECT_NAME TABLE_NAME
FROM
(
    SELECT 
                METADATA_REPORTS.OBJECT_ID
                ,METADATA_REPORTS.OBJECT_TYPE
                ,METADATA_REPORTS.OBJECT_NAME
                ,METADATA_ATTRIBUTES.OBJECT_ID COMPONENT_OBJECT_ID
                ,METADATA_ATTRIBUTES.OBJECT_TYPE COMPONENT_OBJECT_TYPE                
                ,METADATA_ATTRIBUTES.OBJECT_NAME COMPONENT_OBJECT_NAME
                ,METADATA_TABLES.OBJECT_ID FACT_OBJECT_ID
                ,METADATA_TABLES.OBJECT_TYPE FACT_OBJECT_TYPE                
                ,METADATA_TABLES.OBJECT_NAME FACT_OBJECT_NAME
        FROM DSSMDOBJINFO METADATA_REPORTS 
        JOIN DSSMDOBJDEPN METADATA_REPORT_COMPONENTS ON (METADATA_REPORTS.OBJECT_ID= METADATA_REPORT_COMPONENTS.OBJECT_ID)
        JOIN DSSMDOBJINFO METADATA_ATTRIBUTES ON (METADATA_REPORT_COMPONENTS.DEPN_OBJID= METADATA_ATTRIBUTES.OBJECT_ID)
        JOIN DSSMDOBJDEPN METADATA_OBJECT_COMPONENTS ON (METADATA_ATTRIBUTES.OBJECT_ID= METADATA_OBJECT_COMPONENTS.OBJECT_ID)
        JOIN DSSMDOBJINFO METADATA_FACTS ON (METADATA_OBJECT_COMPONENTS.DEPN_OBJID= METADATA_FACTS.OBJECT_ID)
        JOIN DSSMDOBJDEPN METADATA_FACT_COMPONENTS ON (METADATA_FACTS.OBJECT_ID= METADATA_FACT_COMPONENTS.OBJECT_ID)
        LEFT JOIN DSSMDOBJINFO METADATA_TABLES ON (METADATA_FACT_COMPONENTS.DEPN_OBJID= METADATA_TABLES.OBJECT_ID AND METADATA_TABLES.OBJECT_TYPE IN (15))
     WHERE METADATA_REPORTS.PROJECT_ID IN ('EA835B9E11E31A1109D30080EFD500F9') AND METADATA_REPORTS.OBJECT_TYPE = 3 /*REPORTS*/
     AND METADATA_ATTRIBUTES.OBJECT_TYPE IN (4, 12) /*METRICS, ATTRIBUTES*/
     AND METADATA_FACTS.OBJECT_TYPE IN (13, 15) /*FACTS, TABLES*/
     AND METADATA_TABLES.OBJECT_TYPE IN (15) /* TABLES*/
)
WHERE FACT_OBJECT_TYPE = 15
ORDER BY 1, 2