/* Formatted on 26/03/2014 13:34:43 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
DECLARE
--v_COUNT NUMBER;
BEGIN
    FOR C1 IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_LOCAL_CODIGOS) LOOP
        ETL_LOAD_CAMAS_DEL_DIA.P_001_MULTI_AREA (C1.NATID_AREA_HOSPITALARIA);
    END LOOP;
END;
/

CREATE SYNONYM COM_UBICACION_GESTION_LOCAL FOR REP_HIS_OWN.COM_UBICACION_GESTION_LOCAL@SEE43DAE;
SELECT * FROM COM_UBICACION_GESTION_LOCAL;
/

EXEC ETL_LOAD_CAMAS_DEL_DIA.P_001_MULTI_AREA('02004');
/

