SELECT 
NATID_AREA_HOSPITALARIA, NATID_FECHA, NATID_FECHA_ULTIMO_REFRESCO, 
   NATID_CENTRO_INGRESO, NATID_CENTRO_CAMA, NATID_UNIDAD_FUNCIONAL3_RESP, 
   NATID_UNIDAD_FUNCIONAL3_CAMA, NATID_CAMA, NATID_ADMISION, 
   NATID_TRASLADO, INICIO_TRASLADO, FIN_TRASLADO, 
   LAPSO_DE_TIEMPO, OBSERVACIONES, NATID_TRASLADO_ANTERIOR, 
   IND_CAMBIO_ASISTENCIA, NATID_CONTROL_ENFERMERIA, NATID_NUHSA, 
   ETL_ERROR_DESCR
FROM MSTR_HOSPITALIZACION.TEMP_TRASLADOS_A102003
WHERE NATID_CONTROL_ENFERMERIA < 0;
;
SELECT * FROM TEMP_TRASLADOS_A302003;
/
SELECT COUNT(*), 'sin' FROM TEMP_TRASLADOS_A102003
WHERE NATID_CONTROL_ENFERMERIA < 0
UNION ALL
SELECT COUNT(*), 'con' FROM TEMP_TRASLADOS_A102003
WHERE NATID_CONTROL_ENFERMERIA >= 0
UNION ALL
SELECT COUNT(*), 'con' FROM TEMP_TRASLADOS_A102003
WHERE NATID_CONTROL_ENFERMERIA IS NULL
;
SELECT COUNT(*), NATID_CONTROL_ENFERMERIA FROM TEMP_TRASLADOS_A102003
WHERE NATID_CONTROL_ENFERMERIA < 0
GROUP BY NATID_CONTROL_ENFERMERIA;
/
