SELECT 
NATID_AREA_HOSPITALARIA, NATID_FECHA, NATID_FECHA_ULTIMO_REFRESCO, 
   NATID_CENTRO, NATID_UNIDAD_FUNCIONAL3, NATID_CAMA, 
   DESCR_CAMA, LDESC_CAMA, NATID_TIPO_CAMA, 
   DESCR_TIPO_CAMA, NATID_TIPO_AISLAMIENTO, DESCR_TIPO_AISLAMIENTO, 
   NATID_EPISODIO, NATID_CONTROL_ENFERMERIA, NATID_NUHSA, 
   ETL_ERROR_DESCR
FROM TEMP_CAMAS_A102004