EXEC ETL_LOAD_ESTANCIAS_V3.P_001_MULTI_AREA('02018');
/
UPDATE TEMP_TRASLADOS_A102004 A1
       SET NATID_NUHSA =
              (SELECT NATID_NUHSA
                 FROM TEMP_TRASLADOS_A202004 A2
            WHERE A2.NATID_ADMISION = A1.NATID_ADMISION)
/
UPDATE TEMP_TRASLADOS_A102017 A1
       SET NATID_NUHSA =
              (SELECT NATID_NUHSA
                 FROM TEMP_TRASLADOS_A202017 A2
            WHERE A2.NATID_ADMISION = A1.NATID_ADMISION)
/
UPDATE TEMP_TRASLADOS_A102009 A1
       SET NATID_NUHSA =
              (SELECT NATID_NUHSA
                 FROM TEMP_TRASLADOS_A202009 A2
            WHERE A2.NATID_ADMISION = A1.NATID_ADMISION)                        