/* Formatted on 10/7/2014 11:39:35 AM (QP5 v5.163.1008.3004) */
DROP TABLE TEMP_ALTAS_A102003;

CREATE TABLE TEMP_ALTAS_A102003
(
   NATID_AREA_HOSPITALARIA,
   NATID_FECHA,
   NATID_FECHA_ULTIMO_REFRESCO,
   NATID_CENTRO,
   NATID_UNIDAD_FUNCIONAL3,
   NATID_UNIDAD_FUNCIONAL3_RESP,
   NATID_ADMISION,
   NATID_EPISODIO,
   NATID_NUHSA,
   IND_MODALIDAD_ASISTENCIAL,
   IND_MEDICO_QUIRURGICO,
   IND_DESTINO_AL_ALTA,
   IND_MOTIVO_DE_ALTA,
   NATID_CAMA,
   NATID_CONTROL_ENFERMERIA
)
NOLOGGING
PARALLEL
AS
   SELECT                                                                                                                                                                                                        /*+DRIVING_SITE(ADM_ADMISION)*/
         CAH_AH_CODIGO NATID_AREA_HOSPITALARIA,
          TRUNC (FCH_ALTA) NATID_FECHA,
          LAST_REFRESH_DATE NATID_FECHA_ULTIMO_REFRESCO,
          NVL (CENTRO_ALTA, -1) NATID_CENTRO,
          NVL (UNID_FUNC_ALTA, -1) NATID_UNIDAD_FUNCIONAL3,
          NVL (UNID_FUNC_RESP, -1) NATID_UNIDAD_FUNCIONAL3_RESP,
          ADMISION_ID NATID_ADMISION,
          NVL (EPISODIO_ID, -1) NATID_EPISODIO,
          TO_CHAR (USUARIO) NATID_NUHSA,
          DES_MODAL_ASIST IND_MODALIDAD_ASISTENCIAL,
          DECODE (HD_QUIR_SN,  0, 'Médico',  1, 'Quirúrgico') IND_MEDICO_QUIRURGICO,
          DES_DESTINO_ALTA IND_DESTINO_AL_ALTA,
          DES_MOTIVO_ALTA IND_MOTIVO_DE_ALTA,
          NVL (UBICACION_TERMINAL, -1) NATID_CAMA,
          NVL (UNIDAD_CUIDADO, -1) NATID_CONTROL_ENFERMERIA
     FROM REP_HIS_OWN.ADM_ADMISION@SEE41DAE
          JOIN REP_PRO_EST.CENTROS_AH@SEE41DAE
             ON (CENTRO_ALTA = CAH_CODIGO)
          JOIN SYS.ALL_MVIEWS@SEE41DAE
             ON (MVIEW_NAME = 'ADM_ADMISION' AND OWNER = 'REP_HIS_OWN')
          JOIN REP_HIS_OWN.ADM_EPIS_DETALLE@SEE41DAE
             ON (ADMISION_ID = REFERENCIA_ID)
          JOIN REP_HIS_OWN.ADM_M_MODAL_ASIST@SEE41DAE
             ON (ADM_ADMISION.MODALIDAD_ASIST = ADM_M_MODAL_ASIST.MODAL_ASIST_ID)
          JOIN REP_HIS_OWN.ADM_M_DESTINO_ALTA@SEE41DAE
             ON (DESTINO_ALTA = DESTINO_ALTA_ID)
          JOIN REP_HIS_OWN.ADM_M_MOTIVO_ALTA@SEE41DAE
             ON (MOTIVO_ALTA = MOTIVO_ALTA_ID)
    WHERE EPIS_CONTAB = 1 AND FCH_ALTA >= '01-JAN-2013';

CREATE INDEX TEMP_ALTAS_A102003_PK
   ON TEMP_ALTAS_A102003 (NATID_ADMISION)
   NOLOGGING
   PARALLEL;

ALTER TABLE TEMP_ALTAS_A102003
ADD CONSTRAINT TEMP_ALTAS_A102003_PK PRIMARY KEY (NATID_ADMISION);