/* Formatted on 10/28/2014 2:51:30 PM (QP5 v5.163.1008.3004) */
BEGIN
   FOR C1 IN (SELECT NATID_AREA_HOSPITALARIA
                FROM MSTR_UTL_LOCAL_CODIGOS
               WHERE ENABLED = 1)
   LOOP
      ETL_LOAD_INTERVENCIONES_V3.P_001_MULTI_AREA (C1.NATID_AREA_HOSPITALARIA);
   END LOOP;
END;

EXEC ETL_LOAD_INTERVENCIONES_V3.P_001_MULTI_AREA('02003');


SELECT PQ_CAB_ID NATID_CABECERA_PARTE,
       PQ_DET_ID NATID_DETALLE_PARTE,
       IQ_PRE_ID NATID_INTERVENCION_PRE,
       IQ_POST_ID NATID_INTERVENCION_POST,
       ORDEN IND_ORDEN,
       PREING_DET_ID NATID_DETALLE_PREINGRESO,
       NVL (EPISODIO_ID, -1) NATID_EPISODIO,
       (FCH_APERTURA + (HORA_APERTURA - TRUNC (HORA_APERTURA))) NATID_FECHA_INICIO_EPISODIO,
       (FCH_CIERRE + (HORA_CIERRE - TRUNC (HORA_CIERRE))) NATID_FECHA_FIN_EPISODIO,
       TIPO_PROGRAMACION IND_TIPO_PROGRAMACION,
       ID_USUARIO NATID_USUARIO,
       DURACION_PREVISTA,
       NVL (ADMISION_ID, -1) NATID_ADMISION,
       CENTRO_ID NATID_CENTRO,
       UNI_FUNCIONAL_ID NATID_UNIDAD_FUNCIONAL,
       QUIROFANO NATID_QUIROFANO,
       ESTADO_ID IND_ESTADO,
       NVL (MODALIDAD_ASIST, -1) IND_MODALIDAD_ASISTENCIAL,
       FECHA_HORA_INICIO NATID_FECHA_INICIO_PARTE,
       FECHA_HORA_FIN NATID_FECHA_FIN_PARTE
  FROM REP_HIS_OWN.ADM_QRF_IQ_PRE@SEE41DAE
       LEFT JOIN REP_HIS_OWN.ADM_EPISODIO@SEE41DAE
          USING (EPISODIO_ID)
       JOIN REP_HIS_OWN.ADM_QRF_PQ_DET@SEE41DAE
          USING (IQ_PRE_ID)
       JOIN REP_HIS_OWN.ADM_QRF_PQ_CAB@SEE41DAE
          USING (PQ_CAB_ID)
       JOIN SYS.ALL_MVIEWS@SEE41DAE
          ON (MVIEW_NAME = 'ADM_QRF_IQ_PRE' AND OWNER = 'REP_HIS_OWN')
 WHERE IQ_DESPR_ID IS NULL AND FECHA_HORA_INICIO >= ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), -12)