CREATE MATERIALIZED VIEW  TEST_DBLINKS REFRESH COMPLETE START WITH (SYSDATE) NEXT  (SYSDATE+1/1440) WITH ROWID
AS
SELECT DB_LINK ||' '||DECODE(FUNC_IS_LINK_ACTIVE (DB_LINK),0,'FAILED ','SUCCESS ') IS_ACTIVE FROM ALL_DB_LINKS WHERE OWNER = 'PUBLIC' AND FUNC_IS_LINK_ACTIVE (DB_LINK) = 0 AND DB_LINK <> 'SYG'