
SELECT NATID_AREA_HOSPITALARIA, NATID_EPISODIO, NATID_FECHA, CH.NATID_FECHA_ULTIMO_REFRESCO, CH.NATID_UNIDAD_FUNCIONAL3_RESP, TC.UNIDAD_FUNCIONAL, CH.ETL_ERROR_DESCR
FROM MSTR_DET_CAMAS_HISTORICO CH
 JOIN TEMP_CAMAS_A2020037 TC USING (NATID_AREA_HOSPITALARIA, NATID_EPISODIO, NATID_FECHA)
WHERE     NATID_AREA_HOSPITALARIA = '02037'
         AND CH.NATID_UNIDAD_FUNCIONAL3_RESP IS NULL
         AND NATID_EPISODIO > 0;
         --AND TRUNC(CH.NATID_FECHA_ULTIMO_REFRESCO) <> NATID_FECHA;
/

SELECT *--TC.NATID_AREA_HOSPITALARIA, TC.NATID_EPISODIO, TC.NATID_FECHA
FROM TEMP_CAMAS_A2020037 TC
WHERE NATID_CAMA <> UBIC_TERMINAL
/

SELECT * FROM REP_HIS_OWN.ADM_EPIS_DETALLE@HUE40DAE
WHERE EPISODIO_ID IN (1753880)

