/* Formatted on 01/04/2014 9:55:39 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
CREATE OR REPLACE FORCE VIEW UTL_CHECK_HISTORICO_CAMAS
(
	NATID_AREA_HOSPITALARIA
 ,NATID_FECHA
 ,COUNT_CAMAS
) AS
		SELECT NATID_AREA_HOSPITALARIA, NATID_FECHA, COUNT (NATID_CAMA) COUNT_CAMAS
			FROM MSTR_DET_CAMAS_HISTORICO
	GROUP BY NATID_AREA_HOSPITALARIA, NATID_FECHA
	ORDER BY NATID_FECHA DESC, NATID_AREA_HOSPITALARIA;
