/* Formatted on 11/7/2014 5:49:31 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_AREAS_HOSPITALARIAS
(
   NATID_AREA_HOSPITALARIA,
   DESCR_AREA_HOSPITALARIA,
   BAS64_AREA_HOSPITALARIA
)
AS
   SELECT "NATID_AREA_HOSPITALARIA", "DESCR_AREA_HOSPITALARIA", "BAS64_AREA_HOSPITALARIA" FROM MSTR_HOSPITALIZACION.MSTR_MAE_AREAS_HOSPITALARIAS;


/* Formatted on 11/7/2014 5:49:31 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_CENTROS
(
   NATID_AREA_HOSPITALARIA,
   NATID_CENTRO,
   DESCR_CENTRO,
   BAS64_CENTRO
)
AS
   SELECT "NATID_AREA_HOSPITALARIA",
          "NATID_CENTRO",
          "DESCR_CENTRO",
          "BAS64_CENTRO"
     FROM MSTR_HOSPITALIZACION.MSTR_MAE_CENTROS;


/* Formatted on 11/7/2014 5:49:31 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_CONTROLES_ENFERMERIA
(
   NATID_AREA_HOSPITALARIA,
   NATID_CENTRO,
   NATID_CONTROL_ENFERMERIA,
   DESCR_CONTROL_ENFERMERIA,
   LDESC_CONTROL_ENFERMERIA
)
AS
   SELECT "NATID_AREA_HOSPITALARIA",
          "NATID_CENTRO",
          "NATID_CONTROL_ENFERMERIA",
          "DESCR_CONTROL_ENFERMERIA",
          "LDESC_CONTROL_ENFERMERIA"
     FROM MSTR_HOSPITALIZACION.MSTR_MAE_CONTROLES_ENFERMERIA;


/* Formatted on 11/7/2014 5:49:31 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_UNIDADES_FUNCIONALES1
(
   NATID_AREA_HOSPITALARIA,
   NATID_UNIDAD_FUNCIONAL1,
   DESCR_UNIDAD_FUNCIONAL1,
   BAS64_UNIDAD_FUNCIONAL1
)
AS
   SELECT "NATID_AREA_HOSPITALARIA",
          "NATID_UNIDAD_FUNCIONAL1",
          "DESCR_UNIDAD_FUNCIONAL1",
          "BAS64_UNIDAD_FUNCIONAL1"
     FROM MSTR_HOSPITALIZACION.MSTR_MAE_UNIDADES_FUNCIONALES1;


/* Formatted on 11/7/2014 5:49:31 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_UNIDADES_FUNCIONALES2
(
   NATID_AREA_HOSPITALARIA,
   NATID_UNIDAD_FUNCIONAL2,
   DESCR_UNIDAD_FUNCIONAL2,
   NATID_UNIDAD_FUNCIONAL1
)
AS
   SELECT "NATID_AREA_HOSPITALARIA",
          "NATID_UNIDAD_FUNCIONAL2",
          "DESCR_UNIDAD_FUNCIONAL2",
          "NATID_UNIDAD_FUNCIONAL1"
     FROM MSTR_HOSPITALIZACION.MSTR_MAE_UNIDADES_FUNCIONALES2;


/* Formatted on 11/7/2014 5:49:31 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_UNIDADES_FUNCIONALES3
(
   NATID_AREA_HOSPITALARIA,
   NATID_UNIDAD_FUNCIONAL3,
   DESCR_UNIDAD_FUNCIONAL3,
   NATID_UNIDAD_FUNCIONAL2
)
AS
   SELECT "NATID_AREA_HOSPITALARIA",
          "NATID_UNIDAD_FUNCIONAL3",
          "DESCR_UNIDAD_FUNCIONAL3",
          "NATID_UNIDAD_FUNCIONAL2"
     FROM MSTR_HOSPITALIZACION.MSTR_MAE_UNIDADES_FUNCIONALES3;


/* Formatted on 11/7/2014 5:49:31 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_TIME_N1_AÑOS
(
   SUBID_AÑO,
   NATID_AÑO,
   DESCR_AÑO,
   DESCR_AÑO_ROMANO,
   SUBID_AÑO_ANTERIOR,
   DURACION_AÑO
)
AS
   SELECT "SUBID_AÑO",
          "NATID_AÑO",
          "DESCR_AÑO",
          "DESCR_AÑO_ROMANO",
          "SUBID_AÑO_ANTERIOR",
          "DURACION_AÑO"
     FROM MSTR_HOSPITALIZACION.MSTR_TIME_N1_AÑOS;


/* Formatted on 11/7/2014 5:49:31 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_TIME_N2_MESES
(
   SUBID_MES,
   NATID_MES,
   DESCR_MES,
   DESCR_MES_ES,
   DESCR_MES_SORT,
   MES_DEL_AÑO,
   DESCR_MES_DEL_AÑO,
   DESCR_MES_DEL_AÑO_ES,
   NATID_ULTIMO_DIA_DEL_MES,
   SUBID_AÑO,
   SUBID_TRIMESTRE,
   SUBID_MES_ANTERIOR,
   SUBID_MES_TRIMESTRE_ANTERIOR,
   SUBID_MISMO_MES_AÑO_ANTERIOR,
   DURACION_MES
)
AS
   SELECT "SUBID_MES",
          "NATID_MES",
          "DESCR_MES",
          "DESCR_MES_ES",
          "DESCR_MES_SORT",
          "MES_DEL_AÑO",
          "DESCR_MES_DEL_AÑO",
          "DESCR_MES_DEL_AÑO_ES",
          "NATID_ULTIMO_DIA_DEL_MES",
          "SUBID_AÑO",
          "SUBID_TRIMESTRE",
          "SUBID_MES_ANTERIOR",
          "SUBID_MES_TRIMESTRE_ANTERIOR",
          "SUBID_MISMO_MES_AÑO_ANTERIOR",
          "DURACION_MES"
     FROM MSTR_HOSPITALIZACION.MSTR_TIME_N2_MESES;


/* Formatted on 11/7/2014 5:49:31 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_TIME_N3_DIAS
(
   SUBID_DIA,
   NATID_DIA,
   DESCR_DIA,
   DESCR_DIA_ES,
   DIA_DE_LA_SEMANA,
   SUBID_SEMANA,
   SUBID_MES,
   SUBID_TRIMESTRE,
   SUBID_AÑO,
   NATID_DIA_ANTERIOR,
   SUBID_MISMO_DIA_MES_ANTERIOR,
   SUBID_MISMO_DIA_TRIMESTRE_ANTE,
   SUBID_MISMO_DIA_AÑO_ANTERIOR
)
AS
   SELECT "SUBID_DIA",
          "NATID_DIA",
          "DESCR_DIA",
          "DESCR_DIA_ES",
          "DIA_DE_LA_SEMANA",
          "SUBID_SEMANA",
          "SUBID_MES",
          "SUBID_TRIMESTRE",
          "SUBID_AÑO",
          "NATID_DIA_ANTERIOR",
          "SUBID_MISMO_DIA_MES_ANTERIOR",
          "SUBID_MISMO_DIA_TRIMESTRE_ANTE",
          "SUBID_MISMO_DIA_AÑO_ANTERIOR"
     FROM MSTR_HOSPITALIZACION.MSTR_TIME_N3_DIAS;
