CREATE MATERIALIZED VIEW ADM_PREINGRESO_DET
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS
SELECT *
  FROM "HIS_OWN"."ADM_PREINGRESO_DET"@REP_DAE_RND.SAS "ADM_PREINGRESO_DET"
  WHERE "ADM_PREINGRESO_DET"."PREINGRESO" IN 
  (SELECT ADM_PREINGRESO.PREINGRESO_ID FROM HIS_RND.ADM_PREINGRESO)