CREATE MATERIALIZED VIEW ADM_PREINGRESO
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS
SELECT *
  FROM "HIS_OWN"."ADM_PREINGRESO"@REP_DAE_RND.SAS "ADM_PREINGRESO"
  WHERE "ADM_PREINGRESO"."FECHA_PREV_ING" >= ADD_MONTHS (TRUNC (SYSDATE, 'year'), -12);