/* Formatted on 27/05/2013 14:33:04 (QP5 v5.163.1008.3004) */
DROP TABLE EXT_INFHOS_TXT_V2;

         CREATE TABLE EXT_INFHOS_TXT_V2
(
  CODIGO_CITA             VARCHAR2(30 BYTE),
  CODIGO_SOLICITUD        VARCHAR2(30 BYTE),
  AREA_H                  VARCHAR2(30 BYTE),
  CODIGO_CENTRO           VARCHAR2(30 BYTE),
  NUHSA                   VARCHAR2(30 BYTE),
  ESPECIALIDAD            VARCHAR2(30 BYTE),
  PROCEDENCIA             VARCHAR2(30 BYTE),
  TIPO_CITA               VARCHAR2(30 BYTE),
  PRUEBA                  VARCHAR2(30 BYTE),
  FECHASOLIC              VARCHAR2(30 BYTE),
  FECHACITA               VARCHAR2(30 BYTE),
  ESTADOCITA              VARCHAR2(30 BYTE),
  CENTRO_SOLICITANTE      VARCHAR2(30 BYTE),
  UNIDAD_SOLICITANTE      VARCHAR2(30 BYTE),
  CNP_PROF_SOLICITANTE    VARCHAR2(30 BYTE),
  SUJETA_GARANTIA         VARCHAR2(30 BYTE),
  FECHA_INDIC_PROFE       VARCHAR2(30 BYTE),
  FECHA_DESE_USUARIO      VARCHAR2(30 BYTE),
  MOTIVO_DEMANDA          VARCHAR2(30 BYTE),
  CIE9                    VARCHAR2(30 BYTE),
  FECHA_DISP_CLINICA      VARCHAR2(30 BYTE),
  FECHA_PRESENTACION      VARCHAR2(30 BYTE),
  UNIDAD_REALIZACION      VARCHAR2(30 BYTE),
  AGENDA_REALIZACION      VARCHAR2(30 BYTE),
  CLAVE_MEDICA            VARCHAR2(30 BYTE),
  DISTRITO                VARCHAR2(30 BYTE),
  FECHA_REGISTRO          VARCHAR2(30 BYTE),
  LIBRE_ELECCION          VARCHAR2(30 BYTE),
  PROCESO_ASIST           VARCHAR2(30 BYTE),
  EN_PLAZO                VARCHAR2(30 BYTE),
  INSC_REGISTRO           VARCHAR2(30 BYTE),
  EPISODIO_ADMIN          VARCHAR2(30 BYTE),
  TIPO_FINAN              VARCHAR2(30 BYTE),
  FECHA_ACREDIT           VARCHAR2(30 BYTE),
  ESTADO_SOLICITUD        VARCHAR2(30 BYTE),
  FECHAGRABACION          VARCHAR2(30 BYTE),
  TAREA                   VARCHAR2(30 BYTE),
  TAREA_PPAL              VARCHAR2(30 BYTE),
  AGE_NOMBRE              VARCHAR2(100 BYTE),
  SEXO                    VARCHAR2(30 BYTE),
  FECHA_NACIMIENTO        VARCHAR2(30 BYTE),
  CNP_PROF_REALIZA        VARCHAR2(30 BYTE),
  TIPO_PROCESO_ASIST            VARCHAR2(30 BYTE),
  ACT_CODIGO              VARCHAR2(30 BYTE),
  HORA_CITA               VARCHAR2(30 BYTE),
  MODELO_ACTUACION        VARCHAR2(30 BYTE),
  TIPO_ASISTENCIA_ORIGEN  VARCHAR2(30 BYTE),
  TIPO_ASISTENCIA_DESTINO VARCHAR2(30 BYTE),
  F_INI_DEMORA VARCHAR2(30 BYTE),
  DEMORA VARCHAR2(30 BYTE),
  TAREA_DESCRIP           VARCHAR2(250 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY MSTR_CONSULTAS_INFHOS_FILES
     ACCESS PARAMETERS
       ( RECORDS DELIMITED BY NEWLINE
                CHARACTERSET 'WE8MSWIN1252'
       BADFILE MSTR_CONSULTAS_INFHOS_FILES:'infhos.bad'
       DISCARDFILE MSTR_CONSULTAS_INFHOS_FILES:'infhos.dsc'
       LOGFILE MSTR_CONSULTAS_INFHOS_FILES:'infhos.log'
       SKIP 1
       FIELDS TERMINATED BY '|'
       OPTIONALLY ENCLOSED BY '"' AND '"'
       MISSING FIELD VALUES ARE NULL
       REJECT ROWS WITH ALL NULL FIELDS
       (
         CODIGO_CITA CHAR,
         CODIGO_SOLICITUD CHAR,
         AREA_H CHAR,
         CODIGO_CENTRO CHAR,
         NUHSA CHAR,
         ESPECIALIDAD CHAR,
         PROCEDENCIA CHAR,
         TIPO_CITA CHAR,
         PRUEBA CHAR,
         FECHASOLIC CHAR,
         FECHACITA CHAR,
         ESTADOCITA CHAR,
         CENTRO_SOLICITANTE CHAR,
         UNIDAD_SOLICITANTE CHAR,
         CNP_PROF_SOLICITANTE CHAR,
         SUJETA_GARANTIA CHAR,
         FECHA_INDIC_PROFE CHAR,
         FECHA_DESE_USUARIO CHAR,
         MOTIVO_DEMANDA CHAR,
         CIE9 CHAR,
         FECHA_DISP_CLINICA CHAR,
         FECHA_PRESENTACION CHAR,
         UNIDAD_REALIZACION CHAR,
         AGENDA_REALIZACION CHAR,
         CLAVE_MEDICA CHAR,
         DISTRITO CHAR,
         FECHA_REGISTRO CHAR,
         LIBRE_ELECCION CHAR,
         PROCESO_ASIST CHAR,
         EN_PLAZO CHAR,
         INSC_REGISTRO CHAR,
         EPISODIO_ADMIN CHAR,
         TIPO_FINAN CHAR,
         FECHA_ACREDIT CHAR,
         ESTADO_SOLICITUD CHAR,
         FECHAGRABACION CHAR,
         TAREA CHAR,
         TAREA_PPAL CHAR,
         AGE_NOMBRE CHAR,
         SEXO CHAR,
         FECHA_NACIMIENTO CHAR,
         CNP_PROF_REALIZA CHAR,
         TIPO_PROCESO_ASIST CHAR,
         ACT_CODIGO CHAR,
         HORA_CITA CHAR,
         MODELO_ACTUACION CHAR,
         TIPO_ASISTENCIA_ORIGEN CHAR,
         TIPO_ASISTENCIA_DESTINO CHAR,
         F_INI_DEMORA  CHAR,
         DEMORA  CHAR,
         TAREA_DESCRIP CHAR
       )  )
     LOCATION (MSTR_CONSULTAS_INFHOS_FILES:'infhos.txt')
  )
REJECT LIMIT UNLIMITED;