CREATE MATERIALIZED VIEW MSTR_MAE_UBICACIONES_URGENCIAS (L,UBI_IDENTIFICADOR,UBI_NOMBRE,UBI_DESCRIPCION,UBI_ACTIVO,UBI_PADRE,UBI_OCUPADO,UBI_ICONO,UBI_DESCORTA,UBI_SERVESP,UBI_GENERATRANSA,UBI_NOMBRETRANSA,UBI_ADMISION,UBI_TRAN_OCUPADA,UBI_UBICACIONES_DEP,UBI_TIP_UBICACION,UBI_TELEFONO,UBI_ESPEC,UBI_CENTRO)
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 20/03/2013 11:33:22 (QP5 v5.163.1008.3004) */
    SELECT LEVEL L,
           UBI_IDENTIFICADOR,
           UBI_NOMBRE,
           UBI_DESCRIPCION,
           UBI_ACTIVO,
           UBI_PADRE,
           UBI_OCUPADO,
           UBI_ICONO,
           UBI_DESCORTA,
           UBI_SERVESP,
           UBI_GENERATRANSA,
           UBI_NOMBRETRANSA,
           UBI_ADMISION,
           UBI_TRAN_OCUPADA,
           UBI_UBICACIONES_DEP,
           UBI_TIP_UBICACION,
           UBI_TELEFONO,
           UBI_ESPEC,
           UBI_CENTRO
      FROM CAE_OWN.UBICACIONES_URGENCIAS@DAE
START WITH UBI_IDENTIFICADOR = '23729'
CONNECT BY UBI_PADRE = PRIOR UBI_IDENTIFICADOR AND UBI_ACTIVO = 1                                       --AND UBI_CENTRO = '10004';
/