/* Formatted on 31/05/2013 10:03:07 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_ESTADOS_HOJA_QUIRUR
(
   IND_PROVISIONAL,
   DESCR_PROVISIONAL
)
AS
   SELECT 0 IND_PROVISIONAL, 'Provisional' DESCR_PROVISIONAL FROM DUAL
   UNION ALL
   SELECT 1 IND_PROVISIONAL, 'Definitiva' DESCR_PROVISIONAL FROM DUAL
      UNION ALL
   SELECT 2 IND_PROVISIONAL, 'Naranja' DESCR_PROVISIONAL FROM DUAL;
