/* Formatted on 07/05/2013 13:51:55 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_SITUACIONES_GARANTIA
--(
--   SITGAR_CODIGO,
--   SITGAR_CORTO,
--   SITGAR_NOMBRE,
--   SITGAR_SITUACION,
--   TIPSG_CODIGO
--)
AS
   SELECT SITGAR_CODIGO NATID_SITUACION_GARANTIA,
          SITGAR_NOMBRE DESCR_SITUACION_GARANTIA,
          SITGAR_CORTO ABREV_SITUACION_GARANTIA,
          SITGAR_SITUACION IND_SITUACION,
          TIPSG_CODIGO NATID_TIPSG
     FROM REP_PRO_AGD.SITUACIONES_GARANTIA@VAL;
