/* Formatted on 17/05/2013 9:39:59 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_UNIDADES_FUNCIONALES
(
   NATID_UNIDAD_FUNCIONAL3,
   DESCR_UNIDAD_FUNCIONAL3,
   NATID_UNIDAD_FUNCIONAL2
)
AS
   SELECT '-1' NATID_UNIDAD_FUNCIONAL3, 'n/a' DESCR_UNIDAD_FUNCIONAL3, '-1' NATID_UNIDAD_FUNCIONAL2 FROM DUAL
   UNION ALL
   SELECT UF_CODIGO NATID_UNIDAD_FUNCIONAL3, UF_NOMBRE DESCR_UNIDAD_FUNCIONAL3, UF_UF_CODIGO NATID_UNIDAD_FUNCIONAL2
     FROM REP_PRO_EST.UNIDADES_FUNCIONALES@VAL
    WHERE UF_UF_CODIGO IN (SELECT UF_CODIGO
                             FROM REP_PRO_EST.UNIDADES_FUNCIONALES@VAL
                            WHERE UF_UF_CODIGO IN (SELECT UF_CODIGO
                                                     FROM REP_PRO_EST.UNIDADES_FUNCIONALES@VAL
                                                    WHERE UF_UF_CODIGO IS NULL /*AND UF_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_CODIGOS)*/
                                                                              ))
   UNION ALL
   SELECT UF_CODIGO NATID_UNIDAD_FUNCIONAL3, UF_NOMBRE DESCR_UNIDAD_FUNCIONAL3, UF_CODIGO NATID_UNIDAD_FUNCIONAL2
     FROM REP_PRO_EST.UNIDADES_FUNCIONALES@VAL
    WHERE UF_UF_CODIGO IS NULL                      /*AND UF_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_CODIGOS)*/
                              AND UF_FINAL = 'S'
   UNION ALL
   SELECT UF_CODIGO NATID_UNIDAD_FUNCIONAL3, UF_NOMBRE DESCR_UNIDAD_FUNCIONAL3, UF_CODIGO NATID_UNIDAD_FUNCIONAL2
     FROM REP_PRO_EST.UNIDADES_FUNCIONALES@VAL
    WHERE UF_UF_CODIGO IN (SELECT UF_CODIGO
                             FROM REP_PRO_EST.UNIDADES_FUNCIONALES@VAL
                            WHERE UF_UF_CODIGO IS NULL /*AND UF_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_CODIGOS)*/
                                                      )
          AND UF_FINAL = 'S';
