/* Formatted on 7/3/2012 11:08:06 AM (QP5 v5.163.1008.3004) */
DROP MATERIALIZED VIEW MSTR_DET_URGENCIAS_ULTIM2MESES;

CREATE MATERIALIZED VIEW MSTR_DET_URGENCIAS_ULTIM2MESES (AU_USUARIO,USU_IDENTIFICADOR,USU_BDU_NUSA,AU_OPERADOR,AU_FECHA,AU_COD_PROCEDENCIA_URG,AU_COD_TIPO_PROCESO_URG,AU_EPISODIO,AU_FECHASALIDA,AU_FINANCIACION,EU_FHCREACION,EU_PRIORIDAD,EU_INFORMEALTA,EU_COD_CAUSA_ALTA_URG,EU_OPERADOR_FIRMA_ALTA,EU_FHALTA,EU_LUGAR_COD,EU_LUGAR_TXT,EUE_IDENTIFICADOR,UBICACION)
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS

SELECT AU_USUARIO,
       USU_IDENTIFICADOR,
       USU_BDU_NUSA,
       AU_OPERADOR,
       AU_FECHA,
       AU_COD_PROCEDENCIA_URG,
       AU_COD_TIPO_PROCESO_URG,
       AU_EPISODIO,
       AU_FECHASALIDA,
       AU_FINANCIACION,
       EU_FHCREACION,
       EU_PRIORIDAD,
       EU_INFORMEALTA,
       EU_COD_CAUSA_ALTA_URG,
       EU_OPERADOR_FIRMA_ALTA,
       EU_FHALTA,
       EU_LUGAR_COD,
       EU_LUGAR_TXT,
       MAX_ESTADO.EUE_IDENTIFICADOR,
       EUE_UBICACION UBICACION
  FROM CAE_OWN.ADMISION
       JOIN CAE_OWN.EPISODIO_URGENCIAS
          ON (AU_EPISODIO = EU_IDENTIFICADOR)
       JOIN (  SELECT EUE_EPISODIO, MAX (EUE_IDENTIFICADOR) EUE_IDENTIFICADOR
                 FROM CAE_OWN.ESTADOS_EPISODIO_URG
             GROUP BY EUE_EPISODIO) MAX_ESTADO
          ON (AU_EPISODIO = MAX_ESTADO.EUE_EPISODIO)
       JOIN CAE_OWN.ESTADOS_EPISODIO_URG ESTADOS
          ON (MAX_ESTADO.EUE_IDENTIFICADOR = ESTADOS.EUE_IDENTIFICADOR)
        JOIN CAE_OWN.USUARIO
          ON (AU_USUARIO = USU_ID)
 WHERE TRUNC (AU_FECHA) BETWEEN (ADD_MONTHS (TRUNC (SYSDATE, 'MONTH'), -1)) AND (TRUNC (SYSDATE) - 1);

COMMENT ON MATERIALIZED VIEW MSTR_DET_URGENCIAS_ULTIM2MESES IS
   'snapshot table for snapshot HIS_RND.MSTR_DET_URGENCIAS_ULTIM2MESES';