SELECT 
NATID_PROCEDIMIENTO_CMA, DESCR_PROCEDIMIENTO_CMA, NATID_AÑO_CMA, 
   NATID_GRUPO_CCS
FROM MSTR_MAE_PROCEDIMIENTOS_CMA;

UPDATE MSTR_MAE_PROCEDIMIENTOS_CMA
SET NATID_AÑO_CMA = TO_DATE('01/01/2012');