/* Formatted on 07/05/2013 12:52:06 (QP5 v5.163.1008.3004) */
DROP TABLE MSTR_DET_LISTA_ESPERA_QUIRUR;

CREATE TABLE MSTR_DET_LISTA_ESPERA_QUIRUR
(
   NATID_CODIGO_RDQ               NUMBER NOT NULL,
   NUHSA                    VARCHAR2 (36 BYTE) NOT NULL,
   --NATID_HISTORIA_CLINICA          NUMBER,
   GEO_CODIGO_POSTAL            VARCHAR2 (10),
   NATID_ESPECIALIDAD                NUMBER (5),
   NATID_FECHA_ALTA              DATE,
   NATID_FECHA_MECANIZACION      DATE,
   NATID_FECHA_BAJA              DATE,
   NATID_FECHA_FACULTATIVO       DATE NOT NULL,
   NATID_CNP_FACULTATIVO_RESP     NUMBER (13),
   NATID_SITUACION_PACIENTE     NUMBER NOT NULL,
   NATID_SITUACION_GARANTIA            NUMBER (2),
   NATID_MOTIVO_BAJA            NUMBER (2),
   NATID_PROCEDIMIENTO               VARCHAR2 (30 BYTE) NOT NULL,
   NATID_DIAGNOSTICO                VARCHAR2 (30 BYTE),
   IND_TIPO_CIRURGIA            NUMBER (2),
   NATID_UNIDAD_FUNCIONAL_ALTA           VARCHAR2 (18 BYTE),
   NATID_UNIDAD_FUNCIONAL_INTERVE   VARCHAR2 (18 BYTE),
   --AH_CODIGO_ALTA           NUMBER (5),
   --AH_CODIGO_RESPONSABLE    NUMBER,
   --AH_CODIGO_INTERVENCION   NUMBER (5),
   --AH_CODIGO_OFERTA         NUMBER,
   NATID_CENTRO_ALTA           NUMBER (5) NOT NULL,
   --NATID_CENTRO_RESPONSABLE    NUMBER (5) NOT NULL,
   NATID_CENTRO_INTERVENCION   NUMBER (5),
   --CI_CODIGO_OFERTA         NUMBER,
   TIEMPO_REG           NUMBER (4),
   TIEMPO_GAR           NUMBER (4),
   NATID_FECHA_CUMPLE_GARANTIA      DATE,
   --IND_DAE                  VARCHAR2 (1 BYTE),
   NATID_SEMANA_CUMPLE_GARANTIA   DATE
);


ALTER TABLE MSTR_DET_LISTA_ESPERA_QUIRUR ADD (
  CONSTRAINT PK_LEQ
  PRIMARY KEY
  (NATID_CODIGO_RDQ)
  USING INDEX
);


CREATE INDEX LEQ_001
   ON MSTR_DET_LISTA_ESPERA_QUIRUR (NATID_ESPECIALIDAD);


CREATE INDEX LEQ_002
   ON MSTR_DET_LISTA_ESPERA_QUIRUR (NATID_SITUACION_PACIENTE);


CREATE INDEX LEQ_003
   ON MSTR_DET_LISTA_ESPERA_QUIRUR (NATID_MOTIVO_BAJA);


CREATE INDEX LEQ_004
   ON MSTR_DET_LISTA_ESPERA_QUIRUR (NATID_PROCEDIMIENTO);


CREATE INDEX LEQ_005
   ON MSTR_DET_LISTA_ESPERA_QUIRUR (NATID_UNIDAD_FUNCIONAL_ALTA);


CREATE INDEX LEQ_006
   ON MSTR_DET_LISTA_ESPERA_QUIRUR (NATID_UNIDAD_FUNCIONAL_INTERVE);

--
--CREATE INDEX LEQ_007
--   ON MSTR_DET_LISTA_ESPERA_QUIRUR (IND_DAE);