/* Formatted on 07/05/2013 13:54:38 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_SITUACIONES_PACIENTE
AS
   SELECT SITPAC_CODIGO NATID_SITUACION_PACIENTE,
          SITPAC_NOMBRE DESCR_SITUACION_PACIENTE,
          SITPAC_CORTO ABREV_SITUACION_PACIENTE,
          SITPAC_OBS NOTAS,
          SITPAC_SITUACION IND_SITUACION
     FROM REP_PRO_AGD.SITUACIONES_PACIENTES@VAL;
