/* Formatted on 20/03/2013 12:00:41 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_UBICACIONES_URGEN_L4
AS
   SELECT L,
          NATID_UBICACION_URGEN,
          DESCR_UBICACION_URGEN,
          NATID_UBICACION_URGEN_PADRE,
          IND_TIENE_DEPENDIENTES,
          NATID_TIPO_UBICACION,
          NATID_CENTRO
     FROM MSTR_MAE_UBICACIONES_URGEN
    WHERE L = 4
   UNION ALL
   SELECT 4,
          NATID_UBICACION_URGEN,
          DESCR_UBICACION_URGEN,
          NATID_UBICACION_URGEN_PADRE,
          IND_TIENE_DEPENDIENTES,
          NATID_TIPO_UBICACION,
          NATID_CENTRO
     FROM MSTR_MAE_UBICACIONES_URGEN
    WHERE L = 1
   UNION ALL
   SELECT 4,
          NATID_UBICACION_URGEN,
          DESCR_UBICACION_URGEN,
          NATID_UBICACION_URGEN_PADRE,
          IND_TIENE_DEPENDIENTES,
          NATID_TIPO_UBICACION,
          NATID_CENTRO
     FROM MSTR_MAE_UBICACIONES_URGEN
    WHERE L = 2
   UNION ALL
   SELECT 4,
          NATID_UBICACION_URGEN,
          DESCR_UBICACION_URGEN,
          NATID_UBICACION_URGEN_PADRE,
          IND_TIENE_DEPENDIENTES,
          NATID_TIPO_UBICACION,
          NATID_CENTRO
     FROM MSTR_MAE_UBICACIONES_URGEN
    WHERE L = 3;
