/* Formatted on 25/06/2013 17:11:23 (QP5 v5.163.1008.3004) */
DROP TABLE MSTR_MAE_EPISODIOS;

CREATE TABLE MSTR_MAE_EPISODIOS
NOLOGGING
PARALLEL
NOMONITORING
AS
   SELECT EPISODIO_ID NATID_EPISODIO,
          NUHSA,
          DES_MODAL_ASIST DESCR_MODALIDAD_ASISTENCIAL,
          DECODE (HD_QUIR_SN, 1, 'Quirúrgico', 'Médico') IND_QUIRURGICO,
          (FCH_APERTURA + (HORA_APERTURA - TRUNC (HORA_APERTURA))) NATID_FHORA_INICIO_EPISODIO,
          (FCH_CIERRE + (HORA_CIERRE - TRUNC (HORA_CIERRE))) NATID_FHORA_FIN_EPISODIO,
          ADMISION_ID NATID_ADMISION,
          (FCH_INGRESO + (HORA_INGRESO - TRUNC (HORA_INGRESO))) NATID_FHORA_INGRESO_ADMISION,
          (FCH_ALTA + (HORA_ALTA - TRUNC (HORA_ALTA))) NATID_FHORA_ALTA_ADMISION,
          CENTRO_INGRESO NATID_CENTRO_INGRESO,
          UNID_FUNC_INGRESO NATID_UNIDAD_FUNCIONAL_INGRESO
     --       DECODE (ADM_EPISODIO.MODALIDAD_ASIST,
     --               2, DES_MODAL_ASIST || ' ' || DECODE (HD_QUIR_SN, 1, 'Quirúrgico', 'Médico'),
     --               DES_MODAL_ASIST)
     --          TIPO
     --MSTR.FUNC_ENCRYPT_v2 (EPISODIO_ID) NATID_EPISODIO--,
     --MSTR.FUNC_ENCRYPT_v2 (NUHSA) NUHSA
     FROM REP_HIS_OWN.ADM_EPISODIO@EXP
          JOIN REP_HIS_OWN.COM_USUARIO@EXP
             ON (ADM_EPISODIO.USUARIO = ID_USUARIO)
          JOIN REP_HIS_OWN.ADM_EPIS_DETALLE@EXP
             USING (EPISODIO_ID)
          JOIN REP_HIS_OWN.ADM_ADMISION@EXP
             ON (REFERENCIA_ID = ADMISION_ID)
          JOIN REP_HIS_OWN.ADM_M_MODAL_ASIST@EXP
             ON (ADM_EPISODIO.MODALIDAD_ASIST = ADM_M_MODAL_ASIST.MODAL_ASIST_ID)
    --       JOIN REP_HIS_OWN.ADM_EPIS_DETALLE@EXP
    --          USING (EPISODIO_ID)
    WHERE FCH_APERTURA >= ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), -24) AND FCH_APERTURA <= ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), 12) --AND ADMISION_ID IS NULL
   UNION ALL
   SELECT -1 NATID_EPISODIO,
          'n/a' NUHSA,
          'n/a' DESCR_MODALIDAD_ASISTENCIAL,
          'n/a' IND_QUIRURGICO,
          NULL NATID_FHORA_INICIO_EPISODIO,
          NULL NATID_FHORA_FIN_EPISODIO,
          -1 NATID_ADMISION,
          NULL NATID_FHORA_INGRESO_ADMISION,
          NULL NATID_FHORA_ALTA_ADMISION,
          -1 NATID_CENTRO_INGRESO,
          '-1' NATID_UNIDAD_FUNCIONAL_INGRESO
     --       DECODE (ADM_EPISODIO.MODALIDAD_ASIST,
     --               2, DES_MODAL_ASIST || ' ' || DECODE (HD_QUIR_SN, 1, 'Quirúrgico', 'Médico'),
     --               DES_MODAL_ASIST)
     --          TIPO
     --MSTR.FUNC_ENCRYPT_v2 (EPISODIO_ID) NATID_EPISODIO--,
     --MSTR.FUNC_ENCRYPT_v2 (NUHSA) NUHSA
     FROM DUAL
--         AND EPISODIO_ID = 1178754
--ORDER BY ADMISION_ID
/

CREATE INDEX MSTR_MAE_EPISODIOS_IB01
   ON MSTR_MAE_EPISODIOS (DESCR_MODALIDAD_ASISTENCIAL)
   NOLOGGING
   PARALLEL;

CREATE INDEX MSTR_MAE_EPISODIOS_IB02
   ON MSTR_MAE_EPISODIOS (IND_QUIRURGICO)
   NOLOGGING
   PARALLEL;

CREATE INDEX MSTR_MAE_EPISODIOS_IX01
   ON MSTR_MAE_EPISODIOS (NUHSA)
   NOLOGGING
   PARALLEL;

CREATE INDEX MSTR_MAE_EPISODIOS_IX02
   ON MSTR_MAE_EPISODIOS (NATID_FHORA_INICIO_EPISODIO)
   NOLOGGING
   PARALLEL;

CREATE INDEX MSTR_MAE_EPISODIOS_IX03
   ON MSTR_MAE_EPISODIOS (NATID_FHORA_FIN_EPISODIO)
   NOLOGGING
   PARALLEL;

CREATE INDEX MSTR_MAE_EPISODIOS_IX04
   ON MSTR_MAE_EPISODIOS (NATID_FHORA_INGRESO_ADMISION)
   NOLOGGING
   PARALLEL;

CREATE INDEX MSTR_MAE_EPISODIOS_IX05
   ON MSTR_MAE_EPISODIOS (NATID_FHORA_ALTA_ADMISION)
   NOLOGGING
   PARALLEL;

ALTER TABLE MSTR_MAE_EPISODIOS ADD (
  CONSTRAINT MSTR_MAE_EPISODIOS_PK
  PRIMARY KEY
  (NATID_EPISODIO, NATID_ADMISION)
  USING INDEX
       NOLOGGING );

EXEC DBMS_STATS.gather_table_stats ('MSTR_QUIROFANO', 'MSTR_MAE_EPISODIOS');
--select count(EPISODIO_ID) FROM REP_HIS_OWN.ADM_EPISODIO@EXP;