/* Formatted on 09/05/2013 13:19:25 (QP5 v5.163.1008.3004) */
DROP MATERIALIZED VIEW MSTR_DET_PARTES_QUIRURGICOS;
CREATE MATERIALIZED VIEW MSTR_DET_PARTES_QUIRURGICOS (NATID_CENTRO,NATID_UNIDAD_FUNCIONAL,NATID_CABECERA_PARTE_QUIRU,NATID_DETALLE_PARTE_QUIRU,ORDEN_DETALLE_PARTE_QUIRU,NATID_TURNO_QUIROFANO,FHORA_INICIO_PARTE_QUIRU,FHORA_FIN_PARTE_QUIRU,ESTADO_PARTE_QUIRU,VALIDACION_PARTE_QUIRU,NATID_QUIROFANO,NATID_MOTIV_DESPROGRAMACION,NATID_POST_INTERVENCION,NATID_PRE_INTERVENCION,NATID_PREINGRESO,NATID_TIPO_PLANIFICACION,NATID_ADMISION,NATID_ANESTESIA,DURACION_PREVISTA_INTERVENCION,NATID_EPISODIO,NATID_ESTADO_INTERVENCION,NATID_PACIENTE,NUHSA,NATID_CODIGO_RDQ_PRE,IND_MAYOR_MENOR,NATID_MODAL_ASISTENCIALES,IND_QUIRURGICA,IND_URGENCIA_DIFERIDA,NATID_DIAGNOSTICO_CIE_PRE,TEXTO_DIAGNOSTICO_PRE,NATID_PROCEDIMIENTO_CIE_PRE,TEXTO_PROCEDIMIENTO_PRE, IND_DESPROGRAMACION, LAST_REFRESH_DATE)
--BUILD IMMEDIATE
--REFRESH FORCE ON DEMAND
--WITH PRIMARY KEY
AS
SELECT
NULL,NULL,-1,-1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL
FROM DUAL
UNION ALL
SELECT CENTRO_ID,
       UNI_FUNCIONAL_ID,
       PQ_CAB_ID,
       PQ_DET_ID,
       ORDEN,
       --NUHSA,
       TURNO_ID,
       FECHA_HORA_INICIO,
       FECHA_HORA_FIN,
       --FECHA_HORA_CIERRE,
       --CARAC_ECONOM_ID,
       ESTADO,
       --OPERADOR_ID,
       --OPERADOR_CIERRE_ID,
       --FECHA_HORA_REGISTRO,
       --HORA_REGISTRO,
       --ADM_QRF_PQ_CAB.ACTIVO PQ_CAB_ACTIVO,
       ESTADO_VALIDACION,
       QUIROFANO,
       --BLOQUE_PERIODICO_ID,
       --OPERADOR_VALIDACION,
       --FECHA_HORA_VALIDACION,
       --FH_PRIMER_CIERRE
       --PQ_CAB_ID,
       --CARAC_ECONOM_ID_PRE,
       --ESTADO_ID_PRE,
       --FH_REGISTRO_IQ_POST,
       --FH_REGISTRO_IQ_PRE,
       --HORA_REGISTRO_IQ_POST,
       --HORA_REGISTRO_IQ_PRE,
       MOT_DESPROG_ID,
       IQ_POST_ID,
       IQ_PRE_ID,
       --OPERADOR_POST_ID,
       --OPERADOR_PRE_ID,
       PREING_DET_ID,
       --QUIROFANO_ID_PRE,
       --RESERVA_SN_PRE,
       TPLANIFICAC_PRE_ID,
       --IQ_PRE_ID,
       --ADM_QRF_IQ_PRE.ACTIVO IQ_PRE_ACTIVO,
       ADMISION_ID,
       ANESTESIA_ID,
       --CANT_BS,
       --COD_ADM_QRF_IQ_ANESTESIA_PRE,
       --CUIDADOS_POST,
       DURACION_PREVISTA,
       --ENVIO_MSG,
       --EPIS_EXTERNO,
       NVL (EPISODIO_ID, -1),
       ESTADO_ID,
       --FH_PREVISTA_PREINGRESO,
       ADM_QRF_IQ_PRE.ID_USUARIO,
       NUHSA,
       RDQ_CODIGO,
       --IQ_MOTIVO_ID,
       IQ_TIPO_ID,
       MODAL_ASIST_ID,
       --OBSERVACIONES,
       QUIRURGICA,
       TIPO_PROGRAMACION,
       DIAGN_PRINC.CODIGO_ICD9 DIAGN_PRINC_ICD9,
       DIAGN_PRINC.TEXTO_LIBRE DIAGN_PRINC_DESCR,
       PROCE_PRINC.CODIGO_PROC PROCE_PRINC_ICD9,
       PROCE_PRINC.TEXTO_LIBRE PROCE_PRINC_DESCR,
       DECODE (IQ_DESPR_ID, NULL, 0, 1) IND_DESPROGRAMACION,
       LAST_REFRESH_DATE
  FROM REP_HIS_OWN.ADM_QRF_PQ_CAB@EXP
       JOIN REP_HIS_OWN.ADM_QRF_PQ_DET@EXP
          USING (PQ_CAB_ID)
       JOIN REP_HIS_OWN.ADM_QRF_IQ_PRE@EXP
          USING (IQ_PRE_ID)
       JOIN (SELECT IQ_PRE_ID, CODIGO_ICD9, TEXTO_LIBRE
               FROM REP_HIS_OWN.ADM_QRF_IQ_ICD_PRE@EXP
              WHERE DIAGN_PROCE = 'D' AND PRINCIPAL = 1) DIAGN_PRINC
          USING (IQ_PRE_ID)
       JOIN (SELECT IQ_PRE_ID, CODIGO_PROC, TEXTO_LIBRE
               FROM REP_HIS_OWN.ADM_QRF_IQ_ICD_PRE@EXP
              WHERE DIAGN_PROCE = 'P' AND PRINCIPAL = 1) PROCE_PRINC
          USING (IQ_PRE_ID)
       LEFT JOIN REP_HIS_OWN.ADM_QRF_IQ_DESPR@EXP
          USING (IQ_DESPR_ID, IQ_PRE_ID)
       LEFT JOIN REP_HIS_OWN.ADM_QRF_IQ_X_LEQ@EXP
          USING (IQ_PRE_ID)
         JOIN REP_HIS_OWN.COM_USUARIO@EXP
            ON (ADM_QRF_IQ_PRE.ID_USUARIO = COM_USUARIO.ID_USUARIO)
      CROSS JOIN (SELECT last_refresh_date
                     FROM sys.all_mviews@EXP
                    WHERE mview_name = 'ADM_QRF_PQ_CAB')
 WHERE FECHA_HORA_INICIO >= ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), -12)
       AND FECHA_HORA_INICIO <= ADD_MONTHS (TRUNC (SYSDATE, 'YEAR'), 12)
--ORDER BY FECHA_HORA_INICIO DESC;

--COMMENT ON MATERIALIZED VIEW MSTR_DET_PARTES_QUIRURGICOS IS 'snapshot table for snapshot MSTR_QUIROFANO.MSTR_DET_PARTES_QUIRURGICOS';;
/
--COMMENT ON MATERIALIZED VIEW MSTR_DET_PARTES_QUIRURGICOS IS 'snapshot table for snapshot MSTR_QUIROFANO.MSTR_DET_PARTES_QUIRURGICOS';

CREATE INDEX IX01_PARTES_UNIDAD_FUNCIONAL
   ON MSTR_DET_PARTES_QUIRURGICOS (NATID_UNIDAD_FUNCIONAL)
   LOGGING
   NOPARALLEL;

CREATE INDEX IX02_PARTES_FECHA_PARTE
   ON MSTR_DET_PARTES_QUIRURGICOS (FHORA_INICIO_PARTE_QUIRU)
   LOGGING
   NOPARALLEL;

CREATE INDEX IX03_PARTES_QUIROFANO
   ON MSTR_DET_PARTES_QUIRURGICOS (NATID_QUIROFANO)
   LOGGING
   NOPARALLEL;

CREATE UNIQUE INDEX MSTR_DET_PARTES_QUIRURGICOS_PK
   ON MSTR_DET_PARTES_QUIRURGICOS (NATID_DETALLE_PARTE_QUIRU)
   LOGGING
   NOPARALLEL;