/* Formatted on 07/05/2013 14:01:32 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_DIAGNOSTICOS_CIE
AS
   SELECT CODIGO NATID_DIAGNOSTICO,
       NVL (SUBSTR (CODIGO, 1, INSTR (CODIGO, '.') - 1), CODIGO) NATID_RAIZ_DIAGNOSTICO,
       DESCRIPCION DESC_DIAGNOSTICO
  FROM REP_SIDCA_OWN.HCE_MA_CIE9@EXP;
