/* Formatted on 03/05/2013 12:05:36 (QP5 v5.163.1008.3004) */
DROP MATERIALIZED VIEW MSTR_DET_CAMAS_DEL_DIA;

CREATE  MATERIALIZED VIEW MSTR_DET_CAMAS_DEL_DIA
AS
SELECT TRUNC (SYSDATE) NATID_FECHA,
       UBI_CODIGO NATID_CAMA,
       UBI_NOMBRE DESCR_CAMA,
       UBI_DESCRIPCION LDESC_CAMA,
       --          TUBI_DESCRIPCION NO_ME_MIRE,
       NVL (COM_M_TIPO_AISLAMIENTO.NOMBRE, -1) DESCR_TIPO_AISLAMIENTO,
       EPISODIO_ID NATID_EPISODIO,
       ID_USUARIO NATID_USUARIO,
       NUHSA NATID_NUHSA,
       DOM_CP GEO_CODIGO_POSTAL,
       UNID_FUNC_RESP NATID_UNIDAD_FUNCIONAL3_RESP,
       --CASE WHEN EPISODIO_ID IS NULL THEN NULL ELSE -1 END IND_ECTOPICO,
       FUNC_MARCA_SI_ES_ECTOPICO(UBI_CODIGO, UNID_FUNC_RESP, USUARIO) IND_ECTOPICO,
       --DECODE(EPISODIO_ID,  not NULL, 0)
       COM_UBICACION_GESTION_LOCAL.ESTADO NATID_ESTADO,
       ACTIVA IND_HABILITADA,
       UBI_TIP_UBICACION NATID_TIPO_CAMA,
       NVL (UBI_CAH_CODIGO, -1) NATID_CENTRO,
       NVL (UNIDAD_FUNCIONAL, -1) NATID_UNIDAD_FUNCIONAL3,
       NVL (func_recupera_contr_enfermeria (UBI_CODIGO), '-1') NATID_CONTROL_ENFERMERIA,
       LAST_REFRESH_DATE
  FROM REP_HIS_OWN.COM_UBICACION_GESTION_LOCAL@EXP
       JOIN REP_PRO_ESP.UBICACIONES@VAL
          ON (CODIGO_ESTRUCTURA = UBI_CODIGO)
       JOIN REP_PRO_ESP.TIPOS_UBICACION@VAL
          ON (UBI_TIP_UBICACION = TUBI_CODIGO)
       LEFT JOIN REP_HIS_OWN.COM_M_TIPO_AISLAMIENTO@EXP
          ON (TIPO_AISLAMIENTO = CODIGO)
       CROSS JOIN (SELECT last_refresh_date
                     FROM sys.all_mviews@EXP
                    WHERE mview_name = 'COM_UBICACION_GESTION_LOCAL')
       LEFT JOIN REP_HIS_OWN.ADM_EPIS_DETALLE@EXP
          USING (EPISODIO_ID)
       LEFT JOIN REP_HIS_OWN.ADM_ADMISION@EXP
          ON (REFERENCIA_ID = ADMISION_ID)
       LEFT JOIN REP_HIS_OWN.COM_USUARIO@EXP
          ON (USUARIO = ID_USUARIO)
 WHERE ACTIVA = 1 AND UBI_ACTIVO = 0 AND UBI_CAH_CODIGO IN (SELECT NATID_CENTRO FROM MSTR_MAE_CENTROS);

/

ALTER TABLE MSTR_HOSPITALIZACION.MSTR_DET_CAMAS_DEL_DIA ADD
CONSTRAINT MSTR_DET_CAMAS_DEL_DIA_PK
 PRIMARY KEY (NATID_CAMA);