/* Formatted on 11/06/2013 8:24:48 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_CAMAS
(
   NATID_CAMA,
   DESCR_CAMA,
   LDESC_CAMA,
   DESCR_TIPO_AISLAMIENTO,
   NATID_CENTRO,
   NATID_CONTROL_ENFERMERIA,
   NATID_UNIDAD_FUNCIONAL3,
   NATID_TIPO_CAMA,
   NATID_ESTADO,
   IND_HABILITADA
)
AS
   SELECT                                                                                         /*TRUNC (SYSDATE) NATID_FECHA,*/
         NATID_CAMA,
          DESCR_CAMA,
          LDESC_CAMA,
          DESCR_TIPO_AISLAMIENTO,
          NATID_CENTRO,
          NATID_CONTROL_ENFERMERIA,
          NATID_UNIDAD_FUNCIONAL3,
          NATID_TIPO_CAMA,
          NATID_ESTADO,
          IND_HABILITADA
     --TUBI_DESCRIPCION DESCR_TIPO_CAMA,
     /*,
         TUBI_DESCRIPCION NO_ME_MIRE,*/
     /*COM_M_TIPO_AISLAMIENTO.NOMBRE DESCR_TIPO_AISLAMIENTO,*/
     /*EPISODIO_ID NATID_EPISODIO,*/
     /*LAST_REFRESH_DATE*/
     FROM MSTR_DET_CAMAS_DEL_DIA
    --          JOIN REP_PRO_ESP.TIPOS_UBICACION@VAL
    --             ON (UBI_TIP_UBICACION = TUBI_CODIGO)
    --          LEFT JOIN REP_HIS_OWN.COM_M_TIPO_AISLAMIENTO@EXP
    --             ON (TIPO_AISLAMIENTO = CODIGO)
    --          CROSS JOIN (SELECT last_refresh_date
    --                        FROM sys.all_mviews@EXP
    --                       WHERE mview_name = 'COM_UBICACION_GESTION_LOCAL')
    -- CROSS JOIN (select NATID_CONTROL_ENFERMERIA
    --from MSTR_MAE_CONTROLES_ENFERMERIA
--    WHERE TRUNC (NATID_FECHA) = TRUNC (SYSDATE - 1)
-- WHERE ACTIVA = 1 AND UBI_ACTIVO = 0;
;
