create user MSTR_URGENCIAS identified by "ThinkpadT431swithWindows8";
grant connect, resource to MSTR_URGENCIAS;
grant create materialized view to MSTR_URGENCIAS;
grant create  view to MSTR_URGENCIAS;
GRANT "TC_ADMIN_ROLE" TO MSTR_URGENCIAS;
GRANT "TC_LDR_ROLE" TO MSTR_URGENCIAS;
GRANT "TC_MGR_ROLE" TO MSTR_URGENCIAS;
ALTER USER MSTR_URGENCIAS DEFAULT ROLE "CONNECT", "RESOURCE", "TC_ADMIN_ROLE", "TC_LDR_ROLE", "TC_MGR_ROLE";


