/* Formatted on 20/03/2013 11:40:43 (QP5 v5.163.1008.3004) */
--
CREATE MATERIALIZED VIEW MSTR_MAE_UBICACIONES_URGEN
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS
WITH UBICACION AS
(SELECT NATID_UBICACION_URGENCIAS_ROOT  INICIO FROM MSTR_UTL_CODIGOS)
    SELECT LEVEL L,
           UBI_IDENTIFICADOR NATID_UBICACION_URGEN,
           UBI_NOMBRE DESCR_UBICACION_URGEN,
           --UBI_DESCRIPCION LDESC_UBICACION_URGENCIAS,
           --UBI_ACTIVO,
           UBI_PADRE NATID_UBICACION_URGEN_PADRE,
           UBI_OCUPADO IND_OCUPADO,
           UBI_ICONO IND_TIPO,
           --UBI_DESCORTA,
           --UBI_SERVESP,
           --UBI_GENERATRANSA,
           --UBI_NOMBRETRANSA,
           --UBI_ADMISION,
           --UBI_TRAN_OCUPADA,
           UBI_UBICACIONES_DEP IND_TIENE_DEPENDIENTES,
           UBI_TIP_UBICACION NATID_TIPO_UBICACION,
           --UBI_TELEFONO,
           --UBI_ESPEC,
           UBI_CENTRO NATID_CENTRO
      FROM CAE_OWN.UBICACIONES_URGENCIAS@DAE, UBICACION
START WITH UBI_IDENTIFICADOR = UBICACION.INICIO
--START WITH UBI_IDENTIFICADOR = '23729'
CONNECT BY UBI_PADRE = PRIOR UBI_IDENTIFICADOR AND UBI_ACTIVO = 1                                     --AND UBI_CENTRO = '10004';;