/* Formatted on 07/05/2013 13:50:46 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_PROCEDIMIENTOS
AS
   SELECT PRC_CODIGO NATID_PROCEDIMIENTO,
          PRC_GAR IND_GARANTIA,
          PRC_GRUPO NATID_GRUPO,
          --GG_CODIGO,
          --PRC_GRUPO_CONC,
          --PRC_GRUPO_LE,
          PRC_NOMBRE DESCR_PROCEDIMIENTO,
          PRC_RDQ IND_RDQ,
          --PRC_SITUACION,
          PRC_TIEMPO_GAR TIEMPO_GARANTIA
     FROM REP_PRO_AGD.PROCEDIMIENTOS@VAL
    WHERE PRC_SITUACION = 0;