exec DBMS_STATS.GATHER_SCHEMA_STATS('MSTR_CONSULTAS');
exec DBMS_STATS.GATHER_SCHEMA_STATS('MSTR_HOSPITALIZACION'); 
exec DBMS_STATS.GATHER_SCHEMA_STATS('MSTR_QUIROFANO'); 
exec DBMS_STATS.GATHER_SCHEMA_STATS('MSTR_LISTA_DE_ESPERA');  