CREATE OR REPLACE VIEW ZOOM_DET_HISTORICO_CAMAS/* Formatted on 05/09/2013 15:44:50 (QP5 v5.163.1008.3004) */
AS
SELECT 
--NATID_FECHA,
--       NATID_CAMA,
       DESCR_CAMA,
       LDESC_CAMA,
--       DESCR_TIPO_AISLAMIENTO,
--       NATID_EPISODIO,
--       NATID_USUARIO,
--       NATID_NUHSA,
--       GEO_CODIGO_POSTAL,
--       NATID_UNIDAD_FUNCIONAL3_RESP,
--       IND_ECTOPICO,
--       NATID_ESTADO,
--       IND_HABILITADA,
--       NATID_TIPO_CAMA,
       DESCR_CENTRO,
       DESCR_UNIDAD_FUNCIONAL3,
       NATID_CONTROL_ENFERMERIA,
       LAST_REFRESH_DATE,
       IND_ECTOPICO_UF
  FROM MSTR_DET_HISTORICO_CAMAS JOIN MSTR_MAE_UNIDADES_FUNCIONALES3 USING (NATID_UNIDAD_FUNCIONAL3)
  JOIN MSTR_MAE_CENTROS USING (NATID_CENTRO)