DECLARE 
  ZOOMDATA_PAYLOAD VARCHAR2(32767);

BEGIN 
  ZOOMDATA_PAYLOAD := '{"product":"DVD", "price":"19.95", "quantity":20}';

  MSTR.PANDAS_095_ZOOMDATA_UPLOAD.SEND_JSON ( ZOOMDATA_PAYLOAD );
  COMMIT; 
END; 
