/* Formatted on 13/09/2013 13:00:09 (QP5 v5.163.1008.3004) */
DROP TABLE MSTR_DET_AH04A;

CREATE TABLE MSTR_DET_AH04A
NOLOGGING
NOMONITORING
NOPARALLEL
AS
     SELECT FCH_INGRESO NATID_DIA,
            NVL (CENTRO_INGRESO, -1) NATID_CENTRO,
            NVL (UNID_FUNC_INGRESO, -1) NATID_UNIDAD_FUNCIONAL,
            MODALIDAD_ASIST,
            COUNT (ADMISION_ID) AH04A,
            LAST_REFRESH_DATE
       FROM REP_HIS_OWN.ADM_ADMISION@EXP JOIN ALL_MVIEWS@EXP ON (OWNER = 'REP_HIS_OWN' AND MVIEW_NAME = 'ADM_ADMISION')
      WHERE EPIS_CONTAB = 1
   GROUP BY FCH_INGRESO,
            CENTRO_INGRESO,
            UNID_FUNC_INGRESO,
            MODALIDAD_ASIST,
            LAST_REFRESH_DATE;

ALTER TABLE MSTR_DET_AH04A ADD (
  CONSTRAINT MSTR_DET_AH04A_PK
  PRIMARY KEY
  (NATID_DIA, NATID_CENTRO, NATID_UNIDAD_FUNCIONAL, MODALIDAD_ASIST)
  USING INDEX)