DECLARE
   V_N_CONTRAALBARAN NUMBER;
   V_N_FACDIR        NUMBER;
BEGIN
   -- CONTRALBARANES
   SELECT SUM(TH_ALBARANES.IMP_IMPORTELINEA)
     INTO V_N_CONTRAALBARAN
     FROM DWSAS_SIGLO.TH_ALBARANES
    WHERE TO_NUMBER(TO_CHAR(ID_FECHACONFORMIDAD ,'YYYY')) = $ANYO
      AND FEC_BAJA IS NULL 
      AND IND_CONFIRMADA IN ('T');

   -- FACTURAS DIRECTAS
   SELECT SUM(IMP_TOTALLINEA)
     INTO V_N_FACDIR
     FROM (SELECT ID_FACTURA,
                  IMP_TOTALLINEA,
                  FEC_BAJA,
                  (CASE WHEN ID_GENERICOCENTRO IS NULL THEN 0 ELSE 1 END) "L_FACDIR",
                  ID_TIPODESCUENTO
             FROM DWSAS_SIGLO.TH_FACTURAS) TH,
          DWSAS_SIGLO.TD_FACTURA TD
    WHERE TH.ID_FACTURA = TD.ID_FACTURA
      AND TH.L_FACDIR = '1'
      AND TH.FEC_BAJA IS NULL 
      AND TO_NUMBER(TO_CHAR(TD.ID_FECHAFACTURA, 'YYYY')) = $ANYO
      AND TD.COD_ESTADO_FAC IN ('CONCILIADA', 'TRAMITADA')
      AND TH.ID_TIPODESCUENTO IS NULL;

   :1 := NVL(V_N_CONTRAALBARAN, 0) + NVL(V_N_FACDIR, 0);
END;
