/*
DECLARE
   V_N_CONTRAALBARAN NUMBER;
   V_N_FACDIR        NUMBER;
   V_N_FACABO        NUMBER;
BEGIN
   -- CONTRALBARANES
   SELECT SUM(EL.IMPORTELINEA)
     INTO V_N_CONTRAALBARAN
     FROM REP_PRO_SIGLO.PED_ENTRALMACLINEA EL,
          REP_PRO_SIGLO.PED_ENTRADAALMACEN E,
          REP_PRO_SIGLO.FAC_CONTRAALBARAN CON
    WHERE EL.confirmada = 'T'
      AND EL.ACTIVO = 'T'
      AND EL.entradaalmacen = E.ID
      AND EL.CONTRAALBARAN = CON.ID
      AND CON.FECHAREGISTRO IS NOT NULL
      AND TO_NUMBER(TO_CHAR(CON.FECHAREGISTRO, 'YYYY')) = $ANYO;

   -- FACTURAS DIRECTAS (A LAS DIRECTAS HAY QUE QUITARLES LAS QUE SEAN DE ABONO):
   SELECT SUM(NVL(FAL.BASEIMPONIBLE, 0) + NVL(FAL.IMPORTE, 0))
     INTO V_N_FACDIR
     FROM REP_PRO_SIGLO.FAC_FACTURA FA,
          REP_PRO_SIGLO.FAC_FACTURALINEA FAL
    WHERE FAL.FACTURA = FA.ID
      AND TO_NUMBER(TO_CHAR(FA.FECHAFACTURA, 'YYYY')) = $ANYO
      AND FAL.GCDIRECTA IS NOT NULL
      AND FA.ESTADO IN ('CONCILIADA', 'TRAMITADA')
      AND FAL.TIPODESCUENTO IS NULL
      AND FA.TIPO NOT IN (6,7,8);

   -- FACTURAS DE ABONO
   SELECT SUM(NVL(FAL.BASEIMPONIBLE, 0) + NVL(FAL.IMPORTE, 0))
     INTO V_N_FACABO
     FROM REP_PRO_SIGLO.FAC_FACTURA FA,
          REP_PRO_SIGLO.FAC_FACTURALINEA FAL
    WHERE FAL.FACTURA = FA.ID
      AND TO_NUMBER(TO_CHAR(FA.FECHAFACTURA, 'YYYY')) = $ANYO
      AND FAL.GCDIRECTA IS NOT NULL
      AND FA.ESTADO IN ('CONCILIADA', 'TRAMITADA')
      AND FAL.TIPODESCUENTO IS NULL
      AND FA.TIPO IN (6,7,8);

   :1 := NVL(V_N_CONTRAALBARAN, 0) + NVL(V_N_FACDIR, 0) - NVL(V_N_FACABO, 0);
 END;
*/

   SELECT SUM(EL.IMPORTELINEA) V_N_CONTRAALBARAN
    -- INTO V_N_CONTRAALBARAN
     FROM REP_PRO_SEV.PED_ENTRALMACLINEA@SIG EL,
          REP_PRO_SEV.PED_ENTRADAALMACEN@SIG E,
          REP_PRO_SEV.FAC_CONTRAALBARAN@SIG CON
    WHERE EL.confirmada = 'T'
      AND EL.ACTIVO = 'T'
      AND EL.entradaalmacen = E.ID
      AND EL.CONTRAALBARAN = CON.ID
      AND CON.FECHAREGISTRO IS NOT NULL
      AND TO_NUMBER(TO_CHAR(CON.FECHAREGISTRO, 'YYYY')) = 2013;

   SELECT SUM(EL.IMPORTELINEA) VALOR_CONTRAALBARAN/*, TO_NUMBER(TO_CHAR(CON.FECHAREGISTRO, 'YYYY')) AÑO*/, CON.FECHAREGISTRO NATID_DIA
    -- INTO V_N_CONTRAALBARAN
     FROM REP_PRO_SEV.PED_ENTRALMACLINEA@SIG EL,
          REP_PRO_SEV.PED_ENTRADAALMACEN@SIG E,
          REP_PRO_SEV.FAC_CONTRAALBARAN@SIG CON
    WHERE EL.confirmada = 'T'
      AND EL.ACTIVO = 'T'
      AND EL.entradaalmacen = E.ID
      AND EL.CONTRAALBARAN = CON.ID
      AND CON.FECHAREGISTRO IS NOT NULL
      GROUP BY /*TO_NUMBER(TO_CHAR(CON.FECHAREGISTRO, 'YYYY')),*/CON.FECHAREGISTRO ;
      
      SELECT * FROM REP_PRO_SEV.PED_ENTRALMACLINEA@SIG EL;
SELECT * FROM REP_PRO_SEV.PED_ENTRADAALMACEN@SIG E;
SELECT * FROM REP_PRO_SEV.FAC_CONTRAALBARAN@SIG CON;
