--PEDIDOS CON ENTREGA 'T'

  SELECT MIN (ENT.FECHAENTREGA), ENT.PEDIDOLINEA, MIN (PL.IMPORTELINEA)
    FROM REP_PRO_SEV.PED_PROGRAMENTREGA@SIG ENT JOIN REP_PRO_SEV.PED_PEDIDOLINEA@SIG PL ON (ENT.PEDIDOLINEA = PL.ID)
   WHERE ENT.ACTIVO = 'T' AND PL.ACTIVO = 'T'
GROUP BY ENT.PEDIDOLINEA
UNION ALL
--PEDIDOS SIN ENTREGA
SELECT PE.FECHAPEDIDO, PL.ID, (PL.IMPORTELINEA)
  FROM REP_PRO_SEV.PED_PEDIDOLINEA@SIG PL JOIN REP_PRO_SEV.PED_PEDIDO@SIG PE ON (PE.ID = PL.PEDIDO)
 WHERE PL.ACTIVO = 'T'
       AND PL.ID NOT IN (SELECT PEDIDOLINEA
                           FROM REP_PRO_SEV.PED_PROGRAMENTREGA@SIG ENT)
UNION ALL
-- PEDIDOS CON ENTREGA 'F'
SELECT PE.FECHAPEDIDO, PL.ID, (PL.IMPORTELINEA)
  FROM REP_PRO_SEV.PED_PEDIDOLINEA@SIG PL JOIN REP_PRO_SEV.PED_PEDIDO@SIG PE ON (PE.ID = PL.PEDIDO)
 WHERE PL.ACTIVO = 'T'
       AND PL.ID IN (SELECT PEDIDOLINEA
                       FROM REP_PRO_SEV.PED_PROGRAMENTREGA@SIG ENT
                      WHERE ENT.ACTIVO = 'F');

--GROUP BY PE.ID;

--select *
--FROM REP_PRO_SEV.PED_PROGRAMENTREGA@SIG ENT
--where ENT.PEDIDOLINEA =1904869
--/

SELECT *
  FROM REP_PRO_SEV.PED_PEDIDOLINEA@SIG PL
 WHERE id = 1904869