DECLARE
   CURSOR C_LINEAS IS
      SELECT PL.*
        FROM REP_PRO_SIGLO.PED_PEDIDOLINEA PL,
             REP_PRO_SIGLO.PED_PEDIDO PE
       WHERE PL.ACTIVO = 'T'
         AND PE.ID = PL.PEDIDO;

   V_I_GASTOS  NUMBER;
   V_N_CONT    NUMBER;
   V_F_ENTREGA DATE;
   V_F_PEDIDO  DATE;

BEGIN
   V_I_GASTOS := 0;

   FOR CAMPO IN C_LINEAS LOOP
      V_N_CONT := 0;

      SELECT COUNT(*)
        INTO V_N_CONT
        FROM REP_PRO_SIGLO.PED_PROGRAMENTREGA ENT
       WHERE ENT.ACTIVO = 'T'
         AND ENT.PEDIDOLINEA = CAMPO.ID;

      IF V_N_CONT>0 THEN
         SELECT MIN(PED_PROGRAMENTREGA.FECHAENTREGA)
           INTO V_F_ENTREGA
           FROM REP_PrO_SIGLO.PED_PROGRAMENTREGA
          WHERE PED_PROGRAMENTREGA.ACTIVO = 'T'
            AND PED_PROGRAMENTREGA.PEDIDOLINEA = CAMPO.ID;

         IF TO_NUMBER(TO_CHAR(V_F_ENTREGA, 'YYYY')) = $ANYO THEN
            V_I_GASTOS := V_I_GASTOS + NVL(CAMPO.IMPORTELINEA, 0);
         END IF;
      ELSE
         SELECT P.FECHAPEDIDO
           INTO V_F_PEDIDO
           FROM REP_PRO_SIGLO.PED_PEDIDO P
          WHERE P.ID=CAMPO.PEDIDO;

         IF TO_NUMBER(TO_CHAR(V_F_PEDIDO, 'YYYY')) = $ANYO THEN
            V_I_GASTOS := V_I_GASTOS + NVL(CAMPO.IMPORTELINEA, 0);
         END IF;
      END IF;
   END LOOP;

   :1 := V_I_GASTOS;
END;