/* Formatted on 02/09/2013 9:18:13 (QP5 v5.163.1008.3004) */
  SELECT FA.FECHAFACTURA NATID_DIA,
         FA.ORGANOGESTOR NATID_ORGANOGESTOR,
         SUM (NVL (FAL.BASEIMPONIBLE, 0) + NVL (FAL.IMPORTE, 0)) IMPORTE_FACTURAS                                     --,FA.ESTADO
    --    INTO V_I_FACTURA
    FROM REP_PRO_SEV.FAC_FACTURA@SIG FA, REP_PRO_SEV.FAC_FACTURALINEA@SIG FAL
   WHERE     FAL.FACTURA = FA.ID
         --     --AND TO_NUMBER(TO_CHAR(FA.FECHAFACTURA, 'YYYY')) = $ANYO
         AND FA.ESTADO IN ('CONCILIADA', 'PENDCONCILIAR', 'PENDREGISTRAR', 'REGISTRADA', 'TRAMITADA')
         AND FAL.TIPODESCUENTO IS NULL
         AND FA.TIPO NOT IN (6, 7, 8)
GROUP BY FA.FECHAFACTURA, FA.ORGANOGESTOR                                                                            --, FA.ESTADO