/* Formatted on 02/09/2013 9:46:49 (QP5 v5.163.1008.3004) */
SELECT                      --AVG(TO_DATE(TO_CHAR(FECHAMECANIZACION, 'DD/MM/YYYY')) - TO_DATE(TO_CHAR(FECHAENTRADA,'DD/MM/YYYY')))
      FECHAMECANIZACION, FECHAENTRADA, (FECHAMECANIZACION - FECHAENTRADA) FROM REP_PRO_SEV.FAC_FACTURA@SIG
--WHERE TO_NUMBER(TO_CHAR(FECHAFACTURA, 'YYYY')) = 2013