--select distinct NATID_UNIDAD_FUNCIONAL3
--from
--(
select    ROW_NUMBER () OVER (ORDER BY 1)  CustCol_2,
    a11.NATID_DIA  NATID_DIA,
    a11.NATID_CENTRO  NATID_CENTRO,
    a13.DESCR_CENTRO  DESCR_CENTRO,
    a11.NATID_UNIDAD_FUNCIONAL  NATID_UNIDAD_FUNCIONAL3,
    a15.DESCR_UNIDAD_FUNCIONAL3  DESCR_UNIDAD_FUNCIONAL3,
    a11.NATID_MODALIDAD_ASIST  NATID_MODALIDAD_ASIST,
    a14.DESCR_MODALIDAD_ASIST  DESCR_MODALIDAD_ASIST,
    sum(a11.AH04A)  WJXBFS1
from    MSTR_DET_HISTORICO_AH04A    a11
    cross join    DUAL    a12
    left join    MSTR_MAE_CENTROS    a13
      on     (a11.NATID_CENTRO = a13.NATID_CENTRO)
    left join    MSTR_MAE_MODALIDADES_ASIST    a14
      on     (a11.NATID_MODALIDAD_ASIST = a14.NATID_MODALIDAD_ASIST)
    left join    MSTR_MAE_UNIDADES_FUNCIONALES3    a15
      on     (a11.NATID_UNIDAD_FUNCIONAL = a15.NATID_UNIDAD_FUNCIONAL3)
where    a11.NATID_MODALIDAD_ASIST in (1)
and DESCR_UNIDAD_FUNCIONAL3 is null
group by    a11.NATID_DIA,
    a11.NATID_CENTRO,
    a13.DESCR_CENTRO,
    a11.NATID_UNIDAD_FUNCIONAL,
    a15.DESCR_UNIDAD_FUNCIONAL3,
    a11.NATID_MODALIDAD_ASIST,
    a14.DESCR_MODALIDAD_ASIST
    order by 2 desc
    --)