/* Formatted on 02/09/2013 15:09:43 (QP5 v5.163.1008.3004) */
CREATE MATERIALIZED VIEW MSTR_DET_GA06B
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS
SELECT FECHAFACTURA NATID_DIA,
       FA.ORGANOGESTOR NATID_ORGANOGESTOR, --AVG(TO_DATE(TO_CHAR(FECHAMECANIZACION, 'DD/MM/YYYY')) - TO_DATE(TO_CHAR(FECHAENTRADA,'DD/MM/YYYY')))
       /*FECHAMECANIZACION, FECHAENTRADA,*/
        AVG(TRUNC (FECHAMECANIZACION) - TRUNC (FECHAFACTURA)) GA06B
  FROM REP_PRO_SEV.FAC_FACTURA@SIG FA
  GROUP BY FECHAFACTURA,
       FA.ORGANOGESTOR
--WHERE TO_NUMBER(TO_CHAR(FECHAFACTURA, 'YYYY')) = 2013