/* Formatted on 15/08/2013 17:17:20 (QP5 v5.163.1008.3004) */
DROP MATERIALIZED VIEW MSTR_DET_GA01B;
CREATE MATERIALIZED VIEW MSTR_DET_GA01B
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS

SELECT NATID_DIA,
       NATID_ORGANOGESTOR,
       VALOR_CONTRAALBARAN,
       VALOR_FACTURAS_DIRECTAS,
       VALOR_FACTURAS_ABONO,
       (NVL (VALOR_CONTRAALBARAN, 0) + NVL (VALOR_FACTURAS_DIRECTAS, 0) - NVL (VALOR_FACTURAS_ABONO, 0)) GA01B
  FROM (  SELECT SUM (EL.IMPORTELINEA) VALOR_CONTRAALBARAN, CON.FECHAREGISTRO NATID_DIA, PED.ORGANOGESTOR NATID_ORGANOGESTOR
            FROM REP_PRO_SEV.PED_ENTRALMACLINEA@SIG EL,
                 REP_PRO_SEV.PED_ENTRADAALMACEN@SIG E,
                 REP_PRO_SEV.FAC_CONTRAALBARAN@SIG CON,
                 REP_PRO_SEV.PED_PEDIDO@SIG PED
           WHERE     EL.confirmada = 'T'
                 AND EL.ACTIVO = 'T'
                 AND EL.entradaalmacen = E.ID
                 AND EL.CONTRAALBARAN = CON.ID
                 AND CON.FECHAREGISTRO IS NOT NULL
                 AND E.PEDIDO = PED.ID
        GROUP BY CON.FECHAREGISTRO, PED.ORGANOGESTOR) CA
       FULL OUTER JOIN (  SELECT SUM (NVL (FAL.BASEIMPONIBLE, 0) + NVL (FAL.IMPORTE, 0)) VALOR_FACTURAS_DIRECTAS,
                                 FA.FECHAFACTURA NATID_DIA,
                                 FA.ORGANOGESTOR NATID_ORGANOGESTOR
                            FROM REP_PRO_SEV.FAC_FACTURA@SIG FA, REP_PRO_SEV.FAC_FACTURALINEA@SIG FAL
                           WHERE     FAL.FACTURA = FA.ID
                                 AND FAL.GCDIRECTA IS NOT NULL
                                 AND FA.ESTADO IN ('CONCILIADA', 'TRAMITADA')
                                 AND FAL.TIPODESCUENTO IS NULL
                                 AND FA.TIPO NOT IN (6, 7, 8)
                        GROUP BY FA.FECHAFACTURA, FA.ORGANOGESTOR) FD
          USING (NATID_DIA, NATID_ORGANOGESTOR)
       FULL OUTER JOIN (  SELECT SUM (NVL (FAL.BASEIMPONIBLE, 0) + NVL (FAL.IMPORTE, 0)) VALOR_FACTURAS_ABONO,
                                 FA.FECHAFACTURA NATID_DIA,
                                 FA.ORGANOGESTOR NATID_ORGANOGESTOR
                            FROM REP_PRO_SEV.FAC_FACTURA@SIG FA, REP_PRO_SEV.FAC_FACTURALINEA@SIG FAL
                           WHERE     FAL.FACTURA = FA.ID
                                 AND FAL.GCDIRECTA IS NOT NULL
                                 AND FA.ESTADO IN ('CONCILIADA', 'TRAMITADA')
                                 AND FAL.TIPODESCUENTO IS NULL
                                 AND FA.TIPO IN (6, 7, 8)
                        GROUP BY FA.FECHAFACTURA, FA.ORGANOGESTOR) FA
          USING (NATID_DIA, NATID_ORGANOGESTOR)