--SELECT * FROM REP_PRO_SEV.ORG_ORGANOGESTOR@SIG;
CREATE OR REPLACE VIEW MSTR_MAE_ORGANOSGESTORES
AS
SELECT ID NATID_ORGANOGESTOR, DESCRIPCION DESCR_ORGANOGESTOR
FROM REP_PRO_SEV.ORG_ORGANOGESTOR@SIG;