/* Formatted on 04/09/2013 11:46:05 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW MSTR_MAE_UNIDADES_FUNCIONALES1
(
   NATID_UNIDAD_FUNCIONAL1,
   DESCR_UNIDAD_FUNCIONAL1
)
AS
   SELECT '-1' NATID_UNIDAD_FUNCIONAL1, 'n/a' DESCR_UNIDAD_FUNCIONAL1 FROM DUAL
   UNION ALL
   SELECT UF_CODIGO NATID_UNIDAD_FUNCIONAL1, UF_NOMBRE DESCR_UNIDAD_FUNCIONAL1
     FROM REP_PRO_EST.UNIDADES_FUNCIONALES@EXP
    WHERE UF_UF_CODIGO IS NULL AND UF_AH_CODIGO IN (SELECT NATID_AREA_HOSPITALARIA FROM MSTR_UTL_CODIGOS);