CREATE TABLE MSTR_DET_HISTORICO_CAMAS
AS
SELECT 
NATID_DIA, NATID_CENTRO, NATID_UNIDAD_FUNCIONAL, 
   AH01A
FROM MSTR_DET_AH01A;



ALTER TABLE MSTR_DET_HISTORICO_CAMAS ADD (
  CONSTRAINT MSTR_DET_HISTORICO_CAMAS_PK
  PRIMARY KEY
  (NATID_DIA, NATID_CENTRO, NATID_UNIDAD_FUNCIONAL)
  USING INDEX);